### ISSUE TITLE
Is there a verbose option for the python interface?

### ISSUE THREAD

**Issue by ankur-gupta** [stevengj/nlopt#104]
I can set the `stop_options.verbose = 1` option in Octave to print the function evaluations:
```
nlopt_optimize eval #1: 13095
nlopt_optimize eval #2: 13055.6
nlopt_optimize eval #3: 13042
```

Is there a way to do the same in Python?

**Comment by stevengj** [comment]
Just put a `print` statement in your objective function.

**Comment by ankur-gupta** [comment]
Thanks, that 's what I did.

**Comment by smartalecH** [comment]
@stevengj it'd still be good to open the python API such that we can log optimizer verbose output, just like you can do with Julia.

**Comment by stevengj** [comment]
@smartalecH, the Julia API has no general verbose option either.

Are you thinking of algorithm-specific verbose options, e.g. `verbosity=1` for CCSA?  Those [can be set in Python too](https://nlopt.readthedocs.io/en/latest/NLopt_Python_Reference/#algorithm-specific-parameters).
