### ISSUE TITLE
Improve CMake build script with subprojects

### ISSUE THREAD

**Issue by jdumas** [stevengj/nlopt#106]
Hi,

The current CMake build script uses the variable `CMAKE_SOURCE_DIR` in at least 2 places: `test/CMakeLists.txt` (l.4), and `swig/CMakeLists.txt` (l.4). Those should be replaced in favor of `CMAKE_CURRENT_SOURCE_DIR` or `PROJECT_SOURCE_DIR`, to make it possible to compile `nlopt` as part of another project with a simple `add_subdirectory(nlopt)` command.

**Comment by jschueller** [comment]
I agree, use grep to list them all, there's also CMAKE_BINARY_DIR.
What are you waiting for proposing a PR :?
