### ISSUE TITLE
Cannot compile and link nlopt/octave/nlopt_optimize-mex.c

### ISSUE THREAD

**Issue by ktiwari9** [stevengj/nlopt#109]
I am a beginner trying to use the NLOpt toolbox with Matlab. I am following the example given [here](http://ab-initio.mit.edu/wiki/index.php/NLopt_Tutorial#Example_in_Matlab_or_GNU_Octave) but I get the error tried to use nlopt_optimize as a function. I am guessing this is because I haven't compiled the nlopt_optimize-mex.c file so I tried to run `mex -output nlopt_optimize nlopt_optimize-mex.c `but I still get the errors while compiling in matlab command prompt and I am unable to run the example. Could you please help me out here ?

**Comment by jschueller** [comment]
unfortunately the instructions are not up to date ; you need to ask @stevengj about that

**Comment by stevengj** [comment]
What OS are you on?  What error message are you getting? I haven't looked at this recently but you have to make sure that the NLopt shared library is someplace that Matlab can find it.

(I'd like to transfer all of the wiki documentation to github, e.g. via https://github.com/philipashlock/mediawiki-to-markdown)

**Comment by ktiwari9** [comment]
I am using Ubuntu 14.04LTE and it kept complaining "Tried to use nlopt_optimize as a function" . The instructions to install were outdated and after 3 days I finally made it work by writing a script within Matlab that can install and place the necessary binaries in the right place and link the library.

**Comment by jschueller** [comment]
I updated the matalab installation docs (to be published).
