### ISSUE TITLE
Last Result Returned Not Optimized Result

### ISSUE THREAD

**Issue by geoffviola** [stevengj/nlopt#110]
I'm using NLOpt 2.4.2 and noticed that the output is only the last values and not the optimal values. The problem is setup using the C++ API with inequality constraints and the COBYLA algorithm. When the x values, cost, and whether the constraints pass are printed in the objective callback and constraint callback; neither the less optimal constraint passing solution nor the more optimal constraint failing solution is returned. Instead, it returns a constraint failing suboptimal solution, which just happens to be the last solution. Has anyone else seen this behavior?

**Comment by jschueller** [comment]
duplicate of #57
