### ISSUE TITLE
Warning with UndefinedBehaviorSanitizer

### ISSUE THREAD

**Issue by jdumas** [stevengj/nlopt#111]
Hi,

Compiling nlopt with [UndefinedBehaviorSanitizer](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), it produces a few warnings that would be easy to get rid of.

`api/general.c:122:50: runtime error: signed integer overflow: 7412 * 314159 cannot be represented in type 'int'`

- Caused by the product `my_gettid() * 314159` in `nlopt_srand_time()`.

`api/options.c:277:11: runtime error: null pointer passed as argument 1, which is declared to never be null`

- Which happens when calling `nlopt_set_lower_bounds` on a problem of size 0. It happens e.g. on the dual problem of `mma()` when there are 0 constraints.

**Comment by jschueller** [comment]
- 47cd87db48fc26c0dfecb8eb9d14ca1b56245148
