### ISSUE TITLE
GN_ISRES integer overflow on large default population causes SEGV

### ISSUE THREAD

**Issue by RhysU** [stevengj/nlopt#113]
https://github.com/stevengj/nlopt/blob/master/isres/isres.c#L109 overflows an integer due to leading `population*n` when n = 47886 using a default population size of `20*(n+1)`.  Entertainingly, the 2 in `population*n*2` restores the value to be positive, holding off the impending doom until something SEGVs down in https://github.com/stevengj/nlopt/blob/master/isres/isres.c#L122.

May be worth writing that as `((size_t) population)*n*2 + population + population + n` to widen up to size_t.  May also be worth capping population using that integer-valued k*n + j expressions must not overflow INT_MAX.  Possibly something like `(((size_t)population)*n+n) < INT_MAX` right after the default population size is computed.

FWIW, I don't think ISRES will get me anywhere on that problem size.  Just the easiest derivative-free thing on which I can kick my problem's tires.  I'll drop the population below the default.

**Comment by RhysU** [comment]
Assuming I'm doing the math right, both

1. `population <= (INT_MAX - n) / (2 * (n + 1))` and
2. `population <= (INT_MAX - n) / n = INT_MAX / n - 1`

have to hold.  The first because of the malloc detail.  The second because of the `k*n+j` indexing.

**Comment by RhysU** [comment]
Something like the following seems to be behaving:
```
            fixed = self.opt.get_lower_bounds() == self.opt.get_upper_bounds()
            free = self.opt.get_dimension() - fixed.sum()
            int_max = np.iinfo(np.int32).max
            alloc_max = int((int_max - free) / (2 * (free + 1)))
            index_max = int((int_max / free) - 1)
            heuristic = 20 * (free + 1)
            if self.opt.get_population() == 0:
                self.opt.set_population(min(heuristic, alloc_max, index_max))
            if self.opt.get_population() > min(alloc_max, index_max):
                raise ValueError("Population {} > min({}, {})"
                                 .format(self.opt.get_population(),
                                         alloc_max,
                                         index_max))
```

**Comment by jschueller** [comment]
hard to reproduce without an actual example
