### ISSUE TITLE
"eliminate lb == ub dimensions" in optimize.c causes segfault for mconstraints

### ISSUE THREAD

**Issue by RhysU** [stevengj/nlopt#114]
For GN_ISRES using inequality or equality mconstraints in a problem where some lb == ub causes a segfault when the `if (c->f)` branch is taken within `nlopt_eval_constraint` in `stop.c`.

As far as I can tell, the problem is introduced by `elimdim_create(opt)` within `optimize.c`.  Specifically, setting a breakpoint at `elim_opt = elimdim_create(opt);` and inspecting with GDB shows `opt->fc->f == 0`, as expected.  Stepping past the `elimdim_create` invocation to the `ret = nlopt_optimize_(...)` callsite shows BOTH `*elim_opt->fc->f` and `*elim_opt->fc->mf` being non-null.  That makes no sense given the contents of `nlopt_eval_constraint`.

I think the root cause is that `elimdim_create` does not check for `f` vs `mf` before substituting `elimdim_func` or `elimdim_mfunc`.  This is suspect at several places within https://github.com/stevengj/nlopt/blob/master/api/optimize.c#L242.

A Python recreate is as follows:
```
#!/usr/bin/env python
# Setup
import nlopt
import numpy as np
from numpy.linalg import norm

def objective(x, grad):
    if grad.size > 0:
        grad[:] = 2*x
    return norm(x).item()

def inequality_mconstraint(result, x, grad):
    result[:] = 1 - x
    if grad.size > 0:
        grad[:] = -1

def equality_mconstraint(result, x, grad):
    result[:] = sum(x) - 10
    if grad.size > 0:
        grad[:] = 1

# 2.4.2
nlopt.__version__ 

# Convince yourself the setup is sane
dim = 3
guess = np.array([10] + (dim-1)*[0])

result, grad = np.arange(dim), np.arange(dim)

inequality_mconstraint(result, guess, grad)
print("{} {}".format(result, grad))

equality_mconstraint(result, guess, grad)
print("{} {}".format(result, grad))

obj = objective(guess, grad)
print("{} {}".format(obj, grad))

# Trigger the segfault
n = nlopt.opt(nlopt.GN_ISRES, dim)
n.set_min_objective(objective)
n.set_ftol_abs(1e-11)
n.add_inequality_mconstraint(inequality_mconstraint, dim*[1e-11])
n.add_equality_mconstraint(equality_mconstraint, dim*[1e-11])
n.set_maxeval(100*dim)
## WORKS AS EXPECTED:
# n.set_lower_bounds(np.repeat(0, dim))
# n.set_upper_bounds(np.repeat(25, dim))
## BREAKS WITH SEGFAULT:
n.set_lower_bounds([0] + [1] + (dim-2)*[0])
n.set_upper_bounds([25] + [1] + (dim-2)*[25])
print(n.optimize(guess))
```

**Comment by RhysU** [comment]
Fix may be as simple as amending some assignments in `elimdim_create` to read...
```
	  opt0->fc[i].f = opt0->fc[i].f ? elimdim_func : 0;
	  opt0->fc[i].mf = opt0->fc[i].mf ? elimdim_mfunc : 0
```
...along with...
```
	  opt0->h[i].f = opt0->h[i].f ? elimdim_func : 0;
	  opt0->h[i].mf = opt0->h[i].mf ? elimdim_mfunc : 0;
```
...or however you like writing it.  I've not tried out this fix.  `elimdim_makedata` seems oblivious to the `f` vs `mf` distinction.

**Comment by stevengj** [comment]
Thanks, I incorporated your suggested fix.
