### ISSUE TITLE
Website & download URLs down

### ISSUE THREAD

**Issue by IljaKroonen** [stevengj/nlopt#119]
I get the following while trying to install:

```
configure: Need to download and build NLopt
trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Warning in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  :
  unable to connect to 'ab-initio.mit.edu' on port 80.
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Execution halted
/bin/tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
```

The website, http://ab-initio.mit.edu/nlopt/, also does not display in my browser (ERR_CONNECTION_TIMED_OUT)

**Comment by stevengj** [comment]
Temporary server glitch, should now be fixed.

**Comment by gweis** [comment]
down again?

**Comment by znmeb** [comment]
Looks like the glitch has returned - <http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz> goes to <https://nlopt.readthedocs.io/en/latest/nlopt-2.4.2.tar.gz> which is an error page, not a tarball.

**Comment by stevengj** [comment]
@znmeb, that's a separate issue.   We are moving hosting to github, and it looks like one of the redirects got messed up.  cc @oskooi

**Comment by stevengj** [comment]
(The new URL is https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2.tar.gz)

**Comment by znmeb** [comment]
Thanks - the "nloptr" R package uses this - should I file a bug there to have them move their download to GitHub??

**Comment by stevengj** [comment]
Yes.

**Comment by JoshRosen** [comment]
It looks like the http://ab-initio.mit.edu server is currently down, preventing `nloptr` from being built. As suggested, I have commented on a `nloptr` bug mentioning the suggestion of updating the download link: https://github.com/jyypma/nloptr/issues/40#issuecomment-423073680

Should their download link be updated to point directly to the GitHub download link? Or should the uptime of http://ab-initio.mit.edu be improved? I'm not experienced enough with the R packaging ecosystem to sure which answer is right, so I'm cross-posting those question here.

**Comment by jschueller** [comment]
I'd use github, it should be more reliable plus you'll get the latest version 2.5.0.
Maybe @stevengj could remove or update the tarball on the website or point to github.

**Comment by JoshRosen** [comment]
@jschueller, I don't think that purposely removing the tarball on the website is a good idea because that effectively transforms a transient download issue into a _guaranteed_ download issue for anyone attempting to install an old version of `nloptr`.

Given that, I think it's preferable for `nloptr` to update their download link to point to GitHub, but I just wanted to check and make sure that the GitHub link is expected to stay around for the foreseeable future.

**Comment by stevengj** [comment]
Yes, the github link is the new "permanent" host.  That's why e.g. `http://ab-initio.mit.edu/nlopt` redirects to github.
