### ISSUE TITLE
http://ab-initio.mit.edu/nlopt is down

### ISSUE THREAD

**Issue by baogorek** [stevengj/nlopt#120]
The site's been down at least since yesterday. You can't get to it from the web, and here's the error message from `wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz`:

```
--2017-05-07 09:51:54--  (try:20)  http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
Connecting to ab-initio.mit.edu (ab-initio.mit.edu)|18.62.2.90|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.
```

**Comment by baogorek** [comment]
It's back up again. I'll go ahead and close.

**Comment by paliwal90** [comment]
@baogorek This is down again right now. Actually it gets down quite occasionally. Whats the problem? 
Sometimes it remains down for entire day sometimes for few hours. Why so?

**Comment by stevengj** [comment]
Been having server problems recently.  We're planning on transitioning to a new host to eliminate the issues.

**Comment by niharikag** [comment]
Now, this is down again.. please check it.

**Comment by fsluis** [comment]
And again...
