### ISSUE TITLE
ab-initio website down

### ISSUE THREAD

**Issue by GeraldCNelson** [stevengj/nlopt#123]
Trying to download this file http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz. The browser returns cannot open URL.

**Comment by stevengj** [comment]
Seems to be fine for me.

**Comment by jslee02** [comment]
@stevengj Out of curiosity, is there any specific reason not using the [GitHub's download link](https://github.com/stevengj/nlopt/archive/nlopt-2.4.2.tar.gz) instead of the MIT server's? I believe it's reasonably reliable.

**Comment by stevengj** [comment]
Because the tarball is created by `make dist` and contains some generated files.  It is not just a tagged release.  (To build the raw github you need e.g. SWIG.)
