### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by vthiery** [stevengj/nlopt#125]
I have started packaging nlopt as a Conan package [here](https://github.com/vthiery/conan-nlopt) and I would like to see a conan nlopt package be officially available in [conan-center](https://bintray.com/conan/conan-center). 
Although there is still quite some work to do to make sure we meet the requirements for official uploading, I would be happy to work on that and maintain the package in the future.

Usually, for convenience and separation of concerns, the recipe for the package is maintained in a separate repository (as I actually did already) but the recipe could be in nlopt's repository itself. Nevertheless, whoever is maintaining the recipe, wherever it is, a new package has to be uploaded manually upon release.

Which solution sounds better to you? If you want to have the recipe in this very repository, I'd be happy to start a branch and PR it.

**Comment by jschueller** [comment]
Hi,

"Usually, for convenience and separation of concerns", well, let's keep it that way ^^

Out of curiosity, what's your target os ? what is the rationale behind  this package manager ?

Regards.

**Comment by vthiery** [comment]
Hi,

I aim at providing a package for Linux, OSX and Windows. 

There are quite some advantages to use [conan.io](https://conan.io) but in a few words, it offers easy and cross platform dependencies management. When requiring a conan package in a build, it will gives you the specific binaries you need or build from source if not available.
