### ISSUE TITLE
Changing Omega value in Sbplx.c file in Neldermead folder and trying to compile the change

### ISSUE THREAD

**Issue by jamka1902** [stevengj/nlopt#129]
Hi, 

I want to test the change in optimization result with change in Omega value in Subplex algorithm. 
I just changed the number Omega from 0.1 to 0.01, 0.001, 0.0001, 0.00001 and tried just compiling the code by 
./configure
make
make install

and there was no change in the result. 
What am I missing here? I am kind of new bie in c++ and specially with handling big codes and makefiles. 
Can you tell me how do I proceed with this?

**Comment by jschueller** [comment]
Maybe this parameter has no effect for your particular problem.

**Comment by jamka1902** [comment]
it is the decay rate for the step size so, with changes up to 0.00001 (as I am using Subplex.c) the relaxation should just decay quick.

**Comment by jschueller** [comment]
you have to recompile your code too. maybe your code uses an nlopt library at another location ?
