### ISSUE TITLE
Bobyqa uninitialised variables in rare cases

### ISSUE THREAD

**Issue by ocommowi** [stevengj/nlopt#133]
Hello,

I know this is a follow-up to issue #36 but I do not know how to re-open it. I stumbled on the same problem (segmentation fault in altmov_ due to two variables being uninitialised) when using bobyqa together with the augmented lagrangian and a small tolerance as stopping criterion (10^-12). 

I ended up modifying the code of bobyqa a very little which made it work:

 - line 764 : int ksav = 1;
- line 768 : int ibdsav = 1;

This is only an ugly correction but I would be curious to know if someone has a better option to avoid this (I suspect all of this comes from the optimised parameters being a tiny little outside the bounds when entering bobyqa - from auglag - , which does not check for it)

Thanks

**Comment by jschueller** [comment]
hi, do you have an example that helps reproduce the issue ?

**Comment by jschueller** [comment]
gcc gives even more "-Wmaybe-uninitialized" warnings

**Comment by jschueller** [comment]
could you check if #134 does solve your problem ?

**Comment by ocommowi** [comment]
I would say yes, I am going to try, thanks ! However, in tour PR, I would be careful in bobyqa. Since it's a translation of a fortran code with indexes starting at 1, I think it is better to make the default values of the index variables (such as the ones I mentioned earlier) be 1 instead of 0. I might be wrong though, I get lost easily with these indexing problems

**Comment by jschueller** [comment]
I hope the code doesn't rely on it being uninitialized to something>1 then!
Please do test.
