### ISSUE TITLE
nloptr can not be installed on R.3.3.2

### ISSUE THREAD

**Issue by BeckHamed** [stevengj/nlopt#151]
nloptr can not be installed in R3.3.2
fail code:
collect2: error: ld returned 1 exit status
/usr/local/lib/R/share/make/shlib.mk:6: recipe for target 'nloptr.so' failed
make: *** [nloptr.so] Error 1
ERROR: compilation failed for package ‘nloptr’
* removing ‘/usr/local/lib/R/site-library/nloptr’

The downloaded source packages are in
	‘/tmp/RtmpLNN2Z5/downloaded_packages’
Warning message:
In install.packages("nloptr") :
  installation of package ‘nloptr’ had non-zero exit status

**Comment by jschueller** [comment]
go to https://github.com/jyypma/nloptr

**Comment by stevengj** [comment]
To clarify, the nlopt R plugin is developed separately from the core library, and an issue specifically in building the R plugin should be reported at the nloptr plugin page linked by @jschueller, not here.
