### ISSUE TITLE
NLopt for Matlab installation in Ubuntu

### ISSUE THREAD

**Issue by Virginia5632** [stevengj/nlopt#157]
I am quite new to Linux system, and trying to follow the installation instructions in
https://nlopt.readthedocs.io/en/latest/NLopt_Installation/
I have many issues and I only get the octave folder installed, not matlab...I was wondering if it is possible to get some step-by-step instructions...thanks

**Comment by Ariostgx** [comment]
I encountered the same problem as you, and I've been stuck here for several days. Have you found a solution?

**Comment by Virginia5632** [comment]
Hello. Unfortunately not. I could not install it. What I did was to look at the algorithms proposed on the description, find the one I wanted and search for an alternative. Fortunately the algorithm I wanted to use was also available directly as a matlab script in the webpage of the author. Good luck!

**Comment by jschueller** [comment]
Could you post the cmake output ? Maybe Matlab was not properly detected. Matlab_ROOT_DIR can be provided (via cmake -DMatlab_ROOT_DIR=/opt/xxx).

**Comment by jschueller** [comment]
no feedback, closing
