### ISSUE TITLE
NLOPT installation issue in Ubuntu 16.04 - python

### ISSUE THREAD

**Issue by XuanLin** [stevengj/nlopt#158]
I am trying to get run nlopt with python. I have swig and guile installed, but when I run cmake . I get the following error:
-- NLopt version 2.5.0
-- Could NOT find Guile (missing:  GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES) 

and when I do sudo make install, I get the following error:
[ 80%] Built target nlopt
[ 82%] Linking CXX shared module _nlopt.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
swig/CMakeFiles/_nlopt.dir/build.make:106: recipe for target 'swig/_nlopt.so' failed
make[2]: *** [swig/_nlopt.so] Error 1
CMakeFiles/Makefile2:140: recipe for target 'swig/CMakeFiles/_nlopt.dir/all' failed
make[1]: *** [swig/CMakeFiles/_nlopt.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Then I cannot import nlopt. Other stuff seems to be installed OK in /usr/local/lib (screenshot). The My swig version is 3.0.8, and guile version I tried both 1.8 and 2.0

![screenshot from 2017-11-10 16-16-42](https://user-images.githubusercontent.com/10069542/32636520-11a9c8f4-c56a-11e7-8652-dfabea0553fd.png)

**Comment by jschueller** [comment]
Where does /usr/local/lib/libpython2.7.a come from ? Try to link to system python libs please.

**Comment by XuanLin** [comment]
I tried to make install nlopt-2.4.2.tar.gz provided on the front page, and it doesn't work for some reason (maybe I didn't link it to the system). The libpython2.7.a is due to that. 
I remove those files and delete the nlopt-master folder, redo the cmake completely. Now it imports correctly.
Thanks!

**Comment by esdgdhln** [comment]
@XuanLin ,Hi,I got error,usr/local/lib/libnlopt.a(optimize.c.o): relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libnlopt.a: error adding symbols: 错误的值.
I don't know how  do you solve it well,can you tell me in detial?Thanks.
