### ISSUE TITLE
Returning number of function evaluations/iterations with python interface

### ISSUE THREAD

**Issue by abrahamnunes** [stevengj/nlopt#159]
Hi all, 

Sorry if this is the wrong place to post this question. Let me know, and if so I will move as necessary.

I'm running an experiment where I'm using BOBYQA from the nlopt package, I need to return the number of function evaluations and the number of iterations taken until solution. Perhaps I'm missing something somewhere in the documentation, but I can't seem to find out how to get these values with the Python interface.

Here is a simple demo program:

```python
import numpy as np
import nlopt


xatol  = 1e-6
fatol  = 1e-6
maxfev = 1e7

def f(x, grad):
    return np.sum(x**2)


x0 = np.random.uniform(-100, 100, size=2)
opt = nlopt.opt(nlopt.LN_BOBYQA, len(x0))

opt.set_min_objective(f) # Sets objective function
opt.set_xtol_abs(xatol)  # Absolute X tolerance
opt.set_ftol_abs(fatol)  # Absolute f tolerance
opt.set_maxeval(int(maxfev))  # Maximum number of function evaluations

xmin = opt.optimize(x0)
fmin = opt.last_optimum_value()

print(xmin)
print(fmin)
print(nlopt.SUCCESS)
print(nlopt.WANT_N_ITERATIONS_HERE)
print(nlopt.WANT_N_FUNC_EVALS_HERE)
```

Any help will be much appreciated.

Cheers,

Abe

**Comment by stevengj** [comment]
Just increment a global counter in your objective function.

**Comment by stevengj** [comment]
I guess we could provide a function to get this from `opt`, but it would have to be added in the underlying C library first.

**Comment by jschueller** [comment]
https://github.com/stevengj/nlopt/pull/160

**Comment by abrahamnunes** [comment]
Many thanks!

**Comment by constructor-igor** [comment]
please, could you publish sample how to get the iterations number?
I cannot find a relevant method in nlopt '2.5.0'.

**Comment by jschueller** [comment]
you can try (recent git version only):
```opt.get_numevals()```

**Comment by constructor-igor** [comment]
please, could you inform when are you going to release new nlopt version, which will include the method?

**Comment by jschueller** [comment]
A release is long overdue, but @stevengj is busy.
