### ISSUE TITLE
Cannot add a set of constraints with for loop?

### ISSUE THREAD

**Issue by XuanLin** [stevengj/nlopt#163]
Hi,

May I ask a question?

I am using nlopt-python. I want to do trajectory optimization and add constraints for 100 variables, so I am writing a small problem to try it out:

      min sum(x[0], ... x[9])
      s.t. -x[i+1]+x[i]+1<=0 for i=0 to 8
           -x[0]<=0

obviously, the solution is x0=0,  x1=1, ..., x9=9

For the first set of 9 constraints, I want to use for loop to add them, so I write the following:

      def constraint1(x, grad, step):
          if grad.size > 0:
              for i in range(10):
                  grad[i] = 0.0
              grad[step+1] = -1.0
              grad[step] = 1.0 
          result = -x[step+1]+x[step]+1.0
          return result

      for index in range(9):
           opt.add_inequality_constraint(lambda x,grad: constraint1(x, grad, index), 0)

It doesn't give the correct solution, while I try to separate the constraints individually (with the code exactly the same, just change "step" to actual numbers), it solves correctly. It looks like this constraint is not set properly. I tried multiple algorithms and similar situation happens.

So I cannot use for loop to add multiple constraints? Do I have to use add_inequality_mconstraint, or I wrote something wrong? Also, is there a way to get the constraint so I can verify it?

Thank you and have a good day!

**Comment by stevengj** [comment]
This is an unfortunate consequence of how closures (`lambda`) work in Python.  Each `lambda` is actually referring to the same `index` variable, so when `index` is updated in the loop, it changes the previous closures too.

For an explanation and workarounds, see:

https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture
