### ISSUE TITLE
questions about global optimization method 

### ISSUE THREAD

**Issue by mikeaalv** [stevengj/nlopt#164]
It is said in the documents: "All of the global-optimization algorithms currently require you to specify bound constraints on all the optimization parameters. "

Does that means lb and ub have to be set? Could it be -Inf and Inf?

My previous problem were made into (-inf, inf) by transformation, which made it easier for next step optimization and others.

**Comment by aphirst** [comment]
Bound constraints are used to do things like e.g. divide up the search space. The values of these bounds (at least the size, e.g. max-min) are obviously used in calculations to determine scaling factors and so on. If these are infinite, clearly this isn't going to work.

A search domain is hardly "bound" if the "bond" is at infinity.

If you have a problem which for whatever reason you've transformed to (-Inf,Inf), but want to use NLopt for global optimisation; to the best of my knowledge your best bet is going to be to un-transform (not transform it in the first place).
