### ISSUE TITLE
C++ reference from documentation crashes when change opt.set_maxeval

### ISSUE THREAD

**Issue by CxyCH** [stevengj/nlopt#165]
Hi:
  I am use the nlopt lib in my code with the code style in documentation

```
nlopt::opt opt = nlopt::opt(nlopt::GN_DIRECT_NOSCAL, 4);
	opt.set_min_objective(score_trajectory, this);

	opt.set_xtol_rel(0.0001);

	std::vector<double> lb;

	std::vector<double> rb;

	lb.push_back(0);

	lb.push_back(-1.8);

	lb.push_back(-1.8);

	lb.push_back(0);

	rb.push_back(5);

	rb.push_back(1.8);

	rb.push_back(1.8);

	rb.push_back(0.9);

	opt.set_lower_bounds(lb);

	opt.set_upper_bounds(rb);

	opt.set_maxeval(max_iter);
```
when I change the value of the max_iter in opt.set_maxeval(max_iter) from 12 to some bigger value, i get the crash:

`(x , y ,t) = (-6.30202 , 3.77268 | 10 )     (vx,vy) = ( 0 , 0 )
covariance = [ 0.4 , 0 , 0 , 0
               0 , 0.4 , 0 , 0
               0 , 0 , 0.1 , 0
               0 , 0 , 0 , 0.1 `

` *** Error in '/home/cxy/my_code/planner_debug/people_prediction/bin/local_nav_example': double free or corruption (out): 0x0000000000934e70 *** `

It runs ok when the max_iter is lower than 12... I could't figure out what is wrong with the code?

Best

**Comment by jschueller** [comment]
Could you please provide the complete code (if possible minimal) to reproduce the error ?

**Comment by jschueller** [comment]
no answer, closing
