### ISSUE TITLE
documentation quirk

### ISSUE THREAD

**Issue by btreut** [stevengj/nlopt#166]
I am not a markdown specialist, but as far as I can see, there is an excess $$ ... $$ pair in the source of https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/ which renders a passage starting with "Theremay,however,bemorethanonepoint ..." almost unreadable. In the source https://raw.githubusercontent.com/stevengj/nlopt/master/doc/docs/NLopt_Introduction.md , I found it on line 40, Col 531.

**Comment by stevengj** [comment]
Thanks!   Please feel free to submit a pull request (you can do it in the browser by clicking the edit button in https://github.com/stevengj/nlopt/blob/master/doc/docs/NLopt_Introduction.md) for things like this.
