### ISSUE TITLE
Cmake Error when installing Matlab plugin

### ISSUE THREAD

**Issue by Ariostgx** [stevengj/nlopt#167]
When I use the following code to trying to get the Matlab plugin installed
`cmake -DBUILD_SHARED_LIBS=OFF -DMatlab_ROOT_DIR=/usr/local/MATLAB/R2014a/ -DINSTALL_MEX_DIR=$HOME/shuhan/build/ -DCMAKE_INSTALL_PREFIX=$HOME/install..`
Cmake would return this 

>   Manually-specified variables were not used by the project: Matlab_ROOT_DIR

And when I run make in here, messages like the following kept coming out.

>  warning: ‘nlopt_minimize’ is deprecated (declared at /home/shuhan/build/nlopt/src/api/nlopt.h:333) [-Wdeprecated-declarations]

What should I do in order to correctly install the Matlab plugin?
 I've been stuck for several days. If anyone can help me? I'll appreciate it a lot!

**Comment by jschueller** [comment]
Matlab_ROOT_DIR is ok if you use latest cmake.
Those are only warnings, you can ignore them.

**Comment by Ariostgx** [comment]
However, I couldn't find the mex files in my
`DINSTALL_MEX_DIR`
directory, I think my optional variables were ignored.
Could you please tell me what is the default directory of mex files? Thank you!

**Comment by jschueller** [comment]
Are there any installed files ?
What's the output of "make install" ?

**Comment by Ariostgx** [comment]
Thank you, I’ve successfully installed an older version, with a different approach.
