### ISSUE TITLE
Can't link the libaries to MinGW

### ISSUE THREAD

**Issue by khajehei** [stevengj/nlopt#169]
Hello,
I have installed the Nlopt on Windows but the MinGW can't find the library lnlopt. in the lib folder I have libnlopt.

I would appreciate if you can help me with this.
![untitled](https://user-images.githubusercontent.com/22403761/35641227-70f7a8c6-0674-11e8-90a9-b132b20ee49e.png)

**Comment by jschueller** [comment]
Where did you install nlopt (If you used cmake what was the value of CMAKE_INSTALL_PREFIX) ?
You should have a flag -L/path/to/libnlopt in the link command

**Comment by khajehei** [comment]
When I create the link, I get the skipping incompatible. it is looking for
lnlopt but I have libnlopt in the folder.


[image: Inline image 1]

On Wed, Jan 31, 2018 at 11:10 AM, Julien Schueller <notifications@github.com

**Comment by jschueller** [comment]
You didnt answer my question about cmake. Where is libnlopt ? Did you use a prebuilt version ?

**Comment by jschueller** [comment]
no feedback. closing.
