### ISSUE TITLE
Error is not raised (Bug?)

### ISSUE THREAD

**Issue by flabowski** [stevengj/nlopt#170]
Hi everyone,
I posted the following problem on stackoverflow: https://stackoverflow.com/questions/48627491/what-happens-to-this-valueerror
However, I just noticed the error is raised as expected when changing the optimization algorithm. Therefore I think it might be a problem with nlopt.
What happens to the error? Could this possibly be a bug?

**Comment by jschueller** [comment]
On my machine the error is properly raised with or without the numpy line.
Which version of nlopt ? from where ? platform ?

**Comment by flabowski** [comment]
I am using WinPython-64bit-3.4.4.1 on Windows 10 with numpy version 1.11.3
The behaviour occurs with nlopt Version 2.0.12 and after updating with version 2.4.2 as well (from https://www.lfd.uci.edu/~gohlke/pythonlibs/#nlopt).
For some algorithms the error is raised, for the following ones not: 0, 1, 2, 3, 4, 5, 6, 7, 12, 19, 25, 28, 29, 35, 42
(by name: GN_DIRECT, GN_DIRECT_L, GN_DIRECT_L_RAND, GN_DIRECT_NOSCAL, GN_DIRECT_L_NOSCAL, GN_DIRECT_L_RAND_NOSCAL, GN_ORIG_DIRECT, GN_ORIG_DIRECT_L, LN_PRAXIS, GN_CRS2_LM, LN_COBYLA, LN_NELDERMEAD, LN_SBPLX, GN_ISRES, GN_ESCH)

**Comment by flabowski** [comment]
This is the code:

    import numpy as np
    import nlopt
    import sys

    def obj_func(params, grad):
        raise ValueError
        return 42.
    
    ub = np.array([175., 1.2])
    x0 = np.array([175., 1.0])
    lb = np.array([175., 0.8])
    
    opt = nlopt.opt(nlopt.GN_DIRECT, x0.size)
    opt.set_max_objective(obj_func)
    opt.set_lower_bounds(lb)
    opt.set_upper_bounds(ub)
    opt.set_maxeval(100)
    try:
        xopt = opt.optimize(x0)
        np.empty(0,)  # any numpy call. Uncommend this line
        print("No error. result code = ", opt.last_optimize_result())
        print("xopt: ", xopt)
    except:
        print("Error: ", sys.exc_info())
        print("result code = ", opt.last_optimize_result())

When adjusting the bounds to values that makes sense, everything is ok.

    ub = np.array([1., 1.2])
    x0 = np.array([0., 1.0])
    lb = np.array([-1., 0.8])

I guess obj_func is never called because of this. Maybe there should be an exception when the bounds are equal?

**Comment by solarjoe** [comment]
I can reproduce this issue with the same version (Python 3.4, NLopt 2.4.2)

But the strange thing is that it even depends on the Numpy statement, see below.
```
import numpy as np
import nlopt

def obj_func(params, grad):
    raise ValueError('test')

ub = np.array([175., 1.2])
x0 = np.array([175., 1.0])
lb = np.array([175., 0.8])

opt = nlopt.opt(nlopt.GN_DIRECT, x0.size)
opt.set_max_objective(obj_func)
opt.set_lower_bounds(lb)
opt.set_upper_bounds(ub)
opt.set_maxeval(12)

opt = opt.optimize(x0)
x = np.empty((5,)) #using this line raises the error as expected
#x = np.empty(5) #using this line skips the error
```

**Comment by jschueller** [comment]
definetely fixed, please use latest version
