### ISSUE TITLE
Installation Error - Mac

### ISSUE THREAD

**Issue by dportik** [stevengj/nlopt#174]
I'm having an issue installing on Mac OS 10.10. After downloading and running ./configure I am getting the following:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Programs/nlopt-2.4.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

When I look in the config.log file (attached) I see the following:
## ----------- ##

configure:2707: checking for a BSD-compatible install
configure:2775: result: /usr/bin/install -c
configure:2786: checking whether build environment is sane
configure:2841: result: yes
configure:2992: checking for a thread-safe mkdir -p
configure:3031: result: ./install-sh -c -d
configure:3038: checking for gawk
configure:3068: result: no
configure:3038: checking for mawk
configure:3068: result: no
configure:3038: checking for nawk
configure:3068: result: no
configure:3038: checking for awk
configure:3054: found /usr/bin/awk
configure:3065: result: awk
configure:3076: checking whether make sets $(MAKE)
configure:3098: result: yes
configure:3127: checking whether make supports nested variables
configure:3144: result: yes
configure:3273: checking whether to enable maintainer-specific portions of Makefiles
configure:3282: result: no
configure:3375: checking for gcc
configure:3391: found /usr/local/bin/gcc
configure:3402: result: gcc
configure:3631: checking for C compiler version
configure:3640: gcc --version >&5
gcc (GCC) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3651: $? = 0
configure:3640: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../gcc-5.1.0/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 5.1.0 (GCC) 
configure:3651: $? = 0
configure:3640: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3651: $? = 1
configure:3640: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3651: $? = 1
configure:3671: checking whether the C compiler works
configure:3693: gcc    conftest.c  >&5
ld: library not found for -lgcc
collect2: error: ld returned 1 exit status
configure:3697: $? = 1
configure:3735: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "nlopt"
| #define PACKAGE_TARNAME "nlopt"
| #define PACKAGE_VERSION "2.4.2"
| #define PACKAGE_STRING "nlopt 2.4.2"
| #define PACKAGE_BUGREPORT "stevenj@alum.mit.edu"
| #define PACKAGE_URL ""
| #define PACKAGE "nlopt"
| #define VERSION "2.4.2"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3740: error: in `/Programs/nlopt-2.4.2':
configure:3742: error: C compiler cannot create executables
See `config.log' for more details

I'm not understanding what the -lgcc library is and can't seem to find anyone else having this issue. When I type:
gcc -v

The following is produced:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../gcc-5.1.0/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 5.1.0 (GCC) 

Any idea what the problem could be here?

[config.log](https://github.com/stevengj/nlopt/files/1790635/config.log)

**Comment by jschueller** [comment]
There seem to be an issue with your compiler, maybe try clang since your're on mac. Or else you can try the cmake build in master. Anyways this doesnt look like a nlopt bug.
