### ISSUE TITLE
Nelder-Mead causes segfault

### ISSUE THREAD

**Issue by lucasnell** [stevengj/nlopt#178]
First off, thanks for this library. It's been super useful for our analyses.

The issue we're having is with the Nelder-Mead algorithm (I believe Sbplx does this too), but BOBYQA works great. This example gives me a segfault:
```cpp
#include <cmath>
#include <nlopt.h>

double f(unsigned n, const double* x, double* grad, void* f_data) {
    return std::sqrt(x[1]);
}

int main() {
    
    unsigned n = 2;
    double x[2] = { 0, 1 };
    double min_f;
    
    nlopt_opt opt = nlopt_create(NLOPT_LN_NELDERMEAD, n);
    
    nlopt_set_min_objective(opt, f, NULL);
    
    nlopt_set_ftol_rel(opt, 0.00000002);
    nlopt_set_maxeval(opt, 1000);
    
    nlopt_result res = nlopt_optimize(opt, x, &min_f);

    return 0;
}
```

Thanks for your help.

**Comment by jschueller** [comment]
Here it runs fine and returns NLOPT_XTOL_REACHED (Linux/gcc7.3).
What's your Platform/compiler ? NLopt version (git or 2.4.2) ?

**Comment by lucasnell** [comment]
I did some more checking, and this is not a nlopt issue at all. I was using it from R using the Rcpp and nloptr packages, so the issue is somewhere there. Thanks for confirming this isn't a nlopt problem.
