### ISSUE TITLE
Some installation documentation errors

### ISSUE THREAD

**Issue by jonathanlilly** [stevengj/nlopt#184]
In the installation documentation, INSTALL_MEX_DIR should be MEX_INSTALL_DIR

Also, the cmake installation commands in the documentation work with the GitHub version, but not with the nlopt-2.4.2.tar.gz version from the web site. 

https://nlopt.readthedocs.io/en/latest/NLopt_Installation/

**Comment by jschueller** [comment]
You're looking at the documentation for master, which is right for INSTALL_MEX_DIR and cmake.
We should definetely get a release out.
