### ISSUE TITLE
Failed to install in Linux

### ISSUE THREAD

**Issue by Panadestein** [stevengj/nlopt#188]
Hello everyone,
I was trying to install NLopt in the cluster on my university, but the installation fails in the 'make' stage (I think some issue related with SWING). The problem is that the cluster has a prehistoric Python version as default (the one that cmake finds), and newer version has to be loaded as module. So I modified the CMakeLists.txt file as follows:
`if (NLOPT_PYTHON)
  find_package (PythonInterp 3.6.5 REQUIRED)
  find_package (PythonLibs 3.6.5 REQUIRED)
  find_package (NumPy)
endif ()
`
After this, cmake successfully founded Python 3.6.5, however, when I executed 'make' I got all this error messages:
`[ 77%] Built target nlopt
[ 79%] Building CXX object src/swig/CMakeFiles/_nlopt.dir/nloptPYTHON_wrap.cxx.o
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'swig_module_info* SWIG_Python_GetModule()':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:2452: error: 'PyCObject_Import' was not declared in this scope
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'void SWIG_Python_SetModule(swig_module_info*)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:2521: error: 'PyCObject_FromVoidPtr' was not declared in this scope
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'swig_type_info* SWIG_Python_TypeQuery(const char*)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:2544: error: 'PyCObject_AsVoidPtr' was not declared in this scope
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:2549: error: 'PyCObject_FromVoidPtr' was not declared in this scope
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'std::vector<double, std::allocator<double> >* std_vector_Sl_double_Sg____getitem____SWIG_0(std::vector<double, std::allocator<double> >*, PySliceObject*)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:4228: error: cannot convert 'PySliceObject*' to 'PyObject*' for argument '1' to 'int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)'
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'void std_vector_Sl_double_Sg____setitem____SWIG_0(std::vector<double, std::allocator<double> >*, PySliceObject*, const std::vector<double, std::allocator<double> >&)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:4237: error: cannot convert 'PySliceObject*' to 'PyObject*' for argument '1' to 'int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)'
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'void std_vector_Sl_double_Sg____delitem____SWIG_1(std::vector<double, std::allocator<double> >*, PySliceObject*)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:4246: error: cannot convert 'PySliceObject*' to 'PyObject*' for argument '1' to 'int PySlice_GetIndices(PyObject*, Py_ssize_t, Py_ssize_t*, Py_ssize_t*, Py_ssize_t*)'
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx: In function 'const char* pytype_string(PyObject*)':
/home/ramon/nlopt/src/swig/nloptPYTHON_wrap.cxx:4461: error: 'PyString_Check' was not declared in this scope
make[2]: *** [src/swig/CMakeFiles/_nlopt.dir/nloptPYTHON_wrap.cxx.o] Error 1
make[1]: *** [src/swig/CMakeFiles/_nlopt.dir/all] Error 2
make: *** [all] Error 2
`
Any idea of what is going wrong here? Thanks a lot in advance.

**Comment by jschueller** [comment]
Python Interpreter and libs should be of same version. Most likely it is using the old python libs from the previous cmake run, try removing CMakeCache.txt then re-running cmake. If its still not found you can try to play with cmake vars to point to the right Python location of includes and libs: https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html.
