### ISSUE TITLE
Error "dyld: Library not loaded: @rpath/libnlopt.0.dylib" in running tutorial

### ISSUE THREAD

**Issue by yip8** [stevengj/nlopt#190]
I successfully ran `cc tutorial.c -o tutorial -lnlopt -lm`
But afterwards when I do `./tutorial`
I receive the error of `dyld: Library not loaded: @rpath/libnlopt.0.dylib` with `Reason: image not found`

May I ask how to deal with this? I installed nlopt in OS.9.4. Thank you very much!

**Comment by jschueller** [comment]
try setting DYLD_FALLBACK_LIBRARY_PATH and co.
not an nlopt bug, closing.
