### ISSUE TITLE
New Bayesian global optimizer

### ISSUE THREAD

**Issue by sovrasov** [stevengj/nlopt#192]
Hello. I have an implementation of one Bayesian-like global optimization method https://github.com/sovrasov/glob_search_nlp_solver. It can handle nonlinear objective functions and functional constraints which satisfy the Lipschitz condition. My implementation supports dimension < 6. According to the NLOpt documentation most of the other methods (like DIRECTl) doesn't handle non-linear constraints (supports only boundary ones). On unconstrained problems this method performs not worse than DIRECT (see [paper](https://ac.els-cdn.com/S1877050915033578/1-s2.0-S1877050915033578-main.pdf?_tid=db39d1fb-74b8-403a-8e04-033aafd9f5ba&acdnat=1531228193_9cf5d8849f2af3cb2802b7fbe4e4e511))
I can prepare PR to NLOpt. Will it be useful?

**Comment by stevengj** [comment]
Sounds great!

**Comment by sovrasov** [comment]
@stevengj I'll try to submit a PR as soon as I study the internal structure of NLOpt.

**Comment by stevengj** [comment]
Closed by #194.
