### ISSUE TITLE
nlopt CMake fails on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by arbenede** [stevengj/nlopt#204]
I am tryhing to build nlopt under Ubuntu 18.04.1 and I am getting this error:

```
arrigo@arrigo-Z370N-WIFI:~/nlopt/nlopt-2.5.0$ cmake .
-- NLopt version 2.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sysconfig'
CMake Error at CMakeLists.txt:297 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at CMakeLists.txt:298 (file):
  file RELATIVE_PATH called with incorrect number of arguments


-- Could NOT find Guile (missing: GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES) 
-- Could NOT find Octave (missing: OCTAVE_EXECUTABLE OCTAVE_ROOT_DIR OCTAVE_LIBRARIES) 
-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MX_LIBRARY) (found version "NOTFOUND")
-- Configuring incomplete, errors occurred!
See also "/home/arrigo/nlopt/nlopt-2.5.0/CMakeFiles/CMakeOutput.log".
See also "/home/arrigo/nlopt/nlopt-2.5.0/CMakeFiles/CMakeError.log".
```
Any ideas?

Thanks!

-Arrigo

**Comment by jschueller** [comment]
Can you remove thé cmakecache file,  rerun cmake and provide the full cmake output ?

**Comment by pkairys** [comment]
I've also gotten this same error today. I'm running on OSX 10.10.5. The full Cmake output I get is: 

> paulkairys$ cmake -DPYTHON_EXECUTABLE=python -DNLOPT_CXX=OFF ..

> -- The C compiler identification is AppleClang 6.1.0.6020049
> -- The CXX compiler identification is AppleClang 6.1.0.6020049
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- NLopt version 2.5.0
> -- Looking for dlfcn.h
> -- Looking for dlfcn.h - found
> -- Looking for getopt.h
> -- Looking for getopt.h - found
> -- Looking for unistd.h
> -- Looking for unistd.h - found
> -- Looking for string.h
> -- Looking for string.h - found
> -- Looking for strings.h
> -- Looking for strings.h - found
> -- Looking for inttypes.h
> -- Looking for inttypes.h - found
> -- Looking for memory.h
> -- Looking for memory.h - found
> -- Looking for stdlib.h
> -- Looking for stdlib.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for time.h
> -- Looking for time.h - found
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for sys/stat.h
> -- Looking for sys/stat.h - found
> -- Looking for sys/time.h
> -- Looking for sys/time.h - found
> -- Looking for getpid
> -- Looking for getpid - found
> -- Looking for syscall
> -- Looking for syscall - found
> -- Looking for isinf
> -- Looking for isinf - found
> -- Looking for isnan
> -- Looking for isnan - found
> -- Looking for gettimeofday
> -- Looking for gettimeofday - found
> -- Looking for qsort_r
> -- Looking for qsort_r - found
> -- Looking for time
> -- Looking for time - found
> -- Looking for copysign
> -- Looking for copysign - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of uint32_t
> -- Check size of uint32_t - done
> -- Check size of unsigned int
> -- Check size of unsigned int - done
> -- Check size of unsigned long
> -- Check size of unsigned long - done
> -- Looking for sqrt in m
> -- Looking for sqrt in m - found
> -- Looking for fpclassify
> -- Looking for fpclassify - TRUE
> -- Performing Test HAVE_THREAD_LOCAL_STORAGE
> -- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
> -- Performing Test HAVE_THREAD_LOCAL_STORAGE
> -- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
> -- Looking for __cplusplus
> -- Looking for __cplusplus - found
> -- Performing Test SUPPORTS_STDCXX11
> -- Performing Test SUPPORTS_STDCXX11 - Success
> -- Found PythonInterp: /Users/paulkairys/Documents/Research/nlopt/build/python (found version "1.4") 
> -- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found version "3.7.0") 
> CMake Error at CMakeLists.txt:298 (get_filename_component):
>   get_filename_component called with incorrect number of arguments
> 
> 

> CMake Error at CMakeLists.txt:299 (file):
>   file RELATIVE_PATH called with incorrect number of arguments
> 
> 
> -- Could NOT find Guile (missing: GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES) 
> -- Found SWIG: /opt/local/bin/swig (found version "3.0.10") 
> -- Could NOT find Octave (missing: OCTAVE_EXECUTABLE OCTAVE_ROOT_DIR OCTAVE_LIBRARIES) 
> CMake Error at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindMatlab.cmake:1171 (file):
>   file STRINGS file "/usr/local/texlive/2014/bin/VersionInfo.xml" cannot be
>   read.
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindMatlab.cmake:1448 (_Matlab_get_version_from_root)
>   CMakeLists.txt:321 (find_package)
> 
> 
> CMake Error at /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindMatlab.cmake:1173 (string):
>   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
>   command.
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.12.1/share/cmake/Modules/FindMatlab.cmake:1448 (_Matlab_get_version_from_root)
>   CMakeLists.txt:321 (find_package)
> 
> 
> -- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION MX_LIBRARY) (found version "unknown")
> -- Configuring incomplete, errors occurred!
> See also "/Users/paulkairys/Documents/Research/nlopt/build/CMakeFiles/CMakeOutput.log".


It looks like the latest build was updated pretty recently. Could something have gotten broken?

**Comment by stevengj** [comment]
Looks like a problem in your `cmake` installation — it apparently has a broken `FindMatlab.cmake` script.

**Comment by pkairys** [comment]
I just reinstalled `cmake` to version 3.12.1. This didn't solve it. I get the same issue. 

 I do not have Matlab or Octave installed. I use python pretty exclusively. Is there a way to make it *not* look for either of those programs?

Thanks

**Comment by stevengj** [comment]
`cmake -DNLOPT_OCTAVE=Off -DNLOPT_MATLAB=Off -DNLOPT_GUILE=Off`

**Comment by pkairys** [comment]
This solved it for me. Thanks Steven!

**Comment by jschueller** [comment]
Also the full path to the python executable has to be provided when overriding PYTHON_EXECUTABLE.
cmake 3.12.x findmatlab is broken, will be fixed in next version.
