### ISSUE TITLE
Problems when running with Matlab

### ISSUE THREAD

**Issue by DuAlexander** [stevengj/nlopt#208]
Hi, I'm a total beginner with nlopt. When I was trying to run the example in[https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/#example-in-matlab-or-gnu-octave](url), I got an error 

> Attempt to execute SCRIPT nlopt_optimize as a function

How can I tackle this problem? Many thanks in advance.

**Comment by jschueller** [comment]
running a script with matlab is trickier than with octave, try in the interpreter first.
