### ISSUE TITLE
optimising negative and positive values 

### ISSUE THREAD

**Issue by DetlevCM** [stevengj/nlopt#214]
I have a code that uses nlopt for the optimisation and today encountered a problem:
If all values to be optimised are positive, it works.
If one value is negative while the others are positive, it fails. (Basically just crashes.)

I have worked around this for now by moving the sign flip to where the value is used which works, but obviously produces a potential for error in the future...

The optimisation method used is CRS2, the version of nlopt is that supplied with openSUSE.
Yast tells me the following: v2.4.2-29.8, built 28 Aug 2018 21:53:27 CEST

(I don't think I will be able to provide a lot more detail than what I can write in this post - so sorry in this respect.)

**Comment by stevengj** [comment]
What is the stacktrace for the crash?

**Comment by DetlevCM** [comment]
Ehm, no idea... Do you have any easy instructions on how to get one? (A link with quick instructions on what to do, to obtain it.)

I'm compiling in Eclipse CDT on Linux.

**Comment by DetlevCM** [comment]
OK, I still have no idea how to get a stacktrace, but I cobbled together a (not very well written) minimum working example using  a quadratic equation that shows the same behaviour.
Works for (2,2), fails for (-2,2) - both are solutions to the "problem":
[Error-Test.txt](https://github.com/stevengj/nlopt/files/2359897/Error-Test.txt)

I hope this helps?

**Comment by jschueller** [comment]
It does not crash, just throws std::invalid_argument with "nlopt invalid argument" as your bounds are invalid: bound_lower[0] > bound_upper[0]
