### ISSUE TITLE
bug: more than iter SQP iterations?

### ISSUE THREAD

**Issue by kecaiwu** [stevengj/nlopt#215]
I have an optimization problem, there are 24 optimization variables. I choose the slsqp algorithm, however, the program gives me the "bug: more than iter SQP iterations" error? what happened? thank you.

**Comment by kecaiwu** [comment]
Each case should add "break" at the end, you can check the code in 'slsqp.c', 'case9' is the last one that is the default case. However, your error from other cases, maybe 'case4' or 'case5' ...

**Comment by jschueller** [comment]
why did you close ? is there a bug in the switch/case, or ?

**Comment by reem21090** [comment]
> Each case should add "break" at the end, you can check the code in 'slsqp.c', 'case9' is the last one that is the default case. However, your error from other cases, maybe 'case4' or 'case5' ...

What if I use the nlopt optimization inside a loop that I don't want to break?

This is how the loop looks and the error appears in the 2nd iteration "RuntimeError: bug: more than iter SQP iterations"
`while m<n_tests:
    opt = nlopt.opt(nlopt.LD_SLSQP, nvar)
    opt.set_lower_bounds(lb)
    opt.set_upper_bounds(ub)
    opt.set_xtol_rel(1e-4)
    opt.set_min_objective(wrap_myfunc)
    test_points = [0] * nvar
    for rand_n in range(nvar):
        test_points[rand_n] = random.randint(lb[rand_n], ub[rand_n])
    print('test_points', test_points)
    CV = problem.evaluate(test_points, return_values_of=["CV"])
    if CV>0:
        x = opt.optimize(lb)
        print('lb', lb)
    else:
        x = opt.optimize(test_points)
        print('ub', ub)
    minf = opt.last_optimum_value()
    print("optimum at ", x)
    print("minimum value = ", minf)
    print("result code = ", opt.last_optimize_result())
    m = m + 1`

**Comment by kecaiwu** [comment]
@reem21090 You may check the gradient computing and initial value of the optimal variable. If those are right, the bug will not happen. By the way, I solve my optimal problem by NLPQLP library.

**Comment by kkew3** [comment]
I encountered exactly the same problem. I'm optimizing a three-variable constrained problem. The optimal solution is very closed to the constraint boundary. However, the very initial value worked when I used `alglib`'s optimization routine.

**Comment by odow** [comment]
@stevengj can we re-open this issue? Here is a minimal example:
```C
#include <nlopt.h>
#include <stdio.h>

double callback(unsigned int n, const double *x, double *grad, void* user_data) {
    if (grad != NULL) {
        grad[0] = 1.0e8 * x[1] * x[1];
        grad[1] = 2.0e8 * x[0] * x[1];
    }
    return 1.0e8 * x[0] * x[1] * x[1];
}

int main() {
    nlopt_opt opt = nlopt_create(NLOPT_LD_SLSQP, 2);;
    double lb[2] = {0, -10};
    nlopt_result ret = nlopt_set_lower_bounds(opt, lb);
    ret = nlopt_set_min_objective(opt, callback, NULL);
    double obj_f = 0.0;
    double x[2] = {1.0, -1.0};
    ret = nlopt_optimize(opt, x, &obj_f);
    const char* msg = nlopt_get_errmsg(opt);
    printf("%s\n", msg);
    nlopt_destroy(opt);
    return 0;
}
```

which yields:
```
(base) oscar@Oscars-MBP build % clang \
    /tmp/nlopt.c \
    -I/Users/Oscar/Documents/Code/nlopt/src/api \
    -L/Users/Oscar/Documents/Code/nlopt/build/ -lnlopt \
    -Wl,-rpath,/Users/Oscar/Documents/Code/nlopt/build \
    -o /Users/Oscar/Documents/Code/nlopt/build/bug

(base) oscar@Oscars-MBP build % ./bug  
bug: more than iter SQP iterations
```
