### ISSUE TITLE
THREADLOCAL is unset when configuring project twice

### ISSUE THREAD

**Issue by jpo38** [stevengj/nlopt#216]
Run CMake once for Visual Studio, nlopt_config.h contains `#define THREADLOCAL __declspec(thread)`
Run CMake again, nlopt_config.h contains `#define THREADLOCAL`

This is because in CMakeLists.txt, `HAVE_THREAD_LOCAL_STORAGE` is cached but not `THREADLOCAL`. So on second call to CMake, `THREADLOCAL`. is not set and remains empty.

**Comment by jschueller** [comment]
@jpo38 does #217 fix your issue ?

**Comment by jpo38** [comment]
@jschueller Absolutely!
