### ISSUE TITLE
Building with(out) languages and with prefix?

### ISSUE THREAD

**Issue by gabrielgggg** [stevengj/nlopt#218]
Hello!
Since the switch to cmake I can't seem to find any guidance on how to opt-out of the buildings for Python, Matlab, etc. and also how to provide an alternative install location (I do not have root on the machine in question so I need to install in ~/lib and ~/include, etc.)

I am looking to build the library for C and Fortran, with ICC/ICPC, maybe with -O3 and -xHost? Any hints are greatly appreciated!

**Comment by jschueller** [comment]
see https://nlopt.readthedocs.io/en/latest/NLopt_Installation/ for the install location
and https://github.com/stevengj/nlopt/blob/master/CMakeLists.txt#L42 for the options
