### ISSUE TITLE
Stochastic population

### ISSUE THREAD

**Issue by sguazt** [stevengj/nlopt#22]
Hi,

In the Algorithm wiki page
 http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms
there is a reference to the deprecated function  nlopt_set_stochastic_population.
If I'm not wrong, this parameter should be set via the member stochastic_population of struct nlopt_opt. Is it?

Also, I didn't find a method in the C++ interface nlopt::opt to set it.

Thank you for the help.

Best,
  Marco

**Comment by jacopo-chevallard** [comment]
Can you confirm that in Fortran as well, one should only call the routine ``nlo_set_population`` instead of the ``nlopt_set_stochastic_population``? 

On the [wiki](http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms), indeed, fir the ISRES and CRS algorithms it is said that
>  population size, ..., can be changed with the nlopt_set_stochastic_population function

**Comment by stevengj** [comment]
Yes, I've corrected the wiki.
