### ISSUE TITLE
Wrong "Edit on GitHub" link in the docs

### ISSUE THREAD

**Issue by mortenfyhn** [stevengj/nlopt#220]
I was just browsing the docs and noticed this:

If I hit the "Edit on GitHub" buttom from for instance https://nlopt.readthedocs.io/en/latest/, it takes me to https://github.com/stevengj/NLopt/edit/master/docs/index.md which gives a 404.

**Comment by stevengj** [comment]
Fixed by 3ba0cc349a05bc1dacd13f69f823b6b3fdb92799
