### ISSUE TITLE
Documentation Page Down

### ISSUE THREAD

**Issue by weakunix** [stevengj/nlopt#223]
There seems to be a typo -- missing a colon in hyperlink:
https//github.com/stevengj/NLopt

see [here](https://nlopt.readthedocs.io/en/latest/NLopt_C-plus-plus_Reference/)

**Comment by weakunix** [comment]
i see the hyperlink has been fixed, but all the documentation pages are basically blank still. Is this a transient state or should the docs be accessed at a different link?

**Comment by jschueller** [comment]
no clue

**Comment by stevengj** [comment]
Should be fixed now?
