### ISSUE TITLE
Cannot find Matlab interface

### ISSUE THREAD

**Issue by wje1581** [stevengj/nlopt#225]
Hi there

I followed the instructions to install like 
cd nlopt 
mkdir build 
cd build 
cmake .. 
make 
sudo make install

except that I do not have admin so I cmake to another location. But I could not find the matlab file after installation. There is no error message.

I guessed that cmake might be unable to locate my matlab root, so I added
-DMatlab_ROOT_DIR=/hpc/software/matlab/r2016a
, but the result says this variable is not used by the project.

Would anybody kindly suggest why this happens? Or, if it works, would you mind upload the compiled mex file so I could use it in my program directly?

Many thanks!

**Comment by jschueller** [comment]
it could help to post the cmake output, cmake version, nlopt version

**Comment by wje1581** [comment]
> it could help to post the cmake output, cmake version, nlopt version

See below. nlopt-2.5.0. cmake version 2.8.12.2

==========================================


[wje1581@klc02 build]$ cmake -DMatlab_ROOT_DIR=/hpc/software/matlab/r2016a ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- NLopt version 2.5.0
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for syscall
-- Looking for syscall - found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for time
-- Looking for time - found
-- Looking for copysign
-- Looking for copysign - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Looking for fpclassify
-- Looking for fpclassify - TRUE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Failed
-- Looking for __cplusplus
-- Looking for __cplusplus - found
-- Performing Test SUPPORTS_STDCXX11
-- Performing Test SUPPORTS_STDCXX11 - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
-- Found NumPy: version "1.7.1" /usr/lib64/python2.7/site-packages/numpy/core/include
-- Could NOT find Guile (missing:  GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES) 
-- Found SWIG: /usr/bin/swig (found version "2.0.10") 
-- Could NOT find Octave (missing:  OCTAVE_EXECUTABLE OCTAVE_ROOT_DIR OCTAVE_LIBRARIES) 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    Matlab_ROOT_DIR


-- Build files have been written to: /home/wje1581/nlopt-2.5.0/build

**Comment by jschueller** [comment]
Could you try MATLAB_ROOT instead ?

**Comment by wje1581** [comment]
> Could you try MATLAB_ROOT instead ?

Same result. Variable not used by project. ;(

I read through the cmake and make install log, there's basically nothing related to matlab. Is is a version problem?

**Comment by stevengj** [comment]
It looks like `FindMatlab` changed significantly in recent `cmake` versions, and in particular the `Matlab_ROOT_DIR` variable may have been introduce only in `cmake` version 3.3?

Try using a newer `cmake` version.

**Comment by wje1581** [comment]
> It looks like `FindMatlab` changed significantly in recent `cmake` versions, and in particular the `Matlab_ROOT_DIR` variable may have been introduce only in `cmake` version 3.3?
> 
> Try using a newer `cmake` version.

Problem solved with cmake 3.12.0. Thanks professor and @jschueller 

For those unfamiliar with linux as me, check your available cmake versions with **module avail cmake**. Probably there is a newer version but the older is loaded by default...
