### ISSUE TITLE
Lots of C/C++ warnings ...

### ISSUE THREAD

**Issue by taliesin** [stevengj/nlopt#226]
I'm compiling nlopt within an embedded project which has -Wall -Wextra turned on by default and get lots of warnings:

- warning: variable 'xxxx' set but not used [-Wunused-but-set-variable]
- deprecated declaration in f77api.c

I made myself ready to fix them, but now I'm unsure if there is some intention behind these unused variables? If they need to stay in I'd suggest to use `(void) XXX;` to silence the warnings, otherwise I'd remove them, please advise.
For the deprecated functions in f77api.c and f77funcs.h I'd add a GCC pragma (with correct ifdefs) to turn the warning off for these files.

**Comment by stevengj** [comment]
It would be good to silence the warnings.

For unused variables, they can usually be removed if they are local variables, but if they are function arguments then we probably want to `(void)` them for now to preserve the API.

**Comment by bjodah** [comment]
FWIW, a neat way I've seen used for unused variables in function signatures looks like:

```c++
double f(double x, double /* atol */) { ... }
```
(where atol would be unsused)
