### ISSUE TITLE
Python install doesn't work

### ISSUE THREAD

**Issue by asood314** [stevengj/nlopt#237]
I am attempting to install nlopt with the python module on linux. I have followed the directions in the documentation for this package exactly. I don't see any error messages during the installation, but when I try to import it in python, I get an ImportError saying that the module doesn't exist. I have checked the directory that INSTALL_PYTHON_DIR is set to, and I don't see any nlopt module there.

**Comment by jschueller** [comment]
please provide all the logs, I cant do anything with this report

**Comment by asood314** [comment]
Attached is the output from:
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3
make
sudo make install
[cmake_ouput.txt](https://github.com/stevengj/nlopt/files/2646136/cmake_ouput.txt)
[make_output.txt](https://github.com/stevengj/nlopt/files/2646137/make_output.txt)
[sudo_make_install_output.txt](https://github.com/stevengj/nlopt/files/2646138/sudo_make_install_output.txt)

**Comment by jschueller** [comment]
you're missing python devel headers/libs
