### ISSUE TITLE
Installation Problem with MATLAB R2018b

### ISSUE THREAD

**Issue by sehyoun** [stevengj/nlopt#238]
With MATLAB 2018b, there seems to be some problem with cmake compilation for the mex function (e.g. http://cmake.3232098.n2.nabble.com/CMake-with-Matlab-R2018b-td7598661.html ). Therefore, if you follow the instructions in the documentation, one will get "mex gateway function is missing" error. I presume this will be fixed in the cmake side of things. However, I am posting a work around so that other people would not need to spend as much time search for the problem.

 Since the only part that fails is the compilation of one mex-file. One can just compile it directly.

1) Proceed as usual and install nlopt

2) Locate `src/nlopt_optimize-mex.c` file and compile it with mex directly. You cannot compile the function without linker flags, and one needs to run 

  `mex -v -largeArrayDims LINKLIBS="$LINKLIBS -I/usr/local/include -L/usr/local/lib -lnlopt -lm" nlopt_optimize-mex.c`

  For me this compiles and runs correctly. I believe `LINKLIBS` flag structure might be what changed from before.

3) Rename `nlopt_optimize-mex.mexa64` to `nlopt_optimize.mexa64` (File ending can differ based on the OS).

4) Place the file to the proper location. If you installed in the default location, it is `/usr/local/lib/matlab/nlopt_optimize.mexa64`

**Comment by jschueller** [comment]
I belive this should be fixed in latest cmake version:
https://gitlab.kitware.com/cmake/cmake/merge_requests/2407
what version are you using ?
feel free to reopen if not using latest

**Comment by sehyoun** [comment]
Oh, mine isn't the latest; I should have checked that first :)

Thank you.
