### ISSUE TITLE
Default build should compile using C++ if available

### ISSUE THREAD

**Issue by ericjster** [stevengj/nlopt#243]
Should we change the default build options to use C++ if available? Currently users face two problems: (1) by following the documentation the algorithms StoGO and AGS are not compiled; and (2) standard packages do not include them (including debian, pip, and conda packages).

The documentation says (https://nlopt.readthedocs.io/en/latest/NLopt_Installation/):
> If you configure with: 
>     cmake -DNLOPT_CXX=OFF ..
> however, it will disable algorithms implemented in C++ (StoGO and AGS algorithms).

As described in Issue #78, it works the opposite way and users must add an extra parameter to cmake to include the StoGO and AGS algorithms. The fix in Issue #78 worked for me:
>     cmake -DNLOPT_CXX=ON ..

**Comment by jschueller** [comment]
This is already the behavior of current master.
