### ISSUE TITLE
Does nlopt support warm start, and how to do it?

### ISSUE THREAD

**Issue by lesun90** [stevengj/nlopt#247]
Hi,

I read the document but did not see anywhere mention about the warm start.
Does nlopt support warm start, and how to do it?

Thank you

**Comment by marcoafo** [comment]
Well, I might be wrong, but usually I just set the input array to the starting point. It works for derivation-free models very well.

I'm not sure if that's your question. Just trying to help.

**Comment by lesun90** [comment]
Hi,
Thank for your reply, can you explain more on how to set the input array to start point?

Thank you

**Comment by marcoafo** [comment]
A simple example using COBYLA:

```
// let's say 3 dimensions for x
std::vector<double> x = {1,1,1};
nlopt::opt opt(nlopt::LN_COBYLA,3);

// whatever criteria you want
opt.set_ftol_abs(0.001);
opt.set_maxtime(120);

// minfunc is the evaluation function
opt.set_min_objective(minfunc,NULL);
double minf = f(3,&x[0],NULL,NULL);

// here we'll start the optimization in the (1,1,1) point, defined in the beginning
try
{		
    opt.optimize(x, minf);
}
catch(std::runtime_error&)   // you can add more catch's
{
    throw;   // or whatever to treat error
}

// now change the starting point to (999,999,999) and optimize again
x[0] = x[1] = x[2] = 999;
try
{		
    opt.optimize(x, minf);
}
catch(std::runtime_error&)   // you can add more catch's
{
    throw;   // or whatever to treat error
}
```
Very simple example, it's not that much smart, but that's a start.

**Comment by lesun90** [comment]
Thank you so much.
