### ISSUE TITLE
verbose output

### ISSUE THREAD

**Issue by manavbhatia** [stevengj/nlopt#248]
I am interested in gradient-based optimization. I have linked my C code to NLopt and am able to successfully call nlopt_optimize(). However, I don’t get any information printed to screen about the optimization iterations, etc. 

  Is there a flag I can set to get this information? I saw in #104 that one could put a print statement in the objective function call. However, isn't the objective function called multiple times before the conclusion of an iteration? 

  Also, is there a method that allows me to link a monitor to the optimizer such that I can perform specific tasks at the conclusion of each iteration? I would like to output the data on variable and constraint values.

**Comment by marcoafo** [comment]
I might be wrong and all, but I don't think it's quite necessary. You can add such controls and verbose output in your optimization binding function. At least, that's the way I do. Especially in gradient-based algorithms.

**Comment by stevengj** [comment]
Right, you just do whatever you want in your objective function.

The definition of "iteration" rather fuzzy, but if you only want to do something when the objective value improves you could easily track that yourself.
