### ISSUE TITLE
error finding octave/oct.h in MacOS homebrew

### ISSUE THREAD

**Issue by stevengj** [stevengj/nlopt#251]
Just ran into this with an up-to-date homebrew build:
```
[ 88%] Building CXX object src/octave/CMakeFiles/nlopt_optimize.dir/nlopt_optimize-oct.cc.o
/Users/stevenj/Code/nlopt/src/octave/nlopt_optimize-oct.cc:23:10: fatal error: 
      'octave/oct.h' file not found
#include <octave/oct.h>
         ^~~~~~~~~~~~~~
```
In particular, homebrew puts this file in `/usr/local/Cellar/octave/4.4.1_6/include/octave-4.4.1/octave/oct.h`. 

It seems like `cmake` should be able to get this information from the `mkoctfile` executable, which is in my PATH?  Failing that, maybe it should check for `octave/oct.h` and disable Octave support if that file can't be found.

**Comment by jschueller** [comment]
That should already be the current behavior. What's the value of OCTAVE_INCLUDE_DIRS ?

**Comment by stevengj** [comment]
It looks like my homebrew installation was broken, and cmake get confused if some files but not others are present.
