### ISSUE TITLE
Build instructions for Mingw64/Msys2 under Windows 10

### ISSUE THREAD

**Issue by jspst** [stevengj/nlopt#253]
Could you please include instructions on how to build 32bit and 64bit libraries of nlopt for Windows using Mingw64/Msys2 thanks.

**Comment by stevengj** [comment]
Don't you follow the standard build instructions (https://nlopt.readthedocs.io/en/latest/NLopt_Installation/) in that case, since mingw imitates a Unix system?

**Comment by jspst** [comment]
I tried the instructions but they don't work. During cmake I get lots of messages like
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake

At the end it says
-- Performing Test SUPPORTS_STDCXX11 - Success
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Could NOT find Guile (missing: GUILE_EXECUTABLE GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES)
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
-- Could NOT find Octave (missing: OCTAVE_EXECUTABLE OCTAVE_ROOT_DIR OCTAVE_LIBRARIES)
-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MX_LIBRARY) (found version "NOTFOUND")
-- Configuring done
When I run make it gives a lot of errors like
 CMakeFiles/nlopt.dir/src/algs/ags/local_optimizer.cc.obj:local_optimizer.cc:(.text+0x3c): undefined reference to `__cxa_allocate_exception'
CMakeFiles/nlopt.dir/src/algs/ags/local_optimizer.cc.obj:local_optimizer.cc:(.text+0x61): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long long&, unsigned long long)'

**Comment by stevengj** [comment]
If you google your `System is unknown to cmake` error, you'll find that people suggest doing:
```
cmake -G"MSYS Makefiles"
```

**Comment by jspst** [comment]
Sorry but your suggestion doesn't work and gives an error

CMake Error: Could not create named generator MSYS Makefiles

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Comment by jspst** [comment]
I found the problem. I have the generic cmake installed. I deleted it and installed the mingq version using 
pacman -S mingw-w64-x86_64-cmake and now the build works using
cmake -G"Unix Makefiles" ..

Perhaps you can update the instructions to make the version of cmake needed clear. Thanks for your help.

**Comment by stevengj** [comment]
Thanks, I added that to the docs.
