### ISSUE TITLE
DIRserial.c(29): error C2275: 'integer' : illegal use of this type as an expression

### ISSUE THREAD

**Issue by jschueller** [stevengj/nlopt#259]
it seems nlopt master does not build anymore with vs2010 since #230:
```src\algs\direct\DIRserial.c(29): error C2275: 'integer' : illegal use of this type as an expression```
maybe it's the void cast syntax ?

**Comment by stevengj** [comment]
Oh, the problem is that #230 put some of the void casts *before* declaration, which is valid C99 but not C89, and MSVC mostly only supports C89.

**Comment by stevengj** [comment]
We should probably test with `-std=c89`.

**Comment by jschueller** [comment]
maybe it's the integer typedef
