### ISSUE TITLE
Creating a .lib library of nlopt under Windows 10 

### ISSUE THREAD

**Issue by user41974** [stevengj/nlopt#263]
Version 2.5 came with instructions to make a .lib library and the Windows binary packages came with the file libnlopt-0.def to do this. The newer versions of the Windows binaries don't include the instructions or this file. Is it possible to include the def file for the new version of the library thanks.

**Comment by jschueller** [comment]
there's no need for this file anymore, symbols are automatically exported, just use cmake ant the .lib is automtically generated

**Comment by user41974** [comment]
Can you please give exact instructions of how to generate a .lib file with the new versions of nlopt. When I use cmake on Mingw/Mysy2 I can get .dll and .a libraries but not a .lib library.

**Comment by stevengj** [comment]
You can use the `.a` libraries the same way you would use `.lib`, I believe.

**Comment by user41974** [comment]
My fortran compiler needs a .lib library and I can't use the supplied Windows libraries because of this. That's why I suggested supplying the instructions  and files like in version 2.5. I assume it's easy to do (please tell me if it isn't) and gives users more options to use the library. Thanks.

**Comment by stevengj** [comment]
It's possible.  I'd have to modify the NLoptBuilder repository to generate the `.def` file.
