### ISSUE TITLE
Download .zip?

### ISSUE THREAD

**Issue by P-OHS** [stevengj/nlopt#266]
I can not find any .zip file to download in order to install nlopt on Windows 10 PC using the Matlab interface. Refering to the doc:
"On Windows, we provide a precompiled .zip file of the NLopt library, which includes a matlab directory."

**Comment by stevengj** [comment]
Sorry, those docs were out of date; I updated them.  There are still precompiled binaries available (https://nlopt.readthedocs.io/en/latest/NLopt_on_Windows/), but you have to download the matlab stuff separately.
