### ISSUE TITLE
Step monitor or "progress bar"

### ISSUE THREAD

**Issue by mokasin** [stevengj/nlopt#27]
Is it currently possible to obtain while the optimization is running? Something like current estimates, function value, etc.?

**Comment by bchretien** [comment]
Is there any plan to support some kind of callback function? It could be used for "monitoring", or provide a way to stop the optimization based on some user-defined criterion.

**Comment by stevengj** [comment]
NLopt already supports a callback function that allows for monitoring and provides a way to stop the optimization (via `nlopt_force_stop`) based on arbitrary criteria: the objective function.

**Comment by bchretien** [comment]
I was referring to something along the lines of [Ipopt's intermediate_callback](http://www.coin-or.org/Ipopt/documentation/node23.html#SECTION00053410000000000000), but it might be more difficult to have something similar that works for the wide range of algorithms supported by NLopt. FYI, this callback system makes it easy to have complex stopping criteria that do not just depend on the current value of the objective function.

Moreover, if you want to log the state of the solver at each iteration, the only way for now is to modify the cost function by adding a callback that will be triggered each time the function is called. However, when using a global algorithm with a local one (e.g. `AUGLAG` + `LD_MMA`), calls to the cost function will be for both the global algorithm and the local algorithm, making any monitoring difficult. Or am I missing something?
