### ISSUE TITLE
DIRECT takes impossibly long to reach xtol

### ISSUE THREAD

**Issue by jcottrell-ellex** [stevengj/nlopt#275]
Unless I'm mistaken, the XTOL stopping criterion for DIRECT (the cdirect version) can't be used when searching large multi-dimensional spaces, because it requires all hyper-rectangles everywhere to be divided down to below the x-tolerances before stopping. This will take an impossibly long time.

Wouldn't it make more sense to stop as soon as one (or a few) of the rectangles is small? This could be done by inverting some of the logic for the xtol_reached variable within the cdirect.c function divide_good_rects().

I can attach some test code here or work towards a pull request if that would be helpful.

Cheers,
Joel

**Comment by jcottrell-ellex** [comment]
Okay, so I've done some more reading and programming since I posted 2 days ago, and I can see that stopping as soon as you have one 'small' hyperrectangle isn't the right plan either, since it's necessary to cover a reasonable area with that sampling resolution before stopping. I have a new strategy which works in my situation, based on this strategy:
1. Run as normal until one rect is 'small'
2. Store the max Lipschitz value for the rects in the hull at this point in time (following the simpler defn of K̃ which just uses the diameter and distance from fmin). 
3. Continue in 'collapsing' mode, dividing rectangles as before, but skipping any which are too small (unnecessary precision) or exceed the stored max Lipschitz value (unlikely candidates). 
4. Return NLOPT_XTOL_REACHED once all hull Lipschitz values exceed the limit, except for that of the smallest rect, which will be zero.

This approach preserves the benefits of automatic balancing global and local searching until the algorithm gets down to the required tolerances, but switches over to local search at that point by limiting the Lipschitz constant.

**Comment by stevengj** [comment]
> the XTOL stopping criterion for DIRECT (the cdirect version) can't be used when searching large multi-dimensional spaces, because it requires all hyper-rectangles everywhere to be divided down to below the x-tolerances before stopping. This will take an impossibly long time.

This is correct.  DIRECT *guarantees* a global optimum to within xtol.  The time this requires increases exponentially with the number of parameters.  Welcome to the world of NP-complete problems.

As discussed [in the manual](https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/#termination-tests-for-global-optimization), in practice you can only terminate global optimization when you run out of patience.

**Comment by jcottrell-ellex** [comment]
Hi Steven, thanks for making this library available and for all the work you've put into it.
I'll keep playing with this, because I do feel like my optimiser should be able to self-terminate, but I understand that this will add complexity and risk and won't be generally applicable, so it probably doesn't belong in the library.

**Comment by stevengj** [comment]
It's not a question of complexity, it's a question of what you want "global optimization" to mean.

**Comment by jcottrell-ellex** [comment]
You're right, I probably meant 'specificity' not 'complexity', and I'm not after a purely global optimisation.
In my situation (real-time 4-para image registration), I need to use global optimisation because there are plenty of local minima traps, but once I'm down to XTOL precision I can be pretty confident that the global min isn't hidden far away between poorly-scoring values, and I don't have time to waste looking out there. Restricting K seems like a good way to lean towards the local-optim and then exit ASAP.

**Comment by stevengj** [comment]
> once I'm down to XTOL precision

What does this mean?

> maybe GN_MLSL is worth considering

In my experience, MLSL is by far the fastest global option for smooth objectives, especially with not too many local minima.  (Downside is that it requires a bit of tweaking to get good convergence criteria for the local search.)

**Comment by jcottrell-ellex** [comment]
By "down the XTOL precision" I'm referring to the time when some rectangles have been divided enough to have all dimensions below the specified xtol_abs values (small() returns 1). In my current way of thinking, this is the point that I want to switch over to 'collapsing mode' which prevents the algorithm from dividing rectangles that are either smaller than xtol, or larger but with very low probability of containing the optimum.
MLSL looks like it'll be more challenging to get my head around, but worth trying out. If it's well suited to my particular type of objective function and meets the xtol_abs stopping criteria within a useful timeframe, I might be wise to use that rather than a customised DIRECT-L.

**Comment by stevengj** [comment]
> prevents the algorithm from dividing rectangles that are either smaller than xtol, or larger but with very low probability of containing the optimum.

Preventing the algorithm from dividing rectangles smaller than a given diameter would be easy, but I don't know what you mean by larger rectangles with a "low probability of containing the optimum" … how do you assess this probability?   DIRECT already has a convex-hull heuristic that it uses to decide which of the larger rectangles to divide first.

**Comment by jcottrell-ellex** [comment]
For each rect on the hull, I calculate the minimum Lipschitz constant that would be required for the rectangle to contain the optimum: (f - minf)/diameter. If this value is above a certain limit, I consider the rectangle to be an unlikely candidate and I block its division rather than just deprioritise it.
Choosing the limit requires some tuning, but I'm currently using 2 * the max Lipschitz value that was seen on the hull when XTOL was reached. It needs to be low enough for a fast collapse, and high enough for a thorough-ish search during collapse.

**Comment by stevengj** [comment]
Certainly, if you have a bound on the Lipschitz then you can do much better in excluding rectangles.

> using `2 *` the max Lipschitz value that was seen on the hull when XTOL was reached

This loses the guarantee of convergence, no?

**Comment by jcottrell-ellex** [comment]
Yes there's definitely a risk there that I won't get the best possible answer, as there will be with any stopping criteria that terminates quickly. I don't know my exact time limitations yet, but I'm sure there'll be a balance to strike between risk and performance, and I may need to adjust that "2*" (assuming I don't leave this idea behind and switch to MLSL or something else).
