### ISSUE TITLE
mex nlopt-optimize.c wrong in matlab.

### ISSUE THREAD

**Issue by chouqin3** [stevengj/nlopt#277]
When I use interface in matlab, something wrong.
1. addpath('D:\Workspace\MATLABProjects\studyProjects\nloptGit\nloptinstall\include'); 
2. addpath('D:\Workspace\MATLABProjects\studyProjects\nloptGit\nloptinstall\lib');
3.  loadlibrary('nlopt.lib','nlopt.h')  % 'nlopt.lib', 
4. mex nlopt-optimize.c

error use loadlibrary
load library "\nlopttest\nlopt.lib"  error happened
\nlopttest\nlopt.lib is not effective win32 application
error bash (line 4)
loadlibrary('nlopt.lib','nlopt.h')

**Comment by chouqin3** [comment]
The problem has been solved. Beacause my matlab2016 is 64bit, the generated results are 32bit, matlab cannot link the wrapped package. So I use cmake compiled again, interpret is vs2017, x64(not default x86). Then I configured, generated, opened with vs2017, built, installed, finally, the file nlopt_optimize.mexw64 has been generated automatically. 
The test suit is passed successfully.

opt.algorithm = NLOPT_LD_MMA
opt.lower_bounds = [-inf, 0]
opt.min_objective = @myfunc
opt.fc = { (@(x) myconstraint(x,2,0)), (@(x) myconstraint(x,-1,1)) }
opt.fc_tol = [1e-8, 1e-8];
opt.xtol_rel = 1e-4

[xopt, fmin, retcode] = nlopt_optimize(opt, [1.234 5.678])
function [val, gradient] = myconstraint(x,a,b)
val = (a*x(1) + b)^3 - x(2);
if (nargout > 1)
    gradient = [3*a*(a*x(1) + b)^2, -1];
end
function [val, gradient] = myfunc(x)
    val = sqrt(x(2));
    if (nargout > 1)
        gradient = [0, 0.5 / val];
end

![image](https://user-images.githubusercontent.com/12481496/59759390-88ec2980-92c2-11e9-97ad-cc74e27d7e98.png)

**Comment by wojiaojiao** [comment]
mex nlopt-optimize.c
使用 'MinGW64 Compiler (C)' 编译。
错误使用 mex
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x4ba):
undefined reference to `nlopt_force_stop'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x5fa):
undefined reference to `nlopt_create'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x65c):
undefined reference to `nlopt_set_lower_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x699):
undefined reference to `nlopt_set_upper_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6bc):
undefined reference to `nlopt_set_stopval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6db):
undefined reference to `nlopt_set_ftol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6fa):
undefined reference to `nlopt_set_ftol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x719):
undefined reference to `nlopt_set_xtol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x749):
undefined reference to `nlopt_set_xtol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x783):
undefined reference to `nlopt_set_maxeval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7a2):
undefined reference to `nlopt_set_maxtime'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7c2):
undefined reference to `nlopt_set_population'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7e2):
undefined reference to `nlopt_set_vector_storage'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x81c):
undefined reference to `nlopt_set_initial_step'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x878):
undefined reference to `nlopt_set_local_optimizer'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x880):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8b2):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8b9):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8eb):
undefined reference to `nlopt_set_lower_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x90b):
undefined reference to `nlopt_set_upper_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x92e):
undefined reference to `nlopt_set_stopval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x94d):
undefined reference to `nlopt_set_ftol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x96c):
undefined reference to `nlopt_set_ftol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x98b):
undefined reference to `nlopt_set_xtol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9a3):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9aa):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9ce):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9d5):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9f5):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9fc): more
undefined references to `nlopt_destroy' follow
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xca4):
undefined reference to `nlopt_set_precond_min_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xdca):
undefined reference to `nlopt_add_inequality_constraint'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xef4):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xf24):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x106b):
undefined reference to `nlopt_add_equality_constraint'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1114):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1146):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x11b6):
undefined reference to `nlopt_optimize'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x11ff):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x12a8):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x12d4):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1301):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1331):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1372): more
undefined references to `nlopt_destroy' follow
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1481):
undefined reference to `nlopt_set_min_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1491):
undefined reference to `nlopt_set_precond_max_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x14b2):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x14d8):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x151b):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1531):
undefined reference to `nlopt_set_max_objective'
collect2.exe: error: ld returned 1 exit status

**Comment by wojiaojiao** [comment]
why????
mex nlopt-optimize.c
erro mex
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x4ba):
undefined reference to `nlopt_force_stop'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x5fa):
undefined reference to `nlopt_create'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x65c):
undefined reference to `nlopt_set_lower_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x699):
undefined reference to `nlopt_set_upper_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6bc):
undefined reference to `nlopt_set_stopval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6db):
undefined reference to `nlopt_set_ftol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x6fa):
undefined reference to `nlopt_set_ftol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x719):
undefined reference to `nlopt_set_xtol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x749):
undefined reference to `nlopt_set_xtol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x783):
undefined reference to `nlopt_set_maxeval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7a2):
undefined reference to `nlopt_set_maxtime'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7c2):
undefined reference to `nlopt_set_population'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x7e2):
undefined reference to `nlopt_set_vector_storage'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x81c):
undefined reference to `nlopt_set_initial_step'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x878):
undefined reference to `nlopt_set_local_optimizer'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x880):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8b2):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8b9):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x8eb):
undefined reference to `nlopt_set_lower_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x90b):
undefined reference to `nlopt_set_upper_bounds'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x92e):
undefined reference to `nlopt_set_stopval'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x94d):
undefined reference to `nlopt_set_ftol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x96c):
undefined reference to `nlopt_set_ftol_abs'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x98b):
undefined reference to `nlopt_set_xtol_rel'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9a3):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9aa):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9ce):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9d5):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9f5):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x9fc): more
undefined references to `nlopt_destroy' follow
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xca4):
undefined reference to `nlopt_set_precond_min_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xdca):
undefined reference to `nlopt_add_inequality_constraint'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xef4):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0xf24):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x106b):
undefined reference to `nlopt_add_equality_constraint'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1114):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1146):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x11b6):
undefined reference to `nlopt_optimize'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x11ff):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x12a8):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x12d4):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1301):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1331):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1372): more
undefined references to `nlopt_destroy' follow
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1481):
undefined reference to `nlopt_set_min_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1491):
undefined reference to `nlopt_set_precond_max_objective'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x14b2):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x14d8):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x151b):
undefined reference to `nlopt_destroy'
C:\Users\JJ\AppData\Local\Temp\mex_104182800052644_16480\nlopt-optimize.obj:nlopt-optimize.c:(.text+0x1531):
undefined reference to `nlopt_set_max_objective'
collect2.exe: error: ld returned 1 exit status
