### ISSUE TITLE
NLOpt does not issue  ROUNDOFF_LIMITED error in certain circumstances

### ISSUE THREAD

**Issue by pbeeson** [stevengj/nlopt#28]
I've noticed when using SLSQP, that if I do not give an xtol tolerance, but to give a max time, that NLOpt sometimes returns with the MAXTIME_REACHED but the returned X vector is all NaNs.   That is (at least in SLSQP), NLOpt does not notice that Nans/Infs has entered the solver's data structure and stop with a ROUNDOFF_LIMITED error.

**Comment by stevengj** [comment]
Do you have a simple test case that illustrates this?

**Comment by pbeeson** [comment]
Closing since I never followed up to provide a test case.
