### ISSUE TITLE
Disable Python Support in CMake

### ISSUE THREAD

**Issue by marcoafo** [stevengj/nlopt#281]
Not sure if this documented anywhere (I couldn't find in the documentation itself). But the scenario is that I have a Linux installation with Python. But I don't want to install nlopt in that. Since there are missing components in Python to enable nlopt, I don't want to use that, just C++.

But I can't get CMake through. It gives me the expected error:

```
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7")
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'sysconfig'
CMake Error at CMakeLists.txt:307 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at CMakeLists.txt:308 (file):
  file RELATIVE_PATH called with incorrect number of arguments
```

I think I could force PYTHON_EXECUTABLE:FILEPATH to like PYTHON_EXECUTABLE-NOTFOUND (I haven't tried). I'm just wondering how to make this Python optional.

I'm a newbie in CMake, so please forgive if the question has a simple answer.

Thanks.

**Comment by wxmerkt** [comment]
`cmake .. -DNLOPT_PYTHON=OFF`

**Comment by marcoafo** [comment]
Awesome, thanks!

Should it be documented, just in case?
