### ISSUE TITLE
Make error on Mac: No rule to make target `nlopt.f'

### ISSUE THREAD

**Issue by cdeil** [stevengj/nlopt#29]
On Mac OS X 10.10 with Macports I'm getting this error:
```
$ ./autogen.sh 
$ ./configure
$ make
...
make[2]: *** No rule to make target `nlopt.f', needed by `all'.  Stop.
```

Am I doing something wrong or is this a bug?

There's no `nlopt.f` file:
```
$ find . -name 'nlopt.*'
./api/nlopt.3
./api/nlopt.h
./nlopt.pc
./nlopt.pc.in
./swig/nlopt.i
./swig/nlopt.scm
./swig/nlopt.scm.in
```

Full log here: https://gist.github.com/cdeil/d6da8f8cb908fc292668

**Comment by stevengj** [comment]
Maybe a problem with your SWIG installation?   One problem is that no one seems to be maintaining the Guile bindings for SWIG, so they may be bit-rotting...

**Comment by stevengj** [comment]
I just tried with the Homebrew SWIG 3.0.2 on my Mac, and it works fine; I'm guessing there is a problem with your SWIG installation.  Closing this as the original problem (not configuring in `maintainer-mode` is a non-problem).

**Comment by stevengj** [comment]
(Note that, unless you are a developer, you should just download the release tarball.  This includes the swig-generated bindings, so you don't need a functioning SWIG.)
