### ISSUE TITLE
Is there any optimization lib for CUDA ?? 

### ISSUE THREAD

**Issue by ib198669** [stevengj/nlopt#291]
Does nlopt  support CUDA ? 
I want to know  if  there is any optimization lib for CUDA ??   Thank  you very much.

**Comment by jschueller** [comment]
no, nlopt does not make use of cuda apis, nor does it use any form of parallelism

**Comment by stevengj** [comment]
No plans for this at present.   (You can, of course, design your objective function to use CUDA or other forms of parallelism.)
