### ISSUE TITLE
 nullptr exception for SLSQP in C 

### ISSUE THREAD

**Issue by 75241601** [stevengj/nlopt#296]
i am using NLopt SLSQP to optimize the parameter for a state equation, in my case i used finite difference to calculate the gradient, but the compiler(visual studio) reported a nullptr exception at the argument for gradient. like that
![image](https://user-images.githubusercontent.com/54711038/65394132-fd36dd00-dd89-11e9-95a3-06dc6794ff7c.png)
i have tried this in MATLAB, it works fine, but the result of cost function between MATLAB and C is about 1e-4 different, maybe that caused the error report in C? In which situation will the compiler reported this nullptr error?

**Comment by stevengj** [comment]
You should only compute the gradient if `grad != NULL`, as documented in the manual — not every call to your function will request the gradient.
