### ISSUE TITLE
About the install in Ubuntu

### ISSUE THREAD

**Issue by chuanghou** [stevengj/nlopt#300]
I had done everything according the instructions from the website, the dynamic library has been generated, but There is not a auto-generated python-package that can be used in python. At the end, I found using pip can install sucessfully. So Is there a problem?

**Comment by jschueller** [comment]
what's the cmake output ?

**Comment by chuanghou** [comment]
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Failed
-- Looking for __cplusplus
-- Looking for __cplusplus - found
-- Performing Test SUPPORTS_STDCXX11
-- Performing Test SUPPORTS_STDCXX11 - Success
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.8") 
-- Found NumPy: version "1.17.3" /home/chuanghou/.local/lib/python3.6/site-packages/numpy/core/include
-- Could NOT find Guile (missing: GUILE_EXECUTABLE GUILE_ROOT_DIR GUILE_INCLUDE_DIRS GUILE_LIBRARIES) 
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) 
-- Could NOT find Octave (missing: OCTAVE_EXECUTABLE OCTAVE_ROOT_DIR OCTAVE_LIBRARIES) 
-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MX_LIBRARY) (found version "NOTFOUND")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chuanghou/Downloads/nlopt-2.6.1/build

**Comment by chuanghou** [comment]
It is like no error?

**Comment by jschueller** [comment]
you have to install swig

**Comment by chuanghou** [comment]
Thank you, I did not pay much much attention to the output information, and thinking it is just like Matlab, another language.
