### ISSUE TITLE
Selective compilation

### ISSUE THREAD

**Issue by e-aranda** [stevengj/nlopt#301]
I need to modify one specific algorithm in nlopt and I would like to know if it is possible to make a isolated compilation of only that algorithm.

**Comment by jschueller** [comment]
what do you mean, build nlopt with only one algorithm ?

**Comment by e-aranda** [comment]
Yes, if I only want to use one algorithm (and modified it), which files are necessary to compile?

**Comment by jschueller** [comment]
Well, it's easier to take the whole nlopt package, modify the one algorithm that you need than exclude all the other algorithms. See the README or the doc for detailled compilation instructions.
