### ISSUE TITLE
Build system always finds lowest python version on OSX

### ISSUE THREAD

**Issue by HDembinski** [stevengj/nlopt#303]
The cmake build of the Python binding has multiple issues (tested on OSX).

1) It find the lowest Python version on the system, while it should probably default to the highest version.
2) On my system it finds mismatching versions of Python interpreter and Python library (interpreter version 2.7.15, library version 2.7.10).

I understand that a lot of these issues are caused by the bad CMake FindPython module, nevertheless this should be fixed.

**Comment by jschueller** [comment]
should be fixed by 8c4f05c
