### ISSUE TITLE
Manual describes wrong API

### ISSUE THREAD

**Issue by ldeniau** [stevengj/nlopt#305]

**Comment by ldeniau** [comment]
The General Reference describes invalid signatures or non-existent functions, so far I found:
const char *nlopt_algorithm_to_string(nlopt_algorithm algorithm);
nlopt_algorithm nlopt_algorithm_from_string(const char *name);
nlopt_result nlopt_set_x_weights(nlopt_opt opt, const double *w);
nlopt_result nlopt_set_x_weights1(nlopt_opt opt, const double w);
nlopt_result nlopt_get_x_weights(const nlopt_opt opt, double *w);
nlopt_result nlopt_set_force_stop(nlopt_opt opt /*, int val*/)

**Comment by jschueller** [comment]
they do exist in master

**Comment by ldeniau** [comment]
Thanks, I switched to the git version.
