### ISSUE TITLE
nlopt package on PyPI does not work

### ISSUE THREAD

**Issue by HDembinski** [stevengj/nlopt#311]
There is a nlopt package on PyPI which seems to be maintained by other developers.
https://pypi.org/project/nlopt/

This package does not work on OSX and possibly other systems. The command `pip install nlopt` works just fine, but then `import nlopt` fails. It would be great to have an official Python package for nlopt that is unit tested.

**Comment by jschueller** [comment]
you can try nlopt from conda-forge

**Comment by HDembinski** [comment]
Yes, that's what I used in the end. But it would still be nice to have a working wheel that can be installed with pip on all major platforms.

**Comment by stevengj** [comment]
I agree that would be great if someone worked on the pip package.

**Comment by HDembinski** [comment]
@stevengj Do you have control over https://pypi.org/project/nlopt ? I would be willing to make this repository pip-installable, but it does not help much if you cannot update the package called `nlopt` on PyPI.

**Comment by jschueller** [comment]
you'll have to contact the currrent maintainers to give you access or open an issue on the pypi tracker if that does not work

**Comment by HDembinski** [comment]
So in other words, noone here has control over https://pypi.org/project/nlopt?

**Comment by jschueller** [comment]
I dont want to speak for steven, but no I dont think so.

**Comment by HDembinski** [comment]
In the meantime, I have contacted the maintainers of the package. We are still discussing, but maybe I can become maintainer of that package.

**Comment by stevengj** [comment]
No, I have no involvement with the pypi package.
