### ISSUE TITLE
SLSQP vs MMA

### ISSUE THREAD

**Issue by nicolapiccinelli** [stevengj/nlopt#315]
Hi,
I'm trying to use SLSQP to solve an MPC problem with Matlab, but without any luck. So I've tried to run the example that can be found here [NLopt_Tutorial](http://ab-initio.mit.edu/wiki/index.php?title=NLopt_Tutorial) and for SLSQP I'm obtaining very strange results. I put here a comparison of the outcome of the optimization:

**MMA**
nlopt_optimize eval 92: 0.544331
xopt = 0.3333    0.2963
cost = 0.5443
retcode = 4

**SLSQP**
nlopt_optimize eval 43: 0.544331
xopt = 0.5078    4.7625
cost = 2.1823
retcode = 3

The parameters used are the same for both the optimizers:

```
opt.ftol_rel = 1e-10
opt.ftol_abs = 1e-10
opt.xtol_rel = 1e-10
opt.maxeval = 400
```
It's normal that SLSQP isn't able to give the same optimal variables and cost even if it converges to the same evaluation value?

**Comment by jschueller** [comment]
what do you mean by "same evaluation value" ?

**Comment by nicolapiccinelli** [comment]
> what do you mean by "same evaluation value" ?

I mean the value print in the console when the verbose mode is activated, thery are both to 0.544331

**Comment by nicolapiccinelli** [comment]
> > what do you mean by "same evaluation value" ?
> 
> I mean the value print in the console when the verbose mode is activated, they are both to 0.544331

I've added also the print of the vector _x_ and at each iteration, it doesn't coincide with the value returned by **nlopt_optimize**.

**Comment by jschueller** [comment]
this typically happens with some algorithms that have an inner loop to compute some direction and only check the cost enhancement from the points evaluated in the main loop.

**Comment by nicolapiccinelli** [comment]
> yes, this typically happens with some algorithms that have an inner loop to compute some direction and only check the cost enhancement from the points evaluated in the main loop.

There is something strange, now I've started the optimization again and I'm able to get in the output the same values of MMA. I don't understand why, but, what I see in the code is that even if **ftol** is reached the main loop (do-while with the switch-case) makes a further slsqp iteration. Is this correct?

**Comment by jschueller** [comment]
I dont think there is a problem here:

```
import nlopt
import math as m


def myfunc(x, grad):
    if grad.size > 0:
        grad[0] = 0.0
        grad[1] = 0.5 / m.sqrt(x[1])
    return m.sqrt(x[1])


def myconstraint(x, grad, a, b):
    if grad.size > 0:
        grad[0] = 3 * a * (a*x[0] + b)**2
        grad[1] = -1.0
    return (a*x[0] + b)**3 - x[1]

for algo in [nlopt.LD_MMA, nlopt.LD_SLSQP]:
    opt = nlopt.opt(algo, 2)
    print(f"algo: {opt.get_algorithm_name()}")
    opt.set_lower_bounds([-float('inf'), 1e-6])
    opt.set_min_objective(myfunc)
    opt.add_inequality_constraint(lambda x, grad: myconstraint(x, grad, 2, 0), 1e-8)
    opt.add_inequality_constraint(lambda x, grad: myconstraint(x, grad, -1, 1), 1e-8)
    opt.set_xtol_rel(1e-10)
    opt.set_ftol_rel(1e-10)
    opt.set_ftol_abs(1e-10)
    opt.set_maxeval(400)
    x0 = [1.234, 5.678]
    x = opt.optimize(x0)
    minf = opt.last_optimum_value()
    print(f"optimum at {x}")
    print(f"minimum value: {minf:.7g}")
    print(f"result code: {opt.last_optimize_result()}")
    print(f"nevals: {opt.get_numevals()}")


algo: Method of Moving Asymptotes (MMA) (local, derivative)
optimum at [0.33333333 0.29629629]
minimum value: 0.544331
result code: 4
nevals: 52
algo: Sequential Quadratic Programming (SQP) (local, derivative)
optimum at [0.33333333 0.29629629]
minimum value: 0.5443311
result code: 3
nevals: 48
```
