### ISSUE TITLE
Default INSTALL_MEX_DIR not in Matlab's default path

### ISSUE THREAD

**Issue by Golho** [stevengj/nlopt#318]
Hi!

I'm on Ubuntu 18.04 and Matlab R2019b and currently, I've successfully built the repo. However, the installation directory for the MEX files and .m-files are not automatically detected by Matlab, as insinuated by the tutorial (https://nlopt.readthedocs.io/en/latest/NLopt_Installation/)

> The Matlab plugins (along with help files and other .m files) are installed into INSTALL_MEX_DIR. You can override the default by passing a INSTALL_MEX_DIR to cmake, via (in addition to other cmake arguments):

> cmake -DINSTALL_MEX_DIR=dir ..

> to install the Matlab plugins in directory dir. **In this case, however,** when you run Matlab you will either need to run in the dir directory or explicitly add dir to your Matlab path (see the Matlab path command).

The bold text must mean that if I use the NLOPT default option, I shouldn't need to bother with setting any path. In my case, they were installed to the location `/usr/local/lib/matlb`, which is not set to the Matlab path by default.

In the end, this was quite confusing, as I thought I did something wrong in the installation. But I guess I only had to add the directory to the Matlab path. Is this the intended way to go then, or did I actually do something wrong in the installation? In the case of the former, I think the documentation should be updated so it's clear that the MEX directory has to be added manually.

**Comment by jschueller** [comment]
The installation tree is always relative to cmake prefix (set by CMAKE_INSTALL_PREFIX which itself defaults to /usr/local).

**Comment by Golho** [comment]
That doesn't change my point, that the default directory for MEX files will not be a directory in Matlab's default path.

**Comment by jschueller** [comment]
Yes, as for the other language bindings.

**Comment by stevengj** [comment]
Sticking to the prefix is important. For one thing, other directories may not even be writable.  For another thing, a fundamental expectation is that `make install` should not touch any directories outside of the prefix that was specified.

As with all other languages, you need to set the path in that language to correspond to the nlopt installation prefix if you want it to find nlopt.

**Comment by Golho** [comment]
I believe you have misunderstood my issue. From your responses, I understand that this is just a documentation issue. 

The formulation above
> In this case, however, when you run Matlab you will either need to run in the dir directory or explicitly add dir to your Matlab path (see the Matlab path command).

is hence unnecessary and in my case confusing as you may always need to run in the dir directory or explicitly add dir to your Matlab path. I thought the documentation was well written and easy to follow, but this section just confused me.
