### ISSUE TITLE
Vectorized constraints

### ISSUE THREAD

**Issue by smartalecH** [stevengj/nlopt#320]
Feature request, similar to #310

It would be nice to be able to vectorize nonlinear constraints (specifically in python). Currently, the user must specify each constraint (and it's gradient) separately. For example:

https://github.com/stevengj/nlopt/blob/a10f7bc23d3aa77d7dde36f02001a97f79319ddc/test/t_python.py#L14-L24

This is inefficient for epigraph formulations that transform problems calling gradients for many constraints with one call. 

Any advice on how to enable this?

**Comment by stevengj** [comment]
Already supported in Python: https://nlopt.readthedocs.io/en/latest/NLopt_Python_Reference/#vector-valued-constraints
