### ISSUE TITLE
nlopt-2.6.2 introduced nlopt::result::NUM_RESULTS in C++ API

### ISSUE THREAD

**Issue by soonho-tri** [stevengj/nlopt#325]
Hi, I've found that nlopt-2.6.2 introduced a new value `nlopt::result::NUM_RESULTS` in enum `nlopt::result`. I  wonder if this is intended.

The following is an excerpt from nlopt.hpp file in its latest homebrew package (nlopt-2.6.2). It's located at `/usr/local/Cellar/nlopt/2.6.2/include/nlopt.hpp`.

```c++
  enum result {
    FAILURE = -1,         /* generic failure code */
    INVALID_ARGS = -2,
    OUT_OF_MEMORY = -3,
    ROUNDOFF_LIMITED = -4,
    FORCED_STOP = -5,
    SUCCESS = 1,          /* generic success code */
    STOPVAL_REACHED = 2,
    FTOL_REACHED = 3,
    XTOL_REACHED = 4,
    MAXEVAL_REACHED = 5,
    MAXTIME_REACHED = 6,
    NUM_RESULTS           /* not a result, just the number of them */
  };
```

**Comment by jschueller** [comment]
It's for internal use: "not a result, just the number of them"
