### ISSUE TITLE
Can this library be used by header-only method?

### ISSUE THREAD

**Issue by kilasuelika** [stevengj/nlopt#326]
I want to use it in my embedded chip. It will be very easy if I can just copy those header files without linking a lib.

**Comment by jschueller** [comment]
I'm afraid this is not possible: the code source contains are many .c files you need to compile.

**Comment by jschueller** [comment]
look for "header only optimization library", there are several available

**Comment by kilasuelika** [comment]
@jschueller
Thank you. I will try that.
