### ISSUE TITLE
check.derivatives giving false errors

### ISSUE THREAD

**Issue by kurt-o-sys** [stevengj/nlopt#328]
In order to optimize a 500-1500 dimensional problem, I'm trying out the nloptr package. Because I have this high dimensional problem, I'm trying to use gradient-based algorithms (as recommended https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/#gradient-based-versus-derivative-free-algorithms ).
It seems that, by adding a gradient-function, it takes more(!) time to compute the result than without the timings (using sqp). So I started to check if the derivates are right - I just wondered if that might have been the problem. Starting with the example given in the manual:

```
> # example with correct gradient
> f <- function( x, a ) {
+     return( sum( ( x - a )^2 ) )
+ }
> f_grad <- function( x, a ) {
+     return( 2*( x - a ) )
+ }
> nloptr::check.derivatives(.x=1:10, func=f, func_grad=f_grad, check_derivatives_print='none', a=runif(10))
Derivative checker results: 0 error(s) detected.
```
so all seems fine. However, increasing the number of dimensions:

```

> nloptr::check.derivatives(.x=1:100, func=f, func_grad=f_grad, check_derivatives_print='none', a=runif(100))
Derivative checker results: 3 error(s) detected.
> nloptr::check.derivatives(.x=1:1000, func=f, func_grad=f_grad, check_derivatives_print='none', a=runif(1000))
Derivative checker results: 72 error(s) detected.
> nloptr::check.derivatives(.x=1:10000, func=f, func_grad=f_grad, check_derivatives_print='none', a=runif(10000))
Derivative checker results: 2446 error(s) detected.
```
increases the number of errors a lot. (~3% for 100 dimensions, ~7% for 1000 dimensions, ~24% for 10000 dimensions)

So, my questions:
1. is this to be expected? If so, how to cope with these errors? Do they matter? (What's the use of the checker if I can't rely on it?)
2. can this be the reason that adding a gradient function takes more(!) time? UIsing sqp, with the functions above with a 1000 dimensions, it takes about 9-10 seconds to solve with a gradient function and about 7-8 seconds to solve without gradient function)

(I'm aware that I'm not adding any constraints right now! I'm just checking on a simple problem.)

**Comment by stevengj** [comment]
> What's the use of the checker if I can't rely on it?

The `check_derivatives` function doesn't come from NLopt — it's part of the R wrapper, which is by a separate author.   So I'm not sure what it does.

(I'm guessing that it checks against a finite-difference approximation, in which case maybe its step size or its tolerance need to be adjusted.)

> can this be the reason that adding a gradient function takes more(!) time?

If your gradient is inaccurate, that will definitely screw up convergence of a gradient-based algorithm.  (Though your gradient looks right to me.)

What algorithm are you using to solve the problem without a gradient?

**Comment by kurt-o-sys** [comment]
OK, sorry... that must than be an R thing. The check_derivatives function checks if the numerical calculation of the derivative matches the derivative function. I'm pretty sure that the derivative is right, but it still gives errors... Well, it's an R thing, so, let's just close this. I'm moving towards LBFGS anyway. Seems to be much faster, like a 100-1000x for >1000D spaces.

```
> f <- function( x, a ) {
+     return( sum( ( x - a )^2 ) )
+ }
> f_grad <- function( x, a ) {
+     return( 2*( x - a ) )
+ }
```

**Comment by stevengj** [comment]
Yes, SLSQP forms and solves dense DxD matrices for D variables, so it doesn't scale to large D.
