### ISSUE TITLE
Max inner iterations for MMA

### ISSUE THREAD

**Issue by smartalecH** [stevengj/nlopt#329]
It would be nice to pass a maximum number of "inner" iterations for the MMA algorithm.

This is especially useful for topology optimization problems.

**Comment by stevengj** [comment]
Would also be good to be able to specify a different tolerance for the dual optimizer.

**Comment by smartalecH** [comment]
Tolerance code:

https://github.com/stevengj/nlopt/blob/29e76303c564f892c04716f90ef1801a711f8880/src/api/optimize.c#L646

**Comment by stevengj** [comment]
Note that you can currently change this tolerance by setting the ftol_rel of the local optimizer.
