### ISSUE TITLE
Compatibility with Octave 4.0

### ISSUE THREAD

**Issue by rdmitry** [stevengj/nlopt#33]
NLopt doesn't work with Octave 4.0 due to Octave_map changes:

> ** The internal class <Octave_map> was deprecated in Octave 3.8 and has been removed from Octave 4.0.  Replacement classes are <octave_map> (struct array) or <octave_scalar_map> for a single structure.

**Comment by stevengj** [comment]
Thanks, good to know, shouldn't be too hard to update assuming they have a new class with similar semantics.

**Comment by stevengj** [comment]
Right now it's a bit hard for me to test, though, since Octave 4 isn't released... I guess you have to use the subversion head?

**Comment by rdmitry** [comment]
I use 4.0.0-RC3. In any case I'm not direct nlopt user, just checked software from openSUSE repository that requires Octave.

**Comment by peti** [comment]
We've updated to Octave 4.x in NixOS recently, and this update broke our nlopt builds: http://hydra.cryp.to/build/932458/nixlog/1/raw. Is there a simple fix for this issue, by any chance?

**Comment by stevengj** [comment]
The code has to be patched to use Octave's new data structure...

**Comment by peti** [comment]
Is there any progress fixing this issue?

**Comment by Mathnerd314** [comment]
I think this has been fixed by https://github.com/stevengj/nlopt/pull/42.

**Comment by peti** [comment]
It seems so. Now it would be nice to have a new release that contains this fix!

**Comment by peti** [comment]
In NixOS, we've worked around this issue now by simply disabling Octave support for nlopt: https://github.com/peti/nixpkgs/commit/fc8b9a45e6addfd0d7b815357eb2c6fa05b4f17f.
