### ISSUE TITLE
Error C4146 in rightzero32() of sobolseq.c (x64-uwp)

### ISSUE THREAD

**Issue by rickertm** [stevengj/nlopt#330]
When compiling NLopt with UWP, e.g., via the vcpkg x64-uwp triplet, the unary minus on an `uint32_t` type in [line 96](https://github.com/stevengj/nlopt/blob/41967f1981d82d8495c0b27151a126bc35ae0d96/src/util/sobolseq.c#L96) of file `sobolseq.c` creates an error (as opposed to a simple warning, c.f., #122). Replacing this with an alternative solution would enable building NLopt with UWP.
```
src\util\sobolseq.c(96,21): error C4146: unary minus operator applied to unsigned type, result still unsigned
```

**Comment by stevengj** [comment]
This seems wrong to me.   A unary minus applied to an unsigned integer is [well-defined according to both C and C++](https://stackoverflow.com/questions/8026694/c-unary-minus-operator-behavior-with-unsigned-operands).

**Comment by stevengj** [comment]
This is a compiler warning according to the [Microsoft docs](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4146?redirectedfrom=MSDN&view=vs-2019).   Have you used some compiler flag that turns warnings into errors?

**Comment by stevengj** [comment]
If you google this error message you see other similar discussions, e.g. I found this one illuminating: https://bitbucket.org/blaze-lib/blaze/issues/311/msvc-c4146-unary-minus-operator-applied-to

In particular, it comments that the [`/sdl` compiler flag](https://docs.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=vs-2019) is turning that warning into an error.

**Comment by stevengj** [comment]
One option is to use a `pragma` to suppress the warning on that line for MSVC.  In particular, you could add
```c
#ifdef _MSC_VER
#pragma warning( suppress : 4146 )
#endif
```
on the line *immediately preceding* line 96, and I think it should suppress the warning/error for that line.

**Comment by rickertm** [comment]
From what I could find, the `/sdl` flag indeed seems to be default when building with UWP. Here are the compiler flags when building with `x64-uwp`:
```
cl /c /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D NLOPT_DLL /D NLOPT_DLL_EXPORT /D "CMAKE_INTDIR=\"Debug\"" /D nlopt_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"nlopt.dir\Debug\\" /Fd"nlopt.dir\Debug\vc142.pdb" /Gd /TC /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue /utf-8 
```
From my tests, disabling this via suppress without `#ifdef` works:
```c
#pragma warning( suppress : 4146 )
    n = a * (n & (-n));         /* store in n to make sure mult. is 32 bits */
```
This however for some reason does not:
```c
#ifdef _MSC_VER
#pragma warning( suppress : 4146 )
#endif
    n = a * (n & (-n));         /* store in n to make sure mult. is 32 bits */
```
What finally worked on the other hand in my tests is this (replaced `suppress` with `disable` and added `push` and `pop`):
```c
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4146)
#endif
    n = a * (n & (-n));         /* store in n to make sure mult. is 32 bits */
#ifdef _MSC_VER
#pragma warning(pop)
#endif
```

**Comment by stevengj** [comment]
Apparently `#pragma warning  suppress` has to be on the line immediately before, and it counts whitespace lines.  So you would need to do:
```
#ifdef _MSC_VER
#pragma warning( suppress : 4146 )
    n = a * (n & (-n)); 
#else
    n = a * (n & (-n)); 
#endif
```

**Comment by stevengj** [comment]
Thanks, I committed this workaround.

**Comment by rickertm** [comment]
Great, thank you for including this.
