### ISSUE TITLE
Get generation number for population based algorithms in C++

### ISSUE THREAD

**Issue by philippb94** [stevengj/nlopt#331]
Hi,

i was wondering if it is possible to get the current generation number of an individual for population based algorithms like ISRES or ESCH in C++. I need to know to which generation an individual belongs to, when the objective function is called. 

This cannot be calculated afterwards with the initial population size for all algorithms.

Thank you!

**Comment by stevengj** [comment]
In general we don't expose algorithm-specific internals like this, since the concept of a "generation" doesn't makes sense for most algorithms.

**Comment by philippb94** [comment]
Thanks for your reply.
