### ISSUE TITLE
Add Levenberg-Marquardt implementation.

### ISSUE THREAD

**Issue by ethanhs** [stevengj/nlopt#337]
[Levenberg-Marquardt](https://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm) is a very popular non-linear local optimization algorithm used in many applications. I have found it can give better results than L-BFGS for the same budget for the problem I have. Here is an example of an implementation (MIT licensed): https://gist.github.com/rbabich/3539146. This can also be found in minpack as lmder/lmdiff.

**Comment by stevengj** [comment]
It's not a general nonlinear-optimization algorithm — it's specifically for least-squares problems.  So it doesn't really fit into nlopt.  There are plenty of other libraries that provide it, however.
