### ISSUE TITLE
segmentfault 

### ISSUE THREAD

**Issue by liuliucen** [stevengj/nlopt#338]
Hi,
For some reasons, I try to use nlopt to solve a quadratic programming problem。
the form of my problem is  like :
            min       x'Qx
subject to   Aie*x<0
                   Ae*x=0
in which Q is a constant matrix, while Aie and  Ae represent inequality matrix and equality matrix.
1.
First, i use **COBYLA** because it is derivative-free and only COBYLA currently supports arbitrary nonlinear inequality and equality constraints.But the result of  it is really wrong compared with the result of  qpOASES (i am sure qpOASES's result is right).
Do I have to give an initial value of x when using COBYLA?
2.
Then , i try SLSQP , I seriously calculated the gradient of objective function and equality inequality constraint ，but the "**segment fault** " appears when running the code.
In the first round of calculation, every element in x is equal to 0,
but in the second round , the gradient and cost are both **-nan.**

 I really want to know what the problem is. Can someone help me？

[main.txt](https://github.com/stevengj/nlopt/files/4797136/main.txt)

**Comment by jschueller** [comment]
please post a minimal non-working example code

**Comment by liuliucen** [comment]
Hi,
The main.txt is a minimal code

**Comment by liuliucen** [comment]
> please post a minimal non-working example code

can you help me see what the problem is ?
Thank you very much

**Comment by jschueller** [comment]
it segfaults because a nlopt exception is thrown, you just have to catch it (terminate called after throwing an instance of 'nlopt::roundoff_limited'
  what():  nlopt roundoff-limited)
