### ISSUE TITLE
bobyqa stability

### ISSUE THREAD

**Issue by vhaguiar** [stevengj/nlopt#342]
bobyqa gives different solutions when given the same initial values, bobyqa algorithm is deterministic, so It should give same solutions if given same initial values

**Comment by vhaguiar** [comment]
it seems that rhobeg, rhoend are in a nonstandard way, this may cause instability in the stopping rule

**Comment by jschueller** [comment]
please provide a testcase, more infos about os, distro, compiler, libc etc so we can replicate the issue

**Comment by jschueller** [comment]
sorry we cannot do anything without more info
