### ISSUE TITLE
Replace swig by pybind11 for Python bindings

### ISSUE THREAD

**Issue by HDembinski** [stevengj/nlopt#343]
I understand that swig works perfectly fine to generate Python bindings with the added advantage that it also generates Guilde bindings, but for Python, there is actually a better alternative for wrapping C/C++ code, [pybind11](https://pybind11.readthedocs.io/en/stable/).

pybind11 is a header-only C++ library which can be included as a submodule or installed with pip in docker images. This makes building python wheels on many platforms much easier than with swig, which one has to install manually.

Context: I am working on a repo that generates binary wheels for the nlopt python module on all platforms here https://github.com/HDembinski/nlopt-python/tree/overhaul
Installing swig on the various docker images that are required to build binary wheels for all platforms is the last major issue.

**Comment by jschueller** [comment]
swig is not that hard to install, and compiles pretty quickly, we're not rewriting the bindings because of that
