### ISSUE TITLE
Trouble compiling nlopt on Windows

### ISSUE THREAD

**Issue by HDembinski** [stevengj/nlopt#344]
My nlopt Python wheel builder is almost done, it already works on Linux and MacOS, but I am getting a compile error on Windows. I am not a Windows expert, so help would be very much apreciated. It looks like a build issue in nlopt, not a problem on my end.

You can see the issue here:
https://github.com/HDembinski/nlopt-python/runs/839066503?check_suite_focus=true#step:5:483
There are lots of linker errors to symbols which look like they should come from the Python standard lib. If you scroll up you can see that the configuration step works fine, the Python standard lib seems to be correctly found and also everything else looks good.

I am building nlopt as a static library, which works well on Linux and MacOS. Could this cause trouble on Windows?

Edit: the actual nlopt library is compiled into a static library, the Python module is a dynamic library, of course.

**Comment by jschueller** [comment]
```
C:\cibw\python\pythonx86.3.6.8\tools\libs\python36.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
```

**Comment by HDembinski** [comment]
Why are you closing? The nlopt build system seems to pick up the wrong Python library.

**Comment by jschueller** [comment]
it cannot know the arch of the lib, you have to set it the path to the right lib yourself

**Comment by HDembinski** [comment]
The lib must be the same that the Python interpreter is linked to. One can query the Python interpreter for the right lib.
