### ISSUE TITLE
Creating nlopt-org organisation as a place for nlopt and nlopt-python 

### ISSUE THREAD

**Issue by HDembinski** [stevengj/nlopt#345]
I became co-owner of the nlopt Python package on PyPI and I finished automating the building of Python packages for nlopt for all platforms. More help would have been nice, and I hope we can work better together in the future.

To that end, I suggest to create a common place for all nlopt repositories: an nlopt organisation on github.

Steps:
- Create an nlopt orgination on Github, e.g. "nlopt-project" or "nlopt-org"
- Transfer this repo to that organisation
- Transfer [nlopt-python](https://github.com/hdembinski/nlopt-python) to that org

The pybind11 organisation is a good example. It hosts several pybind11 related repositories.

Thanks.

Edit: You can see the nlopt Python packages here: https://pypi.org/project/nlopt/#files. Through my recent work we can now automatically produce these packages for Linux, MacOS, and Windows for Python 3.6 to 3.8.

**Comment by jschueller** [comment]
nlopt-python is probably not a good name, maybe nlopt-wheels ?

a word on your wheels:
- i686 is probably useless these days (or win32)
- what are abi tag with "none" in the middle ? like cp37-none-manylinux1_x86_64, did you mean cp37-cp37m-manylinux1_x86_64 ?
- is useless (for nlopt) to use manylinux2010 if you can provide manylinux1 (best stick with manylinux1 as manylinux2010 is not handled by pip<20 or something)
-

**Comment by HDembinski** [comment]
@DanielBok Do you have thoughts on this?

**Comment by ogencoglu** [comment]
So is nlopt `pip` installable now?

**Comment by jschueller** [comment]
yes, seems @DanielBok got the lead on this
