### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by cpterry** [stevengj/nlopt#348]
Hi, 

If given a thread-safe objective function, can `nlopt_optimize` be run on multiple threads, optimizing separate problems?

If not, what are the limitations and could these please be added to the documentation?

**Comment by jschueller** [comment]
I think this was not tested.
Looking for global variables you'll see that for example subplex.c has many static variables that may prevent thread-safety.

**Comment by cpterry** [comment]
> Can you provide a minimal testcase that shows the issue ?

There's no issue right now. I just wanted to know if nlopt is intended to work multi-threaded. Looking at the code I've only found static variables to do with randomness and timing, and they are thread local. So I guess it should work and be a non-issue for deterministic methods with no maximum time specified.

The question was prompted by some inconsistent results but I've been able to duplicate that in a single-threaded case. I have not been able to duplicate it in a minimal test case yet.

**Comment by stevengj** [comment]
For the most part I tried to make things re-entrant and hence thread-safe, but I would be more cautious about some of the code converted from Fortran.

If you find any code that is not re-entrant, please file an issue.  (The goal is to support not only thread safety but also nested optimization.)

**Comment by cpterry** [comment]
I have not found any non re-entrancy issues. My inconsistent results (with MMA) do not appear to be a re-entrancy problem so I'll close this issue. Thanks!
