### ISSUE TITLE
Minor: Broken link for CVX

### ISSUE THREAD

**Issue by simpsonchristo** [stevengj/nlopt#349]
The link for the CVX optimization package points to a broken link. "if you have a provably convex problem, you may be better off with a different software package, such as the [CVX](http://www.stanford.edu/~boyd/cvx/) package from Stanford." See https://github.com/stevengj/nlopt/blob/master/doc/docs/NLopt_Introduction.md under "Global versus local optimization"

MATLAB CVX: http://cvxr.com/cvx/
CVX is now available via Python too: https://www.cvxpy.org/

**Comment by stevengj** [comment]
Fixed, thanks.  (Feel free to submit a documentation PR for this sort of thing by clicking the "edit" link on github.)

**Comment by simpsonchristo** [comment]
Will do in the future. Thanks.
