### ISSUE TITLE
Fully working with cmake on master

### ISSUE THREAD

**Issue by ocommowi** [stevengj/nlopt#35]
Hello

We would like to compile nlopt with cmake (for usage in several of our projects). We therefore used the CMakeLists present in the folder. What happened however is that the Makefile generation from cmake on the master fails because nlopt.hpp is not generated.

Looking deeper into the code and makefiles, here is my understanding. It seems to me that this file is generated by autogen or configure. It basically is made from nlopt-in.hpp by adding enums by regexps from nlopt.h . 

This is not easy to replicate in cmake and moreover not natively compatible with windows. I have made a workaround this morning by adding to my copy of the repo an nlopt.hpp file correctly generated and everything then go on smoothly.

I would be interested in adding this file to the master so that cmake is fully working without requiring external tools. Of course, I understand that this would mean maintaining this file whenever you add a new optimization algorithm or return code, but this doesn't sound too much of a constraint to me (not happening very often I would guess). If you are interested, I could quickly create a pull request for you to see what would change.

Thanks in advance

**Comment by stevengj** [comment]
If you want to work on master, you should use configure/autoconf etc.   The CMakeLists is only for use with the release tarball, precisely because it relies on generated files as you noted.   I'm unwilling to check generated code into master.

Why do you need to use git `master`, as opposed to just using the release tarball?

**Comment by ocommowi** [comment]
Well, to make a long story short, we wanted to include nlopt as an external dependency in a cmake superproject (medinria, also on github) that is built using native compilers of mac, linux and windows. This superproject can fetch a git repo or a tarball and compile it automatically. The problem of the release tarballs is that they do not include the cmakelists and config.cmake.h.in so I cannot use them directly as they are. This is why I turned to the git master where these files are directly included... but not working since the generated files are not there (and can only be generated with make but using tools - egrep, sed, ... - that are not native on windows).

So that's why I was asking this, thinking that in fact automatic generation of headers can still be done even if pre-generated files are there. But I totally understand your point of view as well. One other solution would be to include the cmakelists and config.cmake.h.in inside the release tarballs, which would mean I won't need the git repo itself.

**Comment by stevengj** [comment]
I can definitely include the cmake files in the release tarball.
