### ISSUE TITLE
How to install matlab interface in win10 with matlab2019b

### ISSUE THREAD

**Issue by HongweiSunny** [stevengj/nlopt#352]
Hi, I want to use NLopt in win10/Matlab2019b, But I do not know how to install it in this environment.
Could u please give some notes? Thx!

**Comment by jschueller** [comment]
see the doc:
https://nlopt.readthedocs.io/en/latest/NLopt_Installation
https://nlopt.readthedocs.io/en/latest/NLopt_Installation/#matlab
