### ISSUE TITLE
'Multiple definition' linker errors while installing nlopt

### ISSUE THREAD

**Issue by mokenyi** [stevengj/nlopt#353]
Hi,

I followed the installation [instructions](https://nlopt.readthedocs.io/en/latest/NLopt_Installation/) in the documentation. After calling

cmake -DCMAKE_INSTALL_PREFIX="$(readlink -f  ~/.local)" -DCMAKE_CXX_FLAGS='-fPIC' ..

I get no errors here (output in [nlopt_cmake_output.txt](https://github.com/stevengj/nlopt/files/5143419/nlopt_cmake_output.txt)), but when I call

make VERBOSE=1

I get errors which I've attached the output in [nlopt_make_output.txt](https://github.com/stevengj/nlopt/files/5143421/nlopt_make_output.txt). The linker detects two implementations of getopt() and related variables: one in nlopt-getopt.c and the other in libc.a. Could you help me stop this from happening?

Thanks,
Matt

**Comment by jschueller** [comment]
could you try this patch ? https://github.com/stevengj/nlopt/pull/354

**Comment by mokenyi** [comment]
Thanks for responding so quickly! The patch did fix the problem.

**Comment by stevengj** [comment]
Let's keep this open until a patch ismerged.
