### ISSUE TITLE
Builtin rb_tree_* symbols collide with libc on NetBSD

### ISSUE THREAD

**Issue by stixpjr** [stevengj/nlopt#360]
I ran into this issue with a strange crash while porting PrusaSlicer to NetBSD, as reported [here](http://mail-index.netbsd.org/tech-pkg/2020/10/11/msg023893.html).

NetBSD libc exports a rb_tree [implementation](https://man.netbsd.org/rbtree.3) whose weak symbols collide with those in nlopt.
As detailed in that email thread, I worked around the issue by prefixing nlopt's "rb_tree" symbols with "nlopt_", and I'll work on getting that patch into pkgsrc for the current version.

Is there any chance of permanently prefixing nlopt's built-in rb_tree symbols?

**Comment by jschueller** [comment]
absolutely, can you submit the patch ?
