### ISSUE TITLE
Using nlopt on a RISC-V system?

### ISSUE THREAD

**Issue by JohnPatMcGinley** [stevengj/nlopt#363]
Hello, 

I just wanted to quickly ask: Is there is any compatibility between nlopt and RISC-V architecture?

I was trying to compile a project using a RISC-V compiler and got the following error: 
![image](https://user-images.githubusercontent.com/36456455/98184633-b3428500-1ebf-11eb-8eb1-1e3802b394d3.png)

I am using this cross-compiler: https://github.com/riscv/riscv-gnu-toolchain 

In addition: Is nlopt dependent on older versions of Python (pre-Python3) or older releases of Numpy?

Thanks

**Comment by stevengj** [comment]
NLopt can compile on any system with a C compiler.  It doesn't need Python at all, unless you are building the Python bindings.

Don't post screenshots of errors — post the text.

Cross-compiling with cmake is a bit of a pain, however…

**Comment by jschueller** [comment]
debian builds nlopt on riscv, so it should be fine,
I'm not aware of problems related to numpy versions
cross-compilation using cmake is very powerful, you need a toolchain file, see:
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html
