### ISSUE TITLE
ABI broken between versions 2.6.2 and 2.7.0

### ISSUE THREAD

**Issue by rlaboiss** [stevengj/nlopt#366]
In version 2.7.0, all the functions `rb_tree_*` have been renamed to `nlopt_rb_tree_*` in `src/util/redblack.c`. Since these functions are publicly available, the ABI breaks between libnlopt.so.0.10.0 (v2.6.2) and libnlplot.so.0.11.0 (v2.7.0). The easiest way of fixing this problem is to change `CMakeLists.txt` like this:

```
set(SO_MAJOR 1)
set(SO_MINOR 0)
set(SO_PATCH 0)
``` 

Please consider doing this in the next release of NLopt.

That said…

If I understand correctly, the `nlopt_rb_tree_*` functions are meant only for internal use and are not really part of the NLopt API (at least, I cannot find references to them in the documentation). If I am not wrong, and in order to avoid such problems in the future, I would recommend to hide those functions (and perhaps others) from the public API. For instance, this could be done with function attributes like this:
```
void __attribute__ ((visibility ("hidden")))
nlopt_rb_tree_init(rb_tree * t, rb_compare compare)
{
…
```
or with visibility pragmas:
```
#pragma GCC visibility push(hidden)
nlopt_rb_tree_init(rb_tree * t, rb_compare compare)
{
…
#pragma GCC visibility pop
```

**Comment by rlaboiss** [comment]
In hindsight, I think that this issue may be a non-issue. If we believe that the downstream applications using NLopt so not use the “internal” functions of the API (like `rb_tree_*`), then there is no need for bumping the SOVERSION.  Indeed, this kind of transition is quite painful for the distributions like Debian, since all the packages that depend on libnlopt0 will have to be ported to libnlopt1.  If we can avoid this, it will be preferable.  At any rate this amounts to the confidence that you have on the donwstream authors not having using the “internal” functions.  I think that this is a reasonable assumption, but I would like to hear your opinion.

For your information, here are the reverse dependencies on libnlopt0 currently in Debian:
```
$ apt-cache rdepends libnlopt0
libnlopt0
Reverse Depends:
  libnlopt-dev
  libnlopt0-dbgsym
  libnlopt-dev
  spades
  shogun-cmdline-static
  libshogun16
  r-cran-nloptr
  phyx
  python-nlopt
  octave-nlopt
  libnlopt-guile0
  libnlopt-dev
  mia-tools
  libmia-2.4-4
  libkido-optimizer-nlopt0.1
  bolt-lmm
  libopenturns0.12
  spades
  prusa-slicer
  r-cran-nloptr
  phyx
  bolt-lmm
  mia-tools
  libmia-2.4-4
  libdart6-optimizer-nlopt
```

**Comment by stevengj** [comment]
Yes, the version numbers only indicate compatibility for the public API, not internal functions.

**Comment by rlaboiss** [comment]
Ok, thanks.  Two questions:

0. Is there a list of the functions in the public API?
0. It would be good to implement the hiding of the internal functions, as I proposed above.  Should I prepare un pull request for that?

**Comment by rlaboiss** [comment]
>  Is there a list of the functions in the public API?

Answering to my own question:

```
grep ^NLOPT_EXTERN ./src/api/nlopt.h
```

**Comment by stevengj** [comment]
There are an awful lot of internal functions. Rather than mark them as hidden one by one, I think you’d want to mark them as all hidden by default.

**Comment by rlaboiss** [comment]
This [patch](https://github.com/stevengj/nlopt/files/5580011/visibility.patch.txt) implements a simple-minded solution along these lines.  It adds `-fvisibility=hidden` to `CMakeLists.txt` and overrides the compile-time visibility setting in both `src/api/nlopt.h` and `src/api/f77api.c` using the construct:

```c
#pragma GCC visibility push(default)
[…]
#pragma GCC visibility pop
```
There is a substantial reduction in the number of exported symbols [before](https://github.com/stevengj/nlopt/files/5580015/libnlopt.so.symbols.orig.txt) and [after](https://github.com/stevengj/nlopt/files/5580018/libnlopt.so.symbols.new.txt) the patch is applied. Those files were obtained with the following command:

```sh
nm -D libnlopt.so.0.11.0 | grep " T " > libnlopt.so.symbols
```

**Comment by stevengj** [comment]
Note that you should only add `-fvisibility=hidden` if the compiler is gcc or gcc-compatible.

**Comment by rlaboiss** [comment]
Sure. Also, the `#pragma` directive only works with GCC. This is why I called the solution provided by my patch “simple-minded”.
