### ISSUE TITLE
Example using additional data and 3 constrained parameters

### ISSUE THREAD

**Issue by connormeaton** [stevengj/nlopt#374]
I am trying to use nlopt c++ to optimize the following equation:

```
sqrt(
                pow(abs(xF - (cos(theta)*xM) - (sin(theta)*yM) + tx), 2) + \
                pow(abs(yF - (sin(theta)*xM) + (cos(theta)*yM) + ty), 2)
```
I want to supply `xM, yM ,xF, and yF` as data input into the function (they are coordinates). I want to solve for `theta, tx, and ty`, all of which are constrained.

The theta constraint is 0.1 to 2pi.
The tx and ty constraints are 0.1 to 980.

I want to return the theta, tx, and ty values that minimize my function.

There is very little documentation on how to do this. Has anyone solved a similar problem?

**Comment by stevengj** [comment]
Your constraints are just bound constraints: https://nlopt.readthedocs.io/en/latest/NLopt_C-plus-plus_Reference/#bound-constraints

You can pass additional data in through the `void*` parameter of the objective function (https://nlopt.readthedocs.io/en/latest/NLopt_C-plus-plus_Reference/#objective-function), e.g. by casting this to/from a `double*` to an array of your additional data.   Having a data pointer like this is a standard technique for callback functions in C.
