### ISSUE TITLE
NLOPT - Windows - Invalid MEX-file: The specified module could not be found

### ISSUE THREAD

**Issue by JustinasMark** [stevengj/nlopt#377]
I've been trying to use NLOPT on Windows. However, I got stuck with a problem regarding the MEX file.

I have implemented the following steps:
1. Downloaded MSYS64 from www.msys2.org
2. Successfully implemented 7 steps instructed in the website www.msys2.org
3. Successfully ran two following commands from the website https://nlopt.readthedocs.io/en/latest/NLopt_on_Windows/#nlopt-on-windows_1    : 
          pacman -S mingw-w64-x86_64-cmake
          cmake -G"MSYS Makefiles" . && make
4. All the ".m" files got stored in   \nlopt\src\octave
5. I copied nlopt.h, libnlopt.dll and libnlopt.dll.a and pasted those files into \nlopt\src\octave
6. I copied t_matlab.m, myfunc.m and myconstraint.m and pasted them into \nlopt\src\octave
7. In MatLab I did   cd \nlopt\src\octave
8. I ran the following command line:
          mex nlopt_optimize.c libnlopt.dll.a
I got the following output in the command window:
          >> mex nlopt_optimize.c libnlopt.dll.a
          Building with 'MinGW64 Compiler (C)'.
          MEX completed successfully.
9. Then I ran t_matlab.m  . However, I got the following error:
          Invalid MEX-file 'C:\Users\Dell\nlopt\src\octave\nlopt_optimize.mexw64': The specified module could not be
found.

Does anyone know what could have gone wrong? Did I miss any of the steps I should have implemented? Or otherwise did I make any mistakes?

I would be very grateful for any help you could provide. Note also that I am not very good with IT, so there could be some simple mistake that I could have done.

Kind regards,
Justinas

**Comment by jschueller** [comment]
does the mex binary mentioned exist ?

**Comment by JuliusSustarevas** [comment]
I was helping Justinas out so I can elaborate. 

Yes the mex was created successfully. "The specified module could not be
found." as per matlab forums means that mex is failing to find dependencies. See here: https://uk.mathworks.com/matlabcentral/answers/92040-why-do-i-receive-a-specified-module-could-not-be-found-error-while-running-a-mex-file-created-from

Using the dependency walker as per matlab forums, we saw a million dependencies missing, tho ofc that is usually nonsense. however we did also see the dependencies missing that are mentioned in this issue : https://github.com/stevengj/nlopt/issues/359  and here https://github.com/stevengj/nlopt/issues/359

Dependency walker shows that the mex file is missing libstdc++-6.dll and libgcc_s_seh-1.dll but many others too. 

... 

To expand on  the issue. We are using 
win10, Matlab 2020b

1. we tried the methodology in your website. Downloaded precompiled ddls. Put everything into one folder. Built the mex successfully. But alas mex did not work. We got "The specified module could not be
found."
2. we then downloaded msys and setup mingw etc. as Justinas points out above and rebuilt the whole nlopt.  Again put dll and dll.a files into one folder etc. Built mex successfully and got the same error. 


We have tried VS C++19 and mingw compilers on matlab. 

----

My hunch is saying that we need those compiler support libraries as per the issues i mentioned. But i would image we need the import libraries to link them not just dlls

**Comment by JustinasMark** [comment]
I have solved my problem. I was missing the following files:

libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll

You can download them from here:
[nlopt_matlab.zip](https://github.com/stevengj/nlopt/files/5947547/nlopt_matlab.zip)

Those files were automatically downloaded in my friend's computer when he downloaded MinGW via MatLab's option "Add-Ons". However, even though I had also downloaded MinGW via MatLab's interface, those three files were not downloaded into my computer due to unknown reasons. 

Having pasted those files into my MatLab working directory, "t_matlab.m" works.
