### ISSUE TITLE
Hybrid Direct with local searches

### ISSUE THREAD

**Issue by dschmitz89** [stevengj/nlopt#388]
The source code contains a [file](https://github.com/stevengj/nlopt/blob/master/src/algs/cdirect/hybrid.c) which enables to provide a local minimizer to DIRECT. Is this available in the public API already? 
The documentation does not state anything about this possibility. I tried setting a local optimizer in the Python binding but it did not seem to have any effect. 

Combining DIRECT with local search is for example used in the very popular [Multilevel Coordinate Search algorithm](https://en.wikipedia.org/wiki/MCS_algorithm), so I think this would be a very useful extension for Nlopt. MCS won a recent (unpublished) [benchmark](http://infinity77.net/go_2021/thebenchmarks.html#results-aggregated-high-level-results) of global optimizers. A hybrid DIRECT in Nlopt could be even more powerful as a great number of local minimizers would be available.

**Comment by stevengj** [comment]
direct/hybrid.c was an experiment, but I never really got it working to my satisfaction so I never exported it.

I'm definitely a fan of combining global and local search, as in MLSL and StoGO.

**Comment by dschmitz89** [comment]
Thanks for your answer and sorry that hybrid Direct did not work out in your tests.
Is it possible to set the local minimizer in StoGO though? From documentation it seems like it is fixed.

**Comment by stevengj** [comment]
Yes, StoGO has a fixed (BFGS) local minimizer.

**Comment by dschmitz89** [comment]
Ok, thanks for the clarification. This issue can be closed from my side then.
