### ISSUE TITLE
major iteration limit

### ISSUE THREAD

**Issue by jpritikin** [stevengj/nlopt#39]
Not all algorithms have major iterations, but it would be nice if there was a way to set a major iteration limit.

**Comment by lgpage** [comment]
I had started adding this (in the API at least) when I attempted to add a callback function to the API and MMA algorithms.
See Issue #37

**Comment by stevengj** [comment]
Why would a major iteration limit (for those algorithms where it makes sense) be useful?

**Comment by jpritikin** [comment]
Different algorithms use a different number of evaluations per major iteration. It can be useful to limit the number of major iterations because major iterations are a more comparable measure of progress between algorithms. I'm not saying that it is a huge important feature, but it is not useless either.

**Comment by stevengj** [comment]
I'm skeptical... if you want to compare algorithms, in the end isn't all you care about the number of function evaluations (or the error plotted vs. # evaluations)?

**Comment by jpritikin** [comment]
> if you want to compare algorithms, in the end isn't all you care about the number of function evaluations (or the error plotted vs. # evaluations)?

Hm .. Maybe a better example is a tool we use to estimate profile likelihood confidence intervals. SLSQP usually works great, but just in case, I'll probably limit it to 150 major iterations. This limit is easier to express in major iterations because it doesn't depend on the number of parameters. A limit in the number of evaluations would have to take into account the evaluations used for a finite difference approximation of the gradient.

**Comment by stevengj** [comment]
@jpritikin, I still don't understand that.  NLopt doesn't know that you are doing a finite-difference approximation inside the gradient.  It only counts the objective evaluations that it calls explicitly.

**Comment by jpritikin** [comment]
@stevengj Ah right, so nlopt_stop_evals is not really counting evaluations. It's really counting major + minor iterations (for SLSQP).

Alright, I'm not sure how useful it is to count major iterations, but code is out there in the wild that puts a limit on major iterations. So I'd like to support it just for backward compatibility.

**Comment by microprediction** [comment]
newbie question: how to set the number of function evals?

**Comment by stevengj** [comment]
@microprediction, using `nlopt_set_maxeval`.
