### ISSUE TITLE
MLSL and StoGo stopping criteria

### ISSUE THREAD

**Issue by dschmitz89** [stevengj/nlopt#391]
From Nlopt's Python API it is not possible to stop MLSL and StoGo via the x_rel, x_abs, f_rel and f_abs tolerances. In all my experiments they always run until maxeval is reached, even for simple examples. I think that both are potentially powerful optimizers but for real life problems they are difficult to use with this limitation. Is there a way around this by maybe setting a ForcedStop? 

After quickly checking the source code, one suggestion to implement a simple stopping criterion for MLSL would be the total number of local searches. This is for example also done in scipy's basinhopping implementation. 

StoGo seems to be an external library with its own stopping criteria. Is it maybe possible to set "more practical" tolerances in there?

**Comment by inikishev** [comment]
same issue, it won't stop, and raising errors doesn't stop it either

**Comment by jschueller** [comment]
indeed, these local criteria dont make sense for this global algorithm, only maxeval, maxtime or stopval criteria,
i have metntionned this in the doc: 1d41a6520 (see also #187)

**Comment by dschmitz89** [comment]
I think having a default that runs in an infinite loop is not a user friendly choice. What about defaulting to `maxeval=1000 * dimensions` as a fallback if the user does not provide a stopping criterion?

**Comment by jschueller** [comment]
other algorithms do not have any stopping criterion enabled either by default so that would not be consistent

**Comment by dschmitz89** [comment]
> other algorithms do not have any stopping criterion enabled either by default so that would not be consistent, unless we set a default maxeval for all algorithms, but then it would mean changing the current behavior

Valid point. Should I open a dedicated issue for a broader discussion with more visibility?

**Comment by jschueller** [comment]
we can ask what @stevengj thinks
