### ISSUE TITLE
how to fix the step size for derivative free algo?

### ISSUE THREAD

**Issue by liwei46** [stevengj/nlopt#395]
Hello, 

I am trying to use a derivative free algo like LN_COBYLA in python and C++, I wish to fix the steo size (for example 1.0). As I only wants to search the integer values in the range. 
How can I do this?
I already tried "opt.set_initial_step" in python. 

Thanks.

**Comment by stevengj** [comment]
These algorithms don't work with fixed step sizes, and in general you can't use a continuous optimization package like NLopt to perform integer optimization.
