### ISSUE TITLE
Ubuntu nlopt error: ModuleNotFoundError: No module named 'nlopt'

### ISSUE THREAD

**Issue by IsayamaYoomi** [stevengj/nlopt#396]
Hello everyone,
I am having issues related to cmake described in title. I did exactly as the documentation suggested, and at the last step where I need to set the full path to the python executable I typed ` cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8 .. -DNLOPT_MATLAB=OFF -DNLOPT_GUILE=OFF -DNLOPT_OCTAVE=OFF` Everything looks fine, but I can not locate the `nlopt.py` file and when I try to import nlopt it gives me the error `ModuleNotFoundError: No module named 'nlopt'`. I am using 64-bit Ubuntu 20.04.2 LTS and cmake version is 3.16.3. Any idea of how to fix this?

```
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3.8 .. -DNLOPT_MATLAB=OFF -DNLOPT_GUILE=OFF -DNLOPT_OCTAVE=OFF
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NLopt version 2.7.0
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for time.h
-- Looking for time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for syscall
-- Looking for syscall - found
-- Looking for isinf
-- Looking for isinf - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for time
-- Looking for time - found
-- Looking for copysign
-- Looking for copysign - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Looking for fpclassify
-- Looking for fpclassify - TRUE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Success
-- Performing Test HAVE_THREAD_LOCAL_STORAGE
-- Performing Test HAVE_THREAD_LOCAL_STORAGE - Failed
-- Looking for __cplusplus
-- Looking for __cplusplus - found
-- Performing Test SUPPORTS_STDCXX11
-- Performing Test SUPPORTS_STDCXX11 - Success
-- Found PythonInterp: /usr/local/bin/python3.8 (found version "3.8.10") 
-- Found PythonLibs: /usr/local/lib/libpython3.8.a (found suitable exact version "3.8.10") 
-- Found NumPy: /home/isayama/.local/lib/python3.8/site-packages/numpy/core/include (found version "1.20.3") 
-- Found SWIG: /usr/bin/swig4.0 (found version "4.0.1") 
-- Performing Test UNDEFINED_SYMBOLS_ALLOWED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/isayama/Documents/nlopt/build
```
```
python3.8
Python 3.8.10 (default, May 12 2021, 23:33:23) 
[GCC 9.3.1 20200430 (for GNAT Community 2020 20200429)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nlopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nlopt'
>>> 
```

**Comment by finartist** [comment]
Did you find a solution to this? I also struggled with this and could only make it work by manually copying the files to the correct folder. For me, the files ended up in `/usr/local/lib/python3/dist-packages` but should have been in `/usr/local/lib/python3.8/dist-packages`.

I also had to manually specify not only `PYTHON_EXECUTABLE` but also `PYTHON_LIBRARY` and `PYTHON_INCLUDE_DIR`. Cmake kept finding my Anaconda installation despite specifying the system Python executable. That would have been fine if it would have worked in Anaconda but it did neither work there nor for my system Python. Seems like having the installation process cannot handle multiple different Python installations.

**Comment by jschueller** [comment]
you have to set the correct CMAKE_INSTALL_PREFIX

**Comment by finartist** [comment]
But that moves everything to another directory (i.e. also the non-Python stuff). Because the Cmake documentation says "this directory is prepended onto all install directories". I'd rather like to have the library as usual in `/usr/local` and the Python specific stuff in the Anaconda or `/usr/local/lib/python3.x` directory.  

Reading through the Cmake file, I found that `INSTALL_PYTHON_DIR` is an option that can be set. Would be nice to include that into the documentation along with common default paths. Also this part:
> Note also that the -DCMAKE_INSTALL_PREFIX flag will change the location where the Python plugins are installed, so you may need to change the Python module search path via the PYTHONPATH environment variable.

would be nice in the Python section of the installation directions.

It's also very counter intuitive that even without setting CMAKE_INSTALL_PREFIX the library won't be at the correct location. `print(sysconfig.get_python_lib(plat_specific=True, prefix='${CMAKE_INSTALL_PREFIX}'))` will give the wrong location even with the default prefix path because `/usr/local/lib/python3` is not in the search path for system Python and it will give a completely wrong location for Anaconda.

**Comment by jschueller** [comment]
for anaconda you have to set CMAKE_INSTALL_PREFIX to the anaconda prefix
