### ISSUE TITLE
using the additional f_data as matrix in myfunc [Fortran]

### ISSUE THREAD

**Issue by ChaoyiZhu93** [stevengj/nlopt#398]
I was trying to use f_data as a (3,10) matrix for my objective function myfunc. it does not seem to work because it only seems to take scalar value. I am wondering if there is any trick for using f_data as a matrix.

**Comment by LTuohaha** [comment]
Hi Zhu! I am so confused about what exactly f_data is? Does it play an vital role in the nlopt? I will be very grateful for your answer。
