### ISSUE TITLE
Minimize based on extra data

### ISSUE THREAD

**Issue by Deloryz** [stevengj/nlopt#399]
My objective function has extra data, such as data->a, and myfunc returns (a-xxx), which xxx is a expression related to parameters, and no constraints are set. 

When I run the code , the minimum value returned is data->a and the parameter is 0.

I want to know if there is any problem here, or how to get the minimum value and parameters that make (a-xxx) tend to 0, thank you very much!

**Comment by stevengj** [comment]
I don't really understand your question.   You can easily pass extra data/parameters to the objective function (via the `void*` parameter in C, or using a closure in Python etcetera).

If it's not giving the minimum you expect, you may have a bug in your objective function.

Note that NLopt *minimizes* functions.  If you want to make a function equal to zero, you may instead want to use a root-finding library.

**Comment by Deloryz** [comment]
Thanks for your reply. I know how to use extra data to my function. I don't know if there is a root-finding library that can solve my function.

There is my code

`#include<iostream>
#include<cmath>
#include"nlopt.h"

using namespace std;

int i=0;
typedef struct{
    double a, b;
}myfunc_data;

double func(int n, const double *x, double *grad, void *f_data)
{
    i++;
    cout << "i= " << i << endl;
    myfunc_data *d = (myfunc_data*)f_data;
    double a =d->a, b =d->b;
	
    return  a - (x[0] + x[1]*tanh(x[2]*b) + x[3]*( pow(abs(b),x[4]) * ((b>0) - (b<0))) );
}


int main()
{

    double f_min;

    myfunc_data data[1] = {50,1};
    double x[5]; //= {0.1,10,50,10,1};

    double lb[5] = {0,0,0,0,0};
    double rb[5] = {100,100,1000,100,10};

     double res = nlopt_minimize(NLOPT_LN_COBYLA,5,func,&data[0],lb,rb,x,&f_min,-10000000000,0,0,0,0,0,0);
     cout << x[0] << endl << x[1] << endl << x[2] << endl << x[3] << endl << x[4] << endl << f_min << endl;
     cout << res << endl;

}`

This finally returns
x[0] = 7.06539e-270
x[1] = 7.06584e-270
x[2] = 7.09406e-270
x[3] = 4.85907e-270
x[4] = 7.09405e-270
f_min = 50
res = -4

I want to know if it is correct to use NLopt to solve the minimum value of my objective function.

**Comment by stevengj** [comment]
It looks like your function is monotonic in all five variables, so the minimum will be at the lower bounds (0,0,0,0,0), and that is what it is finding.

NLopt finds minimums, if that's what you need.

**Comment by Deloryz** [comment]
I used to initialize x, but the minimum value and parameters obtained are not what I want. It seems that the minimum value of the objective function has nothing to do with the extra parameters `a` I passed in

**Comment by Deloryz** [comment]
I used to initialize `x`, but the minimum value and parameters obtained are not what I want. It seems that the minimum value of `x` in the objective function has nothing to do with the extra parameters I passed in.

**Comment by Deloryz** [comment]
I used to initialize x, but the minimum value and parameters obtained are not what I want. It seems that the minimum value of x in the objective function has nothing to do with the extra parameters `a` I passed in.

**Comment by Deloryz** [comment]
I used to initialize `x`, but the minimum value and parameters obtained are not what I want. It seems that the minimum value of `x` in the objective function has nothing to do with the extra parameters `a` I passed in.

**Comment by Deloryz** [comment]
I used to initialize `x`, but the minimum value and parameters obtained are not what I want. It seems that the minimum value of `x` in the objective function has nothing to do with the extra data `a` I passed in.

**Comment by stevengj** [comment]
NLopt is doing what you ask, but perhaps not what you want.   I'm guessing your function doesn't mean what you think it means.
