### ISSUE TITLE
Python Cobyla different behaviour than the R version

### ISSUE THREAD

**Issue by florysf** [stevengj/nlopt#402]
Hello team

We are using the COBYLA algorithm for minimizing a function with around 12 inequality constraints. We have implemented the algorithm in both R and Python but the target is to use the Python version.
However we encountered a weird behaviour: the R algorithm works fine and finds an optimum value that satisfies the constraints, but the Python one not. 
We have checked and compared all the parameters but they seem to be the same. Unless we are missing something in the configuration. Even the outputs of the algorithm from R and Python are the same for the first 10-12 steps. How ever afterwards the Python version enters kind of a loop where the same parameters and optimum is found for 3 steps. Then the parameters  are all set to NaN. And if we increase the number of steps this behaviour kind of repeats several times and the last optimum value doesn't satisfy the inequality constraints.

Any ideas what could cause this difference in the behaviour? Is there something in the bindings that could be set differently?

Thanks a lot and best regards,
Flori

**Comment by jschueller** [comment]
looks like it could be similar to #560 where you do not provide exactly the same output or gradient values (printing all the decimals may help)
