### ISSUE TITLE
Suspicious use of long double in slsqp.c

### ISSUE THREAD

**Issue by AaronWebster** [stevengj/nlopt#413]
I want to get rid of the `long double` type in `slsqp.c` for compatibility with ARM.  If its use is warranted, I can replace it with a Kahan sum.  Otherwise, I'd demote it to a `double`.

**Comment by stevengj** [comment]
`double` should be fine.

**Comment by AaronWebster** [comment]
https://github.com/stevengj/nlopt/pull/414

**Comment by stevengj** [comment]
Closed by #414.
