### ISSUE TITLE
RuntimeError: nlopt failure

### ISSUE THREAD

**Issue by rezah** [stevengj/nlopt#416]
I get an error: RuntimeError: nlopt failure

File "/home/reza/anaconda3/envs/qdev/lib/python3.9/site-packages/nlopt/nlopt.py", line 334, in optimize
    return _nlopt.opt_optimize(self, *args)
RuntimeError: nlopt failure

even by setting opt.set_maxtime(-1)

**Comment by jschueller** [comment]
please provide a minimal script

**Comment by rezah** [comment]
Well, I can not provide a minimal example, as it is used with other packages. It works well in so many cases (so grad is calculated right) but only in few cases do I face this problem.
