### ISSUE TITLE
Error when using bounds

### ISSUE THREAD

**Issue by IgnacioEG** [stevengj/nlopt#425]
I am solving an optimization problem of the form:

```
opt = nlopt.opt(nlopt.LD_MMA, len(x))
opt.set_lower_bounds([10**(-25/20)]*len(x))
opt.set_upper_bounds([1]*len(x))
opt.set_min_objective(lambda fx,grad: myfunc(fx,grad,o_d))
opt.set_ftol_abs(1e-2)
opt.set_maxtime(300)
fx = opt.optimize(fx)
```

I solved it many times changing parameters and it works fine. However, from time to time I get the following error:
...

  _File "C:\ProgramData\Anaconda19\lib\site-packages\nlopt.py", line 333, in optimize
    return _nlopt.opt_optimize(self, *args)

ValueError: bounds 5 fail 0.0562341 <= 0.0562341 <= 1_

Any idea how to solve this?

**Comment by stevengj** [comment]
Soundds like you have a roundoff error that is causing your initial guess to be slightly less than your lower bound (i.e. `0.0562341 <= 0.0562341 <= 1` *looks* like it is satisfied, but only because it is printing just 6 significant digits).
