### ISSUE TITLE
Which optimizers are deterministic?

### ISSUE THREAD

**Issue by Happy-to-see-you** [stevengj/nlopt#426]
Are any of the optimizers deterministic, as in, will always produce the same output if the initialization is the same?

**Comment by stevengj** [comment]
Most of them are deterministic, except for CRS, MLSL, ISRES, StoGO, AGS, and ESCH.  (And the LDS variant of MLSL is deterministic.)

And even the stochastic algorithms can be made determistic if you use `nlopt_srand` to set the seed.
