### ISSUE TITLE
Using nlopt without gradient information

### ISSUE THREAD

**Issue by AnkitAggarwalPEC** [stevengj/nlopt#427]
double myfunc(unsigned n, const double *x, double *grad, void *my_func_data){

    if (grad) {
        grad[0] = 0.0;
        grad[1] = 0.5 / sqrt(x[1]);
    }
    return sqrt(x[1]);
}

The function to optimize is defined as above. How can we optimize the same function without providing the grad as obtaining gradient information is tough for some functions.

Thanks,
Ankit Aggarwal

**Comment by stevengj** [comment]
You call one of the derivative-free algorithms.  In that case the `grad` argument will always be `NULL` and you need not compute it.
