### ISSUE TITLE
403 error on MIT server

### ISSUE THREAD

**Issue by roryk** [stevengj/nlopt#43]
http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz looks down, any chance of a mirror?

**Comment by stevengj** [comment]
It should be back up, thanks for pinging me.

**Comment by roryk** [comment]
Thanks!

**Comment by jslee02** [comment]
You could try to download nlopt from [this repo](https://github.com/stevengj/nlopt/archive/nlopt-2.4.2.tar.gz) in the meantime.

**Comment by stevengj** [comment]
@jslee02, no you shouldn't use the github-generated tarballs; you need a tarball generated by `make dist` that includes the generated files (which is not checked into git).  Using the github-generated tarballs requires you to have additional build tools installed, much like `git clone`.

**Comment by jslee02** [comment]
I see. I found the details from the [README.md](https://github.com/stevengj/nlopt/blob/master/README.md) as well, thanks.

I could build nlopt from the github-generated tarball without any additional install of build tools. I feel like I have all the build tools installed. :)

**Comment by stevengj** [comment]
Things like `automake` are common on GNU/Linux systems, but are not necessarily present on all Unix-like systems.  (e.g. they are not there by default on OS X.)
