### ISSUE TITLE
Offset out of bounds in SLSQP algorithm

### ISSUE THREAD

**Issue by astamm** [stevengj/nlopt#431]
I am the new maintainer of the R wrapper `nloptr` that makes `NLopt` available to the R community.
On some OS configuration, the compiler throws the following warning:
```
Found the following significant warnings:
     C:/Users/USERVehIAdHXco/nloptr.Rcheck/00_pkg_src/nloptr/src/nlopt-src/src/algs/slsqp/slsqp.c:959:12: warning: '__builtin_memset' offset [8, 15] is out of the bounds [0, 8] of object 'xnorm' with type 'double' [-Warray-bounds]
   See 'C:/Users/USERVehIAdHXco/nloptr.Rcheck/00install.out' for details.
```
Could this be an actual problem in the current code of the SLSQP algorithm?

**Comment by jschueller** [comment]
it sounds like a legit alignment issue

**Comment by astamm** [comment]
After reading protocolbuffers/protobuf#7140, it seems that
1. This warning is legit indeed and related to a version of the GCC compiler.
2. There is a workaround that pertains to silencing the warning by adding to the main `CMakeLists.txt` something along this line `set_source_files_properties(${NLOPT_SOURCES} PROPERTIES COMPILE_FLAGS -Wno-array-bounds)`, which I did and it indeed silence the warning.

Could you investigate the SLSQP code to fix the warning please? In particular, line 959 of file `algs/slsqp/slsqp.c` seems to trigger the warning. In effect, there seems to indeed be an out-of-bound issue here.

**Comment by jschueller** [comment]
it seems like a false positive after all as I dont get it with newer gcc 14
