### ISSUE TITLE
Inequality constraint tolerance not satisfied but successful status returned 

### ISSUE THREAD

**Issue by filippopalomba** [stevengj/nlopt#432]
I'm trying to solve an optimization problem with an equality and an inequality constraint. The command `nloptr()` finds an optimum, however when I try to evaluate the constraints of the problem at the proposed optimum, I finf that the inequality constraint is not satisfied, meaning that the residual is higher than the allowed tolerance for inequality constraints. Here's a github link to a repository where you can find an R workspace and an .R file that replicate the issue.

https://github.com/filippopalomba/nloptr-issue

**Comment by samuelkim314** [comment]
Is it possibly related to this issue (https://github.com/stevengj/nlopt/issues/57) where it returns the last evaluated point rather than the optimum point?

**Comment by jschueller** [comment]
#57 was fixed, so closing this too
