### ISSUE TITLE
Array of inequality constraints

### ISSUE THREAD

**Issue by NicolasRiel** [stevengj/nlopt#435]
Hi !
I am using NLopt in C and I need to add different combinations of inequality constraints (using CCSAQ algortihm) depending on an external condition.
How can I set an array of inequality constraints in NLopt? Can we use a pointer to an array of inequality constraints?
I remember seeing that a long time ago, but don't find it again :(

Thanks!

**Comment by JacintaDFerreira** [comment]
Hello! Did you find a way to do this? I'm trying to do the same

**Comment by NicolasRiel** [comment]
Hi! Yes I did actually, here you can find an example:

https://github.com/ComputationalThermodynamics/MAGEMin/blob/main/src/NLopt_opt_function.c

Tell me if this is not clear!

Cheers
