### ISSUE TITLE
Python Installation instructions fail on MacOS 12.2 Monterey

### ISSUE THREAD

**Issue by danielrgreen** [stevengj/nlopt#436]
On MacOS 12.2 (Monterey), the installation instructions fail. In particular, CMake fails to locate the correct version of the Python libraries.

    username@computer build % cmake -DPYTHON_EXECUTABLE=`which python3` ..
    -- NLopt version 2.7.1
    -- Could NOT find PythonLibs: Found unsuitable version "2.7.18", but required is exact version "3.10.2" (found /Library/Frameworks/Python.framework/Versions/3.10/lib)

CMake is only able to find the outdated Python 2.x libraries (which are unfortunately still the standard Python version on MacOS, for whatever reason), but not the modern Python 3.x libraries. There does not appear to be any option to supply the correct Python library directory directly to CMake.

**Comment by jschueller** [comment]
there is, see PYTHON_LIBRARY and PYTHON_INCLUDE_DIR
