### ISSUE TITLE
Run several optimizations in parallel

### ISSUE THREAD

**Issue by jmcastro2109** [stevengj/nlopt#438]
Hi, I am writing here because I could not find this anywhere on the documentation (or in google FWIW)

Assume that I have to maximize `N` independent functions which are the "same" but there are some constant parameters (from the perspective of the optimization) that vary across each of the `n \in N` subproblems.

What would be the proper way of running each independent optimization in parallel? In other words, I would be calling NLopt in parallel to solve each subproblem `n`. What is the correct way of doing this? Since parameters are changing would I need to create `n` optimization routines?

**Comment by wumy27** [comment]
Is this issue done? Can you share how you achieved it?
