### ISSUE TITLE
Issues Compiling for M1 Max MacBook

### ISSUE THREAD

**Issue by Powerofthesun** [stevengj/nlopt#439]
I am unable to compile Nlopt for my M1 Max MacBook. Given the issues I'm having, I'm wondering if there's an issue with NLopt an and these new cpus? Here's what I get when I try to make from source and when I use Conan, respectively.
`Undefined symbols for architecture arm64:
  "_mexCallMATLABWithObject", referenced from:
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexErrMsgTxt", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexPrintf", referenced from:
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexWarnMsgTxt", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
  "_mxCalloc", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxCreateDoubleMatrix_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxDestroyArray", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxFree", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetCell_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetField_730", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetM", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetN", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetPr", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetScalar", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
  "_mxGetString_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsCell", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsChar", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsComplex", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxIsDouble", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxIsFunctionHandle", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsNaN", referenced from:
      _user_function in nlopt_optimize-mex.c.o
  "_mxIsNumeric", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
  "_mxIsStruct", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o`

`Undefined symbols for architecture arm64:
  "_nlopt_create", referenced from:
      nlopt::opt::opt(nlopt::algorithm, unsigned int) in inverse_kinematics.cpp.o
  "_nlopt_destroy", referenced from:
      nlopt::opt::~opt() in inverse_kinematics.cpp.o
  "_nlopt_get_dimension", referenced from:
      nlopt::opt::set_upper_bounds(std::__1::vector<double, std::__1::allocator<double> > const&) in inverse_kinematics.cpp.o
      nlopt::opt::set_lower_bounds(std::__1::vector<double, std::__1::allocator<double> > const&) in inverse_kinematics.cpp.o
      nlopt::opt::alloc_tmp() in inverse_kinematics.cpp.o
      nlopt::opt::optimize(std::__1::vector<double, std::__1::allocator<double> >&, double&) in inverse_kinematics.cpp.o
  "_nlopt_get_errmsg", referenced from:
      nlopt::opt::get_errmsg() const in inverse_kinematics.cpp.o
  "_nlopt_optimize", referenced from:
      nlopt::opt::optimize(std::__1::vector<double, std::__1::allocator<double> >&, double&) in inverse_kinematics.cpp.o
  "_nlopt_set_force_stop", referenced from:
      nlopt::opt::set_force_stop(int) in inverse_kinematics.cpp.o
  "_nlopt_set_lower_bounds", referenced from:
      nlopt::opt::set_lower_bounds(std::__1::vector<double, std::__1::allocator<double> > const&) in inverse_kinematics.cpp.o
  "_nlopt_set_maxeval", referenced from:
      nlopt::opt::set_maxeval(int) in inverse_kinematics.cpp.o
  "_nlopt_set_min_objective", referenced from:
      nlopt::opt::set_min_objective(double (*)(std::__1::vector<double, std::__1::allocator<double> > const&, std::__1::vector<double, std::__1::allocator<double> >&, void*), void*) in inverse_kinematics.cpp.o
  "_nlopt_set_munge", referenced from:
      nlopt::opt::opt(nlopt::algorithm, unsigned int) in inverse_kinematics.cpp.o
  "_nlopt_set_stopval", referenced from:
      nlopt::opt::set_stopval(double) in inverse_kinematics.cpp.o
  "_nlopt_set_upper_bounds", referenced from:
      nlopt::opt::set_upper_bounds(std::__1::vector<double, std::__1::allocator<double> > const&) in inverse_kinematics.cpp.o
ld: symbol(s) not found for architecture arm64`

**Comment by rhysics** [comment]
I want to follow up on this I also cant install nlopt on M1 Mac

**Comment by jschueller** [comment]
nlopt compiles fine on M1, try disabling the matlab bindings, I doubt its available on conan other than for x86
for pip ask https://github.com/DanielBok/nlopt-python

**Comment by ethans-carl** [comment]
I'm getting a similar set of error messages when trying to compile on an M1 MacBook (with the end goal of using nlopt within Matlab), using cmake.

I'm new to compiling, so if I'm messing up something obvious I apologize; what do I need to do to make sure the Matlab plugin gets installed?

`
ld: warning: ignoring file /Applications/MATLAB_R2022a.app/extern/bin/maci64/libMatlabEngine.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Applications/MATLAB_R2022a.app/bin/maci64/libMatlabDataArray.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Applications/MATLAB_R2022a.app/bin/maci64/libmex.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Applications/MATLAB_R2022a.app/bin/maci64/libmx.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_mexCallMATLABWithObject", referenced from:
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexErrMsgTxt", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexPrintf", referenced from:
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mexWarnMsgTxt", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
  "_mxCalloc", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxCreateDoubleMatrix_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxDestroyArray", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxFree", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetCell_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetField_730", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxGetM", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetN", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetPr", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxGetScalar", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
  "_mxGetString_730", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsCell", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsChar", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsComplex", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxIsDouble", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
      _user_pre in nlopt_optimize-mex.c.o
  "_mxIsFunctionHandle", referenced from:
      _mexFunction in nlopt_optimize-mex.c.o
  "_mxIsNaN", referenced from:
      _user_function in nlopt_optimize-mex.c.o
  "_mxIsNumeric", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
      _user_function in nlopt_optimize-mex.c.o
  "_mxIsStruct", referenced from:
      _make_opt in nlopt_optimize-mex.c.o
      _mexFunction in nlopt_optimize-mex.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/octave/nlopt_optimize.mexmaci64] Error 1
make[1]: *** [src/octave/CMakeFiles/nlopt_optimize-mex.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by jschueller** [comment]
seems matlab libs are still x86_64

**Comment by dtorre38** [comment]
I am able to run on an M2 MacBook Pro by following the NLopt steps although slightly modified:

1. Open terminal and cd to desired directory (e.g. Documents). 
2. git clone https://github.com/stevengj/nlopt.git.
3. cd nlopt.
4. mkdir build.
5. cd build.
6. cmake .. -DNLOPT_OCTAVE=Off -DNLOPT_MATLAB=Off -DNLOPT_GUILE=Off
7. make
8. sudo make install
