### ISSUE TITLE
failure building shared libs

### ISSUE THREAD

**Issue by ocramz** [stevengj/nlopt#44]
When building with `--enable-shared` on OSX, during the `make` phase , I get this sequence of errors, all concerning a handful of functions (`scm_is_true()`, `scm_from_long()` , `scm_from_locale_string()` ...); however I should point out that the static build works fine.

Part of the log when things start to go wrong:

Making all in swig
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I/opt/local/include -I../api   -g -O2 -MT libnlopt_guile_la-nlopt-guile.lo -MD -MP -MF .deps/libnlopt_guile_la-nlopt-guile.Tpo -c -o libnlopt_guile_la-nlopt-guile.lo `test -f 'nlopt-guile.cpp' || echo './'`nlopt-guile.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I/opt/local/include -I../api -g -O2 -MT libnlopt_guile_la-nlopt-guile.lo -MD -MP -MF .deps/libnlopt_guile_la-nlopt-guile.Tpo -c nlopt-guile.cpp  -fno-common -DPIC -o .libs/libnlopt_guile_la-nlopt-guile.o
In file included from /opt/local/include/libguile.h:50:0,
                 from nlopt-guile.cpp:730:
nlopt-guile.cpp: In function 'char* SWIG_Guile_scm2newstr(SCM, size_t*)':
nlopt-guile.cpp:817:32: error: 'scm_is_string' was not declared in this scope

... and then the following pattern:

nlopt-guile.cpp:2957:48: error: 'scm_is_true' was not declared in this scope
         _v = scm_is_true(scm_integer_p(argv[1])) && scm_is_true(scm_exact_p(argv[1]))? 1 : 0;
                                                ^
nlopt-guile.cpp: In function 'scm_unused_struct* _wrap_nlopt_opt_optimize__SWIG_0(int, scm_unused_struct**)':
nlopt-guile.cpp:3003:52: error: 'scm_from_locale_string' was not declared in this scope
       scm_list_1(scm_from_locale_string((_e).what())));
                                                    ^
nlopt-guile.cpp:3008:52: error: 'scm_from_locale_string' was not declared in this scope
       scm_list_1(scm_from_locale_string((_e).what())));
                                                    ^
nlopt-guile.cpp:3013:52: error: 'scm_from_locale_string' was not declared in this scope
       scm_list_1(scm_from_locale_string((_e).what())));
                                                    ^
nlopt-guile.cpp:3018:40: error: 'scm_from_long' was not declared in this scope
     gswig_result = scm_from_long(result); 
                                        ^
nlopt-guile.cpp: In function 'scm_unused_struct* _wrap_nlopt_opt_optimize__SWIG_1(int, scm_unused_struct**)':
nlopt-guile.cpp:3044:30: error: 'scm_is_vector' was not declared in this scope
     if (scm_is_vector(argv[1])) {
                              ^
nlopt-guile.cpp:3045:55: error: 'scm_c_vector_length' was not declared in this scope
       unsigned long size = scm_c_vector_length(argv[1]);
                                                       ^
nlopt-guile.cpp:3049:56: error: 'scm_from_ulong' was not declared in this scope
         SCM o = scm_vector_ref(argv[1],scm_from_ulong(i));
                                                        ^
nlopt-guile.cpp:3050:28: error: 'scm_is_number' was not declared in this scope
         if (scm_is_number(o))
                            ^
nlopt-guile.cpp:3051:44: error: 'scm_to_double' was not declared in this scope
         temp2[i] = (double)(scm_to_double(o));
                                            ^
nlopt-guile.cpp:3055:35: error: 'scm_is_null' was not declared in this scope
     } else if (scm_is_null(argv[1])) {
                                   ^
nlopt-guile.cpp:3058:35: error: 'scm_is_pair' was not declared in this scope
     } else if (scm_is_pair(argv[1])) {
                                   ^
nlopt-guile.cpp:3060:49: error: 'scm_c_vector_length' was not declared in this scope
       unsigned long size = scm_c_vector_length(v);

**Comment by stevengj** [comment]
I can't reproduce your problem on MacOS 10.10.4.  I did:
```
wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
tar xf nlopt-2.4.2.tar.gz
cd nlopt-2.4.2/
./configure --enable-shared && make
```
and it compiled without errors.

**Comment by jschueller** [comment]
This is due to using swig < 2.0.10.
Now the cmake infrastructure only enables guile bindings  if swig is recent enough.
