### ISSUE TITLE
nlopt Python API is broken on Python 3.10.2

### ISSUE THREAD

**Issue by lfdmotta** [stevengj/nlopt#441]
In Python 3.10.2, nlopt API is broken.

From a fresh Python 3.10.2 installation, create an environment,

`py -3 -m venv .venv`

activate the environment and install nlopt,

`py -3 -m pip install nlopt`

then you will get

> import nlopt
(....)
ModuleNotFoundError: No module named '_nlopt'

**Comment by jschueller** [comment]
[cc @DanielBok](https://github.com/DanielBok/nlopt-python/issues/8)

**Comment by lfdmotta** [comment]
how's is that a solution to the issue?

**Comment by jschueller** [comment]
it's not. the issue belongs to the maintainers of the pip packages
