### ISSUE TITLE
Apparent package config bug on CentOS 7

### ISSUE THREAD

**Issue by MiguelRodo** [stevengj/nlopt#444]
Hi

Thank you for the work maintaining this project.

So, on a server CentOS 7 machine I needed to install the R package [`nloptr`](https://github.com/astamm/nloptr), which makes use of `nlopt`, of course. However, a compilation issue arose that seems to be a bug with the `nlopt` package config output. 

Specifically, it assumes that the `nlopt` "installation" folder contains `lib`, when in fact it contains `lib64` only. 

To demonstrate, we installed `nlopt` into `/opt/exp_soft/nlopt-2.7.1`, and here is the output from `ls /opt/exp_soft/nlopt-2.7.1`:
```bash
include  lib64  share
```

However, compilation of `nloptr` fails, with the following two lines being the key parts of the error message:
```bash
g++ -std=gnu++11 -shared -L/opt/exp_soft/R-4.1.1/lib64/R/lib -L/usr/local/lib64 -o nloptr.so init_nloptr.o nloptr.o test-C-API.o test-runner.o -lopenblas -lgfortran -lm -lquadmath -L/opt/exp_soft/nlopt-2.7.1/lib -lnlopt -L/opt/exp_soft/R-4.1.1/lib64/R/lib -lR
/usr/bin/ld: cannot find -lnlopt
```

As you can see in the first line, one of the arguments is `-L/opt/exp_soft/nlopt-2.7.1/lib -lnlopt`, thereby referencing `lib` rather than `lib64`. The shared library `lnopt` is therefore not found.

We got around it by creating a symlink from `lib` to `lib64`. 

So, this is no longer a problem for us, but in case this is a bug and not due to some mistake we made I thought you should know. If you want further information, note that I did not do the installation (end-user, not sysadmin) and so can't say offhand how it was done (but I could ask). If you want specific information about the system, then please be specific about how to generate it, as I'm not experienced with these things. 

[Here](https://github.com/astamm/nloptr/issues/112) is the original thread discussing the issue (and others in installing `nloptr`).

**Comment by jschueller** [comment]
can you check if #445 fixes it ?

**Comment by MiguelRodo** [comment]
Hi @jschueller. Thank you for writing up a fix so quickly! I am more than happy to test it, but I would need to you to adapt the [README](https://github.com/stevengj/nlopt) installation instructions for non-root users (I am very new to Linux). I don't have root access to our HPC and our sysadmin does not want to troubleshoot further when we've got around the bug another way.

**Comment by jschueller** [comment]
ok, I see that nloptr uses pkgconfig, and I checked the new pkgconfig file have lib64  now
