### ISSUE TITLE
Error while R package installation on HPC

### ISSUE THREAD

**Issue by bioinfonext** [stevengj/nlopt#446]
Hi,

I am getting below error while installing R package methyloclock from bioconductor on HPC, could you please help me how I can solve this issue?

.```
......

[100%] Built target nlopt
CMake Error: The source directory "/tmp/RtmptnIJfW/R.INSTALL2e22ffdd3c9/nloptr/src/nlopt" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
cp: cannot stat 'nlopt/include/*': No such file or directory
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/bin/gcc -I"/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/include" -DNDEBUG -I../inst/include  -I'/mnt/scratch2/users/3052771/R/lib/testthat/include' -I/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/include   -fpic  -g -O2  -c init_nloptr.c -o init_nloptr.o
/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/bin/gcc -I"/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/include" -DNDEBUG -I../inst/include  -I'/mnt/scratch2/users/3052771/R/lib/testthat/include' -I/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/include   -fpic  -g -O2  -c nloptr.c -o nloptr.o
/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/bin/g++ -std=gnu++11 -I"/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/include" -DNDEBUG -I../inst/include  -I'/mnt/scratch2/users/3052771/R/lib/testthat/include' -I/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/include   -fpic  -g -O2  -c test-C-API.cpp -o test-C-API.o
/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/bin/g++ -std=gnu++11 -I"/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/include" -DNDEBUG -I../inst/include  -I'/mnt/scratch2/users/3052771/R/lib/testthat/include' -I/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/include   -fpic  -g -O2  -c test-runner.cpp -o test-runner.o
/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/bin/g++ -std=gnu++11 -shared -L/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/lib -L/opt/gridware/depots/54e7fb3c/el7/pkg/libs/blas/3.8.0/gcc-9.3.0 -L/opt/gridware/depots/54e7fb3c/el7/pkg/compilers/gcc/9.3.0/lib64 -o nloptr.so init_nloptr.o nloptr.o test-C-API.o test-runner.o -L/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/lib -lRlapack -L/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -Lnlopt/lib -lnlopt -L/opt/gridware/depots/54e7fb3c/el7/pkg/apps/R/4.1.3/gcc-9.3.0+lapack-3.9.0+blas-3.8.0/lib64/R/lib -lR
/usr/bin/ld: cannot find -lnlopt
collect2: error: ld returned 1 exit status
make: *** [nloptr.so] Error 1
ERROR: compilation failed for package ‘nloptr’
```
Many thanks

**Comment by jschueller** [comment]
report that to the nloptr package, we only maintain the core package, not the r bindings
