### ISSUE TITLE
COBYLA with nonlinear constraints gets stuck in infeasible regions

### ISSUE THREAD

**Issue by samuelkim314** [stevengj/nlopt#448]
My constraint is binary - either it is fulfilled or not - so I am using a nonlinear constraint function that returns -1 if it is feasible and +1 if it is infeasible. I start COBYLA in a feasible region, but sometimes it will immediately step into an infeasible region and get stuck there. So if I run it for 1000 iterations, it'll just spend 999 of those iterations in infeasible region. Has anybody seen this behavior before? Does it have to do with the binary constraint?

A workaround is to not use nonlinear constraints, but rather fold it into the objective function where it returns some fixed large negative value (for a maximization problem) in the infeasible region, and the actual objective function in the feasible region. However, I was seeing problems with poor convergence so I was hoping that using nonlinear constraints would help this.

**Comment by stevengj** [comment]
COBYLA works by constructing linear approximations, and it isn’t guaranteed to converge for non-differentiable functions. I’m not surprised it fails completely for a discontinuous constraint. 

By formulating the constraint like that, you’ve made it impossible to use any good optimization algorithm. You should really try to re-formulate your problem.
