### ISSUE TITLE
Looping over inequality constraints

### ISSUE THREAD

**Issue by bspoe** [stevengj/nlopt#450]
Hi there, 

I am currently trying to set up the constraints for a simplified optimization problem. Since I want to programmatically build the inequality constraints, I run a for loop and use different parameters as input to my constraint function. However, the method only uses the last declared constraint for its optimization. Furthermore, if we add a simple `i = 2` at the end of the loop, there will be an (Out of Range) error. It seems like the iteration variable is treated as a global one. 

Thanks for your help! 

```python
import nlopt
import numpy as np


def myfunc(x, grad):
    if grad.size > 0:
        grad[0] = 2*x[0]
        grad[1] = 2*x[1]
        grad[2] = 2*x[2]
    return x[0]**2 + x[1]**2 + x[2]**2 

def myconstraint(x, grad, a, b, i):
    if grad.size > 0:
        
        grad[0] = b[0]
        grad[1] = b[1]
        grad[2] = b[2]
    return a - x[i]

a = [1, 3]
b = [[-1 , 0, 0], [0, -1, 0]]
opt = nlopt.opt(nlopt.LD_CCSAQ, 3)
opt.set_min_objective(myfunc)
fs=[]

for i in range(2):

    fs.append(lambda x, grad: myconstraint(x, grad, a[i], b[i], i))
   
  
opt.add_inequality_constraint(fs[0], 1e-3)
opt.add_inequality_constraint(fs[1], 1e-8)
#i = 2

opt.set_xtol_rel(1e-4)
x = opt.optimize([7.234, 5.678, 4.562])
minf = opt.last_optimum_value()
print("optimum at ", x[0], x[1], x[2])
print("minimum value = ", minf)
print("result code = ", opt.last_optimize_result())


```

**Comment by stevengj** [comment]
That's not how `lambda` works in Python, unfortunately.  See e.g.

* https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture
* https://python.plainenglish.io/python-pitfalls-with-variable-capture-dcfc113f39b7
