### ISSUE TITLE
SLSQP runtime reduced by 25%!

### ISSUE THREAD

**Issue by pirlite2** [stevengj/nlopt#459]
Hi

Not so much an issue as flagging a success! 

I make extensive use of SLSQP, but it is fairly slow. Consequently, I have had a look at speeding it up by using the cblas implementations from the Intel Math Kernel Library (MKL) to replace the local cblas functions. On Linux Mint 20.3 and an i7-3770, I got the following for my code.

- nlopt out of the box = 123 minutes of core time (over 2 cores - my application uses multiple threads)
- nlopt built with a modified slsqp.c file that uses the MKL libraries = 94 minutes
- 
So I am pretty pleased with a 25% reduction for not  a lot of effort! Happy to post the (rather hacked up) source file if anybody is interested. I am guessing that other algorithms in nlopt also use local implementations of cblas routines so this may be more widely useful. Perhaps a refactoring that sequesters the local cblas functions into a separate file that is only included if the build machine does not have an optimsed blas installed?

One question I did want to ask: I do not know cmake so my tests above were done by manually building nlopt in an IDE; I was not able to see immediately how to link MKL into the regular build process (without a lot of work).  I am presuming that cmake can scout around for any installed optimised blas implementations and conditionally link them? Can anyone give me a hint how to do that because I don't really want to learn cmake just for this exercise?

Peter

**Comment by jschueller** [comment]
yes, cmake has a built-in macros to find blas variants : find_package(BLAS)
it is possible to manually pass BLAS_LIBRARIES variable to point to a specific location

**Comment by stevengj** [comment]
That being said, if you are using SLSQP with so many variables that BLAS time is significant, you might think about switching to a different algorithm that scales better, e.g. CCSA.
