### ISSUE TITLE
null pointer dereference in nlopt_optimize_ / nlopt_set_xtol_abs

### ISSUE THREAD

**Issue by gddl** [stevengj/nlopt#461]
_nlopt_optimize_(...)_ contains a few _nlopt_set_xtol_abs(local_opt, opt->xtol_abs)_ calls with _opt->xtol_abs_ beeing null since #268. This causes a null pointer dereference in _nlopt_set_xtol_abs(...)'s_ memcpy.

**Comment by jschueller** [comment]
is #462 ok for you ?

**Comment by gddl** [comment]
Yes, looks good. Thanks.

**Comment by jschueller** [comment]
@stevengj could you have a look ?
