### ISSUE TITLE
Non linear constraint optimisation problem

### ISSUE THREAD

**Issue by CollinMak** [stevengj/nlopt#463]
I have a non-linear constraint problem as below:

![image](https://user-images.githubusercontent.com/109043204/179400410-2ce16e74-6fff-494e-8008-4302017d7f11.png)

The objective and constraint functions can be expressed as the sum of 4th polynomial equations like below:

![image](https://user-images.githubusercontent.com/109043204/179400425-67932815-a2aa-4595-8c67-3b24f247e265.png)

where $a_i, b_i, c_i, d_i, e_i, p_i, q_i, r_i, s_i, t_i, l_i, u_i$ are some real constants. 

I need to solve this type of problem multiple times daily with a high dimension $x$ (with $n$ = 200k or even 1m).  I am wondering which algorithm is most suitable for this type of problem? Apologies if this is not directly relevant to the package.

**Comment by jschueller** [comment]
I think praxis or subplex are suited for high dimension

**Comment by stevengj** [comment]
If it's high dimension you really need to have a gradient-based algorithm, e.g. CCSA.
