### ISSUE TITLE
Possible bug re: ORIG_DIRECT

### ISSUE THREAD

**Issue by jmendelson256** [stevengj/nlopt#466]
Hello,

I have noticed some strange behavior re: ORIG_DIRECT.  For a particular function I'm optimizing, when I specify bounds of (0.2, 1.5), it yields a result well below 0.2, and gives a success return code.  The result returns is at odds with the detailed output:

Code:
```
set.seed(95293)
nloptr::nloptr(x0 = 0.85,
               eval_f = function(x) (-data_main$posterior_pdf_b_unscaled(x)),
               lb = .2,
               ub = 1.5,
               opts = list(algorithm = "NLOPT_GN_ORIG_DIRECT",
                           xtol_rel = 1e-08, print_level = 3, maxeval = 1e5))
```

Output:
```
iteration: 6559
	x = 0.200693
	f(x) = -0.000000
iteration: 6560
	x = 0.200495
	f(x) = -0.000000
iteration: 6561
	x = 0.200099
	f(x) = -0.000000

Call:
nloptr::nloptr(x0 = 0.85, eval_f = function(x) (-data_main$posterior_pdf_b_unscaled(x)), 
    lb = 0.2, ub = 1.5, opts = list(algorithm = "NLOPT_GN_ORIG_DIRECT", 
        xtol_rel = 1e-04, print_level = 3, maxeval = 1e+05))


Minimization using NLopt version 2.7.1 

NLopt solver status: 1 ( NLOPT_SUCCESS: Generic success return value. )

Number of Iterations....: 6561 
Termination conditions:  xtol_rel: 1e-04	maxeval: 1e+05 
Number of inequality constraints:  0 
Number of equality constraints:    0 
Optimal value of objective function:  -6.92768159318526e-22 
Optimal value of controls: 7.62079e-05

```

Any ideas what might be causing this?  Please let me know if you need more info.  (My function is a bit complicated, hence my example is admittedly not minimal.  It seems odd that the result is below the lower bound and yields a success code, though.)

**Comment by stevengj** [comment]
>when I specify bounds of (0.2, 1.5), it yields a result well below 0.2

These are bounds on `x`, not on `f(x)`, and you'll notice that your `x` is always ≥ 0.2.

**Comment by jmendelson256** [comment]
Thank you.  To clarify, the issue is not with the specific iterations displayed, but with the result being returned:

`Optimal value of controls: 7.62079e-05
`
This value is less than the lower bound, and is returned by the R wrapper (nloptr) as the solution.
