### ISSUE TITLE
Docs: NLopt with MinGW => broken link to MinGW

### ISSUE THREAD

**Issue by rolffank** [stevengj/nlopt#477]
Hi
In the docs "NLopt on Windows" there is a broken link to MinGW in chapter "NLopt with MinGW".
I need to create a 32-bit DLL for my application and I cannot use the precompiled binaries because I need the fix for the bug I reported.
I would be very happy if you could enhance the guide for compilation with MinGW, answer to my other post where I described my failed attempts to create a 32-bit DLL or provide updated precompiled binaries for Windows. 
Meanwhile I will try the instruction from [mahyaret](https://github.com/mahyaret) using MSYS2 (I already tried this before without success (https://github.com/stevengj/nlopt/issues/472))

Best regards and many thanks for your work!
Rolf

**Comment by jschueller** [comment]
[d7eb0cf](https://github.com/stevengj/nlopt/commit/d7eb0cf71061b4a2d2d1ff4283afa092d36a9a20)
