### ISSUE TITLE
nlopt_get_errormsg undocumented?

### ISSUE THREAD

**Issue by pirlite2** [stevengj/nlopt#483]
Hi
From what I can see, nlopt_get_errormsg is undocumented despite being introduced in v2.5. 

I found this function by accident when trying to run down a "can't see the forest due to the trees" problem, and it is massively useful. I would suggest something in the Reference guide at the end of the section on "Error codes (negative return values)" might be the best place?

In addition, the behaviour of nlopt_get_errormsg seems to terminate the whole process? I haven't traced it through, but I wasn't expecting that. If that is the intended behavior, a few words of explanation would be really helpful to prevent people using the function in, say, asserts and getting unexpected termination.

P.

**Comment by jschueller** [comment]
please provide a testcase if you got a bug

**Comment by pirlite2** [comment]
Any response to the fact that this really useful function seems to have been omitted from the documentation? (This will undoubtedly be helpful for many people.)  I am happy to suggest a suitable passage if that will help.

**Comment by jschueller** [comment]
yes, see https://github.com/stevengj/nlopt/commit/97a1e789d6e6cd46d94147a8fbcccf2ecb003aac
