### ISSUE TITLE
polynomial optimization

### ISSUE THREAD

**Issue by trlsmax** [stevengj/nlopt#485]
Hi, I'm not sure this is a problem nlopt can solve. If it's not, I'm sorry to disturb.

there are data xs[n], ys[n], targets[n] and polynomial v = f(x,y) = c[0] + c[1] * x + c[2] * y + c[3] * x^2 + c[4] * x * y + c[5] * y^2; 
I want to find values of c[] which make (f(xs[0], ys[0]) - targets[0]) + (f(xs[1], ys[1]) - targets[1]) + ....... + (f(xs[n-1], ys[n-1]) - targets[n-1]) the smallest value.

I don't know how to construct the objective function
double f(unsigned n, const double* x, double* grad, void* f_data);

Thank you.

**Comment by stevengj** [comment]
>I want to find values of c[] which make (f(xs[0], ys[0]) - targets[0]) + (f(xs[1], ys[1]) - targets[1]) + ....... + (f(xs[n-1], ys[n-1]) - targets[n-1]) the smallest value.

This doesn't make literal sense — the smallest value here is -∞.

You need to either square the terms, in which case this is linear least squares and is trivial with specialized solvers — or use absolute values (L1 minimization) or the maximum of the absolute values (Linf minimization), both of which are equivalent to linear programming (LP) problems and are best attacked with specialized solvers.

Of course, NLopt can handle these too, but the whole point of NLopt is to work for generic problems, so it will be less efficient than specialized solvers for least squares or LP.

**Comment by trlsmax** [comment]
> you could express your optimization problem as a least squares problem: https://en.wikipedia.org/wiki/Least_squares
> 
> it should work for small problems but nlopt is not dedicated to least-squares, as it only "sees" the global objective not the individual diffs I recommend scipy.optimize.least_squares in Python or cminpack in C

Thank you. I will looking into cminpack.
