### ISSUE TITLE
History of points

### ISSUE THREAD

**Issue by bram-vermeulen** [stevengj/nlopt#486]
For our research, we are using nlopt and we would like to draw the trajectory plot of the algorithms. Is there any way in nlopt that we can access the history of points because we can not find it in the manual? 

And for a second question, is there a way that we can alter the stepsize for the algorithms?

**Comment by jschueller** [comment]
one possibility is to store each new point at the end of the objective function in a global array

**Comment by bram-vermeulen** [comment]
Okay thank you very much!
