### ISSUE TITLE
Error with cmake and python 3.11.0 in windows 11

### ISSUE THREAD

**Issue by vincferr** [stevengj/nlopt#488]
I have been trying to build nlopt (tag: v2.7.1) with cmake 3.24.3 and it cannot build the python bindings as the visual studio project generated via cmake expects to link against python311_d.lib, which is not shipped with a regular installation of python 3.11.

To reproduce the behaviour, via "Developer Command Prompt for VS 2022" v17.4.3

```
cd nlopt
mkdir build & cd build
cmake -G "Visual Studio 17 2022" -DBUILD_SHARED_LIBS=OFF .. -B . 
msbuild INSTALL.vcxproj /t:build /p:configuration=debug /m:8
```

yields:
```
       "C:\sw_source\PVIM_CppDependencies\deps\nlopt\build\INSTALL.vcxproj" (build target) (1) ->
       "C:\sw_source\PVIM_CppDependencies\deps\nlopt\build\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\sw_source\PVIM_CppDependencies\deps\nlopt\build\src\swig\nlopt_python.vcxproj" (default target) (6) ->
       (Link target) ->
         LINK : fatal error LNK1104: cannot open file 'python311_d.lib' [C:\sw_source\PVIM_CppDependencies\deps\nlopt\b
       uild\src\swig\nlopt_python.vcxproj]

    78 Warning(s)
    1 Error(s)
```

of course, removing the python bindings fixes it.

```
rmdir /S /Q build
mkdir build & cd build
cmake -G "Visual Studio 17 2022" -DBUILD_SHARED_LIBS=OFF -DNLOPT_PYTHON=OFF .. -B . 
msbuild INSTALL.vcxproj /t:build /p:configuration=debug /m:8
```
returns
```
    51 Warning(s)
    0 Error(s)
```

I don't really need the python bindings, but I wanted to report it nonetheless.

**Comment by stevengj** [comment]
We are [just using](https://github.com/stevengj/nlopt/blob/e30e2b0415a99d9c9a11e841ef8432d0992376c4/CMakeLists.txt#L312) `cmake`'s [built-in `find_package(Python ...)` function](https://cmake.org/cmake/help/latest/module/FindPython.html), so if it is linking to the wrong library the problem should be reported to `cmake`.
