### ISSUE TITLE
Traces of optimization parameters

### ISSUE THREAD

**Issue by mabr2001** [stevengj/nlopt#490]
Hey folks,

Just wanted to check if there is any functionality to create traces of optimization parameters across iterations directly using the C++ library? Alternatively, if anyone has added this logging functionality with custom code and would be willing to share, that would be highly appreciated!

**Comment by mabr2001** [comment]
Figured it out...

**Comment by matheusdiogenesandrade** [comment]
Could you share?

**Comment by stevengj** [comment]
Just add a log to your objective function.  (Either a `printf` or saving values in an array for later usage.)

**Comment by matheusdiogenesandrade** [comment]
> Just add a log to your objective function. (Either a `printf` or saving values in an array for later usage.)

Thanks. But, let's suppose I want to obtain a thorough information throughout the execution, as Ipopt/Algencan/Cplex/Gurobi do. I do not see any problem in coding such functionality, but, is there any callback for this?

**Comment by stevengj** [comment]
What information do you want that you currently can't get.  Internal data of the algorithm?

**Comment by mabr2001** [comment]
> What information do you want that you currently can't get? Internal data of the algorithm? Your objective function has all the values of the optimization parameters and the corresponding function values.

Internal algorithm information would actually be pretty useful...

**Comment by matheusdiogenesandrade** [comment]
> Internal data of the algorithm?

For instance, let's take the [Algencan](https://github.com/pjssilva/Algencan.jl) logging system:

```
out penalt  objective infeas  scaled    scaled infeas norm   |Grad| inner Newton opt sc
ite         function  ibilty  obj-funct infeas +compl graLag infeas totit forKKT factor
  0         3.522D+07 2.D+03  3.975D+02 8.D+02 8.D+02 1.D+00 1.D+00    0   0   0 1.D+00
  1 1.D-13  0.000D+00 1.D+00  0.000D+00 1.D+00 1.D+00 1.D-13 1.D+00    2C  0   0 1.D+00
...
```

Or the Ipopt one:

```
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  6.2912432e+03 1.48e+03 9.90e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
...
```

Or the Cplex one:

```
        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap
*     0+    0                            0.0000        2.0000              ---
*     0     0      integral     0        2.0000        2.0000        0    0.00%
Elapsed time = 0.00 sec. (0.00 ticks, tree = 0.00 MB, solutions = 2)
```

Of course, there is no need for reporting all these information, even because depending of the chosen algorithm such info won't be available, however, providing some iterative info, as mentioned by [mabr2001](https://github.com/mabr2001), could be helpful.

> Your objective function has all the values of the optimization parameters and the corresponding function values.

Ok, could you show some code snippet on this? I suppose you are referring to the using of the parameter [`void* f_data`](https://nlopt.readthedocs.io/en/latest/NLopt_Reference/#objective-function) for this purpose.

```cpp
 double f(unsigned n, const double* x, double* grad, void* f_data);
```

Thanks and regards.
