### ISSUE TITLE
Adding a second equality constraint to SLSQP fails

### ISSUE THREAD

**Issue by pirlite2** [stevengj/nlopt#491]
I have been very successfully using SLSQP for constrained optimisation with a single equality constraint. When I try to add a _second_ equality constraint, this second call to the nlopt_add_equality_constraint function fails with a "too many equality constraints" error message. This happens consistently when  I reverse the order of adding the two equality constraints. I can see nothing in the docs that says that SLSQP cannot take more than one equality constraint. In fact, from my reading of the docs, I infer the exact opposite behaviour! In addition, the docs for the SLSQP algorithm state "We fixed a bug ... for the case where the number of equality constraints equals the dimension of the problem." which implies to me that the algorithm can take multiple equality constraints. 

Is the above failure expected behaviour? If this is expected, am I likely to fare any better with a vector-valued constraint and using nlopt_add_equality_mconstraint? (I will try this but is a major code rejig.)

FWIW: I submitted some suggested changes to the docs before Christmas that fixed some typos + expanded on the explanation of the incredibly useful nlopt_get_errmsg function. Any chance of that being reviewed and incorporated?

Peter

**Comment by jschueller** [comment]
please provide a minimal test-case

**Comment by jschueller** [comment]
did you submit a PR for  nlopt_get_errmsg ?

**Comment by pirlite2** [comment]
"did you submit a PR for nlopt_get_errmsg ?"

I thought I had.

**Comment by pirlite2** [comment]
Right. I have identified the problem. On closer inspection, this problem was only arising on the tenth invocation of the optimiser. I am using SLSQP to calibrate the parameters of a stochastically generated model, and on the tenth occasion, the model  (erroneously) produced had only one parameter. Hence SLSQP quite correctly refused to accept a second equality constraint. 

Could I suggest the error message returned by nlopt_get_errmsg is extended to the more informative "too many equality constraints for the number of problem dimensions".
