### ISSUE TITLE
v2.4.2.tar.gz

### ISSUE THREAD

**Issue by eeprude** [stevengj/nlopt#493]
Hi. Sorry to send this request here. I try to got the mailing lists but the links in the NLOPT webpage did not work.

Where could I get the tar.gz for version 2.4.2. I am trying to install MUQ2, and it automatically tries to get such version of NLOPT from its own "repository". However, such 2.4.2 tar.gz file is corrupt. If I make MUQ2 to download a new version of NLOPT, I get compilation errors within MUQ2 (probably using some functionality of NLOPT that has changed).

If you would like for me to send this request to another place, just let me know.

Thank you in advance,

Ernesto (eeprude@sandia.gov)

**Comment by marcoafo** [comment]
HI Ernesto, I have emailed you the requested version.

**Comment by eeprude** [comment]
Thank you very much, Marco. I got the other email with the tar.gz. Appreciated.

Ernesto.

From: Marco Afonso ***@***.***>
Reply-To: stevengj/nlopt ***@***.***>
Date: Monday, January 23, 2023 at 6:23 PM
To: stevengj/nlopt ***@***.***>
Cc: "Prudencio, Ernesto Esteves" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [stevengj/nlopt] v2.4.2.tar.gz (Issue #493)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

HI Ernesto, I have emailed you the requested version.
