### ISSUE TITLE
MMA move limit

### ISSUE THREAD

**Issue by bmdaj** [stevengj/nlopt#496]
Hi,

I am wondering if there is the possibility to modify the move limit in the Nlopt MMA algorithm.

**Comment by stevengj** [comment]
Write now these are not configurable, but the maximum stepsize σ in each variable is updated [here](https://github.com/stevengj/nlopt/blob/master/src/algs/mma/mma.c#L393-L396) in the code and would be easy to edit.  Might be nice to add a user parameter to alter the upper and lower step-size limits.
