### ISSUE TITLE
How to use it as thirdparty?

### ISSUE THREAD

**Issue by jinfagang** [stevengj/nlopt#500]
“nlopt.hpp”: No such file or directory

How can I include it by using it as thirdparty include?

**Comment by stevengj** [comment]
You have to install it in a directory where your compiler can find it.

**Comment by jinfagang** [comment]
@stevengj  I mean using as thirdparty and calling cmake to build, rather than manually build it and then build my own project...

this is not a **thirdparty** works like.

I need to automatically build.
