### ISSUE TITLE
Compiler internal error with VS2013 and VS2015

### ISSUE THREAD

**Issue by dariomt** [stevengj/nlopt#51]
More info about the problem and suggested workaround in Microsoft Connect
https://connect.microsoft.com/VisualStudio/feedback/details/1028781/c1001-on-release-build

Boils down to adding a #pragma on cobyla/cobyla.c before the loop around line 1503:

```
#pragma loop(no_vector)
for (k = 1; k <= i__1; ++k) {
     d__1 = 0., d__2 = vmultc[k] - ratio * vmultd[k];
     vmultc[k] = MAX2(d__1,d__2);
```

Would you accept a PR with the suggested workaround #ifdef'ed for VS2013 and VS2015?

**Comment by stevengj** [comment]
Sure.  Vectorizing this loop is not important.

**Comment by dariomt** [comment]
PR ready to merge

**Comment by dut09** [comment]
Hi,

I had exactly the same issue here, and dariomt's solution fixed it nicely. Could you please consider merging it to the master branch?

**Comment by stevengj** [comment]
Unfortunately, he never actually created a pull request in the main nlopt repo.   I'll try to grab it from his repo and file it as a PR here.

**Comment by dut09** [comment]
That will be great! Thanks!
