### ISSUE TITLE
Updating Optimisation Function in For Loop in C++

### ISSUE THREAD

**Issue by Kiguli** [stevengj/nlopt#518]
Hello,

I am trying to use nlopt for some code I am writing, I would like to update the function I use to optimise at each step in the for loop. This is because, as far as I can work out, there is no way to pass additional arguments for constants inside the function.

I tried doing this with lambda functions but it also throws errors. I was just wondering if anyone had tried to do this or had success?

Cheers for any help you can give :)

**Comment by stevengj** [comment]
You can use the `void* f_data` to pass additional information to the function (with C-style pointer casts).

**Comment by Kiguli** [comment]
Thanks, I have now managed to get it working. I defined a struct called data that I pass into set_min_optimization(f, &data). I had a lambda function within the optimisation function too, so I had to pass the function through the struct too. All a bit convoluted but now working! Thanks for the help!
