### ISSUE TITLE
Alternatives for automatic differentiation

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [stevengj/nlopt#526]
Hello.

I would like to know if NLOpt has any support for AMPL integration, or any other tool allowing automatic differentiation. For instance, [NLOpt.jl](https://github.com/JuliaOpt/NLopt.jl), provides a derivative-free interface. Although I am not sure how it is done behind the hood, I would say it makes use of the [JuMP automatic differentiation](https://github.com/jump-dev/Ipopt.jl/issues/381) support. I know there is support for [Matlab and Octave integration](https://nlopt.readthedocs.io/en/latest/NLopt_Installation/#matlab), but I am not so sure if the automatic differentiation functionality could be so easily implemented through these means.

Thanks and regards.

**Comment by jschueller** [comment]
gradients are user-provided, so you can choose anything you want
it also has some gradient-free algorithms (cobyla, bobyqa, ...)
