### ISSUE TITLE
AGS algorithm in Matlab 

### ISSUE THREAD

**Issue by mangelett** [stevengj/nlopt#532]
Hi,

I would like to use the AGS algorithm in Matlab. Does it is available ?
I try the C code in the the NLOPT tutorial with NLOPT_GN_AGS: the codes runs but the optimization fails with the return code -2. I also run the Python code of the issue #285 and I obtained a result. So I think the AGS algorithmis has been compiled during the installation. But inside MATLAB, the variable NLOPT_GN_AGS is not recognizer.

Thanks for your help

**Comment by stevengj** [comment]
Should be fixed by #532.  For now, you can work around this by simply passing `43` for the algorithm (since that's the value of the `NLOPT_GN_AGS` constant).

**Comment by mangelett** [comment]
Thank you for your answer.
