### ISSUE TITLE
Wrong usage of nlopt_optimize: opt vector field is not of length n

### ISSUE THREAD

**Issue by WinkySong** [stevengj/nlopt#539]
I encountered this problem when I used nlopt's matlab interface in win10 to solve a high-dimensional optimization problem containing nonlinear inequality constrains (the optimization variable is a column vector). After that, I tried the matlab routine of nlopt and found that this problem can only be avoided when the number of nonlinear inequality constraints is equal to the dimension of the optimization variable. However, in practical applications this is unreasonable, and the official website introduction states the two don't have to be equal, why is that? Hope it gets resolved, thank you!

**Comment by jschueller** [comment]
please provide a minimal code that helps reproduce the issue

**Comment by WinkySong** [comment]
Taking the officially provided matlab routine as an example, if the number of nonlinear inequality constraints of the two-dimensional optimization variables in the routine is reduced from 2 to 1, code as follows:

```opt.algorithm = NLOPT_LD_MMA
opt.lower_bounds = [-inf, 0]
opt.min_objective = @myfunc
opt.fc = { (@(x) myconstraint(x,2,0)) }
opt.fc_tol = [1e-8, 1e-8];
opt.xtol_rel = 1e-4
[xopt, fmin, retcode] = nlopt_optimize(opt, [1.234 5.678])
```

Error "Wrong usage of nlopt_optimize: opt vector field is not of length n" will be reported.

**Comment by stevengj** [comment]
You only have one constraint, but you are passing two values for `opt.fc_tol`.
