### ISSUE TITLE
Can't open Octave-4.0.0 plugin

### ISSUE THREAD

**Issue by acapobianchi** [stevengj/nlopt#54]
Hello @stevengj I've followed the installation instructions published at http://ab-initio.mit.edu/wiki/index.php/NLopt_on_Windows but I can't make the Octave plugin running. These are the steps I've gone through:
1. File "nlopt-2.4.2-dll64.zip" is unzipped in "D:\Installers\NLopt\nlopt-2.4.2-dll64"
2. Files "libnlopt-0.def" and "libnlopt-0.dll" are copied to "C:\Octave\Octave-4.0.0\i686-w64-mingw32\bin"
3. "C:\Octave\Octave-4.0.0\bin" is added to Windows Path in order to let dlltool.exe find "libz.dll"
4. "libnlopt-0.lib" is generated by dlltool.exe in a command window started at "C:\Octave\Octave-4.0.0\i686-w64-mingw32\bin"
5. "nlopt_optimize-oct.cc" and "nlopt_optimize_usage.h" are copied to "C:\Octave\Octave-4.0.0\i686-w64-mingw32\bin"
6. In "nlopt_optimize-oct.cc" all "Octave_map" are replaced with "octave_map" in order to get compatibility with Octave-4.0.0
7. In Octave Command Window, the following command is run:
   mkoctfile
    -ID:\Installers\NLopt\nlopt-2.4.2-dll64
    -IC:\Octave\Octave-4.0.0\include\octave-4.0.0\octave
    -IC:\Octave\Octave-4.0.0\include\octave-4.0.0
    -llibnlopt-0
    -LD:/Installers/NLopt/nlopt-2.4.2-dll64
    --output D:\Installers\NLopt\nlopt-2.4.2-dll64\nlopt_optimize.oct
    D:\Installers\NLopt\nlopt-2.4.2-dll64\nlopt_optimize-oct.cc
8. Result: file "D:\Installers\NLopt\nlopt-2.4.2-dll64\nlopt_optimize.oct" is generated!
9. file "D:\Installers\NLopt\nlopt-2.4.2-dll64\nlopt_optimize.oct" is copied to "C:\Octave\Octave-4.0.0\lib\octave\4.0.0\oct\i686-w64-mingw32"
10. >> nlopt_optimize
     error: library open failed: C:\Octave\Octave-4.0.0\lib\octave\4.0.0\oct\i686-w64-mingw32\nlopt_optimize.oct

Any idea why the library cannot be opened?
Thank you very much!
Alfredo

**Comment by jschueller** [comment]
maybe the nlopt dll was not in the PATH ?
