### ISSUE TITLE
FORCED_STOP return code

### ISSUE THREAD

**Issue by alexhwang0919** [stevengj/nlopt#554]
Hello, 

I keep getting a `FORCED_STOP` return code from my NLopt optimization using `BOBYQA`. 
When I ran the same Julia code script last month, I got a `SUCCESS` return code after 5 hours. 
Today, the code terminates in less than a second. 

I checked the **Forced termination** section of your documentation, and it seems to imply that a `FORCED_STOP` would only occur when the user decides to halt the process.

What are some other reasons why the program would terminate like in my case?

This is the code that I'm running; the `gmm_obj` function is from my own package. 

```
# Algorithm to use
method_name = "LN_BOBYQA"
method = :LN_BOBYQA

# Objective function
function f(θ::Vector, dummy_gradient::Vector)
    if length(dummy_gradient) > 0
        # do nothing
    end
    
    return gmm_obj(θ[1], θ[2], θ[3], θ[4], θ[5], θ[6], θ[7],
                   monthHolidayPerms, normDraws, empProbs)[1]
end

# NLopt
opt = Opt(method, 7) 
opt.min_objective = f 
opt.lower_bounds = [0.0, -0.99, -4.0, 0, 0, 0, 0]
opt.upper_bounds = [0.5, 0.99, 4.0, 0.5, 2, 0.3, 0.2]
opt.xtol_abs = 1e-8 
 
# initial values quite close to the optimum
θ0 = [0.055, 0.422, 1.777, 0.043, 1.782, 0.051, 0.025]
    
(minf, minx, ret) = optimize(opt::Opt, θ0)
```

**Comment by jco255** [comment]
when you just call your obj function, i.e. f(θ0, []) , does it return a reasonable value?

**Comment by alexhwang0919** [comment]
It did not, so I went back to my package and found out that there was an underlying issue. 
Thanks for your response, and sorry about such a basic question - I should have checked this first.
