### ISSUE TITLE
Numpy 2.0 compatibility

### ISSUE THREAD

**Issue by PaulJonasJost** [stevengj/nlopt#557]
Hello,

NLopt seems not to be compatible with numpy 2.0 yet ([see this CI](https://github.com/ICB-DCM/pyPESTO/actions/runs/9595626421/job/26463337234#step:6:136)).

**Comment by stevengj** [comment]
It looks like that's just a build thing — on the CI machine, it's apparently building/linking with numpy 1, but then at runtime Python is pulling in numpy 2, which is incompatible.

Hopefully if you build nlopt with numpy 2 it should be fine?

**Comment by jschueller** [comment]
yes, wheels just need a rebuild:
https://github.com/DanielBok/nlopt-python/issues/35
