### ISSUE TITLE
Suggestion to add library target which omits L-GPL deps (i.e luksan)

### ISSUE THREAD

**Issue by markusgft** [stevengj/nlopt#568]
Dear all, 
First of all, thanks for the great work, this is an incredibly useful package.
I have a question (and maybe suggestion) regarding the license of NLOpt, it being a collection of different (possibly modified) sources with different licenses from different authors. It looks like the large majority of original sources would be permissively licensable, only a few sources are non-permissively licensable, most outstandingly `src/algs/luksan/COPYRIGHT` which is L-GPL.
NLOpt as a whole might be considered L-GPL because everything is lumped into one main library target [here](https://github.com/stevengj/nlopt/blob/7cdebfe5f777b12d3c5b0788c38fe595444d69c6/CMakeLists.txt#L256).
Have you considered adding a separate library target (maybe called `nlopt_notice` or similar) which omits problematic headers and sources, such that you could offer a "reduced" version of NLOpt under permissive license? At first sight, this might be doable with a few modifications to CMakeLists. Your opinion would be very much appreciated, happy to discuss further!
Thank you
Markus

**Comment by markusgft** [comment]
Dear all, a friendly ping! Please let us know if the above suggestion is worth following up!

**Comment by markusgft** [comment]
https://github.com/stevengj/nlopt/pull/569 sketches out the basic idea behind the proposal above, I hope this is helpful. The changes are still incomplete, just for information and discussion.

**Comment by jschueller** [comment]
it would be easier not to create a new library but just exclude the ones you dont want
what's the use-case exactly ? LGPL is pretty permissive isnt it ? do you need explicitely something even more permissive ?

**Comment by markusgft** [comment]
> it would be easier not to create a new library but just exclude the ones you don't want

Thank you, that was a good comment. Of course this is easier, and I'll adopt it in the next update to above pullrequest!

> what's the use-case exactly ? LGPL is pretty permissive isnt it ? do you need explicitely something even more permissive ?

Eventually, I'll want to distribute commercial software, which (amongst many others) has NLOpt as a dependency. However, the specific aspect of NLOpt that we'll want to use is not L-GPL. The fact that Luksan cannot be easily dropped from NLOpt renders the whole package "unusable". So, we would like to be able to build a "subset" of NLOpt only.
Including the L-GPL deps would require us to use dynamic linking, see e.g. discussions [here](
https://softwareengineering.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app). Dynamic linking is unfortunately not an option for us, and the same holds for many other companies out there. I believe that the overall impact and distribution of NLOpt could be multiplied if we'd offer a version that was fully permissive!

**Comment by markusgft** [comment]
@jschueller are you okay with the general direction https://github.com/stevengj/nlopt/pull/569 is taking? Do I need to get any other stakeholders on board for this change? I would like to drive this to a mergeable state in a next step, unlike there are any  major concerns that need more in-depth discussion.
Thanks for your feedback so far!

**Comment by jschueller** [comment]
this is fine to me, maybe this just needs clarification about the resulting license when luksan is disabled, is it MIT ?
maybe this could be added in the https://nlopt.readthedocs.io/en/latest/NLopt_License_and_Copyright/ section
what do you think @stevengj ?

**Comment by markusgft** [comment]
Please also see the (small) modifications I proposed for the COPYING file in https://github.com/stevengj/nlopt/pull/569. Thanks!

**Comment by markusgft** [comment]
Friendly ping to @stevengj, your feedback is required to unblock https://github.com/stevengj/nlopt/pull/569 .

**Comment by markusgft** [comment]
* friendly ping, I am still waiting for feedback.
