### ISSUE TITLE
*_NOSCAL algorithms

### ISSUE THREAD

**Issue by jacopo-chevallard** [stevengj/nlopt#70]
It appears that the algorithms indicated on the [nlopt wiki](http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms) as 
```
NLOPT_GLOBAL_DIRECT_NOSCAL
NLOPT_GLOBAL_DIRECT_L_NOSCAL
NLOPT_GLOBAL_DIRECT_L_RAND_NOSCAL
```
should rather be indicated as
```
NLOPT_GN_DIRECT_NOSCAL
NLOPT_GN_DIRECT_L_NOSCAL
NLOPT_GN_DIRECT_L_RAND_NOSCAL
```

otherwise linking the library from a fortran program (which includes the ``include 'nlopt.f'`` line) raises a linking error.

Can you confirm this? or am I doing something wrong?

**Comment by champost** [comment]
I too ran into this problem (in C++) and it should be "GN" instead of 
"GLOBAL". This would also be consistent with the format for all the 
other global algorithms.

**Comment by stevengj** [comment]
Thanks, I've fixed the wiki.
