### ISSUE TITLE
c++ build not supported?

### ISSUE THREAD

**Issue by weakunix** [stevengj/nlopt#78]
Hi,
I cloned the latest code to investigate/fix the issues I was having. The `cmake` instruction seems to only build a C library. Is C++ interface not encouraged (supported) any more?
I'd also like to do static linking as well, but `cmake` builds a dynamic library.

**Comment by jschueller** [comment]
Hi,
You can take a look at the available options here:
https://github.com/stevengj/nlopt/blob/master/CMakeLists.txt#L26

**Comment by weakunix** [comment]
Hi,
I modified CMakeLists.txt:

    option (WITH_CXX "enable cxx routines" ON)
    option (BUILD_SHARED_LIBS "Build NLOPT as a shared library" OFF)
and re-ran `cmake .;make clean;make`, got exactly the same `libnlopt.so.0.9.0` back. Am I missing a step?

**Comment by jschueller** [comment]
These are meant to be set as command-line arguments: ```cmake -DWITH_CXX=ON -DBUILD_SHARED_LIBS=OFF```

**Comment by weakunix** [comment]
Thanks a lot!
