### ISSUE TITLE
wrong python prefix used

### ISSUE THREAD

**Issue by kjyv** [stevengj/nlopt#79]
When compiling and installing on macOS, my (macports) python interpreter and python-config at /opt/local/bin/python2.7-config is found and used for compiling. However, ./configure states `checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages`
and is apparently using the normal prefix, so the module is not found by python. It would be proper to install into `python2.7-config --prefix`/lib/python2.7/site-packages.

**Comment by jschueller** [comment]
that is expected behavior, it's up to you to specify the prefix

**Comment by kjyv** [comment]
Sorry, I think you misunderstand. The python files don't go into the prefix specified (with --prefix) but they go into whatever python2.7-config specifies. This might on some systems be the same prefix, in my case it is not. So for me the compiled library goes into /usr/ while the python interpreter and site-packages lives in /opt/local/, which is exactly where the found default python interpreter is and where the python header are taken from.

**Comment by jschueller** [comment]
oh, sorry, then this is unexpected. but we removed the autotools/configure script to only support cmake, which behaves as expected.
