### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by siddharthist** [stevengj/nlopt#87]
I'm running into issue https://github.com/stevengj/nlopt/issues/33. Could you make a new release that includes that fix, please? It would fix dozens of `R` packages on NixOS. 

Looks like the last one was in 2014!

**Comment by siddharthist** [comment]
@stevengj ping

**Comment by jschueller** [comment]
@stevengj how about we tag a new release ? 2.4.3 ? 2.5.0 ?

**Comment by tvatter** [comment]
I concur, @stevengj, it would be really appreciated.

**Comment by stevengj** [comment]
Should definitely be a minor version bump, since there are new API additions...

I agree that this is long overdue, just haven't had time to make sure things were ready.

**Comment by tvatter** [comment]
No problem, we are all busy :)

**Comment by jschueller** [comment]
I tried to look at the remaining opened issues and PR last week and closed a few. I think make install does nothing for matlab.

**Comment by jschueller** [comment]
I fixed the matlab install and updated the docs, so we're getting closer.

**Comment by jschueller** [comment]
ping @stevengj, still up for the release?

**Comment by stevengj** [comment]
Just tagged and released 2.5.0.
