### ISSUE TITLE
index expression error when calling nlopt_optimize

### ISSUE THREAD

**Issue by ankur-gupta** [stevengj/nlopt#92]
I get this error when I try to run the example in the Tutorial online.

```
error: invalid use of script /home/ankur/toolbox/nlopt/m/nlopt_optimize.m in index expression
error: called from
    nlopt_example at line 26 column 20
```

I noticed that `M_INSTALL_DIR/nlopt_optimize.m` contains only comments and happens to be earlier in the path than `OCT_INSTALL_DIR/nlopt_optimize.oct`. 

If I simply delete the `M_INSTALL_DIR/nlopt_optimize.m` file, then the example works.

**Comment by jschueller** [comment]
do you use matlab ? could you show your exact example script ?

**Comment by ankur-gupta** [comment]
I used Octave 4.0.0 on Kubuntu 16.10.  Code is below.  

I think cmake not installing `M_INSTALL_DIR/nlopt_optimize.m` could definitely solve the issue. 
Also, having `OCT_INSTALL_DIR/nlopt_optimize.oct` before `M_INSTALL_DIR/nlopt_optimize.m` in the path might also solve the issue (but this is might not be the best option because a user may alter the path and cause a break).

```
% nlopt example
 
close all; clear all; clc; more off; format short g
 
function [val, gradient] = myfunc(x)
    val = sqrt(x(2));
    if (nargout > 1)
        gradient = [0, 0.5 / val];
    end
end
 
 
function [val, gradient] = myconstraint(x,a,b)
    val = (a*x(1) + b)^3 - x(2);
    if (nargout > 1)
        gradient = [3*a*(a*x(1) + b)^2, -1];
    end
end
 
opt.algorithm = NLOPT_LD_MMA
opt.lower_bounds = [-inf, 0]
opt.min_objective = @myfunc
opt.fc = { (@(x) myconstraint(x,2,0)), (@(x) myconstraint(x,-1,1)) }
opt.fc_tol = [1e-8, 1e-8];
opt.xtol_rel = 1e-4
[xopt, fmin, retcode] = nlopt_optimize(opt, [1.234 5.678])
```

**Comment by jschueller** [comment]
I can reproduce the issue if I swap the octave paths in tests/CMakelist.

**Comment by stevengj** [comment]
In Matlab, we install `nlopt_optimize.m` just for the documentation (the `help` command looks for a `.m` file), and when you run the script it looks for the `.mex*` file (the compiled plug-in) first.

I think it used to be the same in Octave...it would always look for the `.oct` file first when executing, and the `.m` file for help.  But for this purpose the `.m` file must have the same name. Is there a different way to provide help in Octave nowadays, instead of putting it in the `.m` file?

**Comment by jschueller** [comment]
apparently the doc behavior has not changed, I guess the order has to be right

**Comment by stevengj** [comment]
Actually, now that I look at it, we pass the docstring in the `DEFUN_DLD` of `nlopt_optimize-oct.cc`, so we shouldn't have to install the `.m` file at all for Octave.

**Comment by ankur-gupta** [comment]
Yes, I think that's right. I can still access the docstring when I type in `help nlopt_optimize` which shows that the docstring is coming from the `.oct` file:


```
'nlopt_optimize' is a function from the file /home/ankur/toolbox/nlopt/oct/x86_64-pc-linux-gnu/nlopt_optimize.oct

Usage: [xopt, fopt, retcode] = nlopt_optimize(opt, xinit)

Optimizes (minimizes or maximizes) a nonlinear function under
...
```

This means we need not install the `nlopt_optimize.m` file for Octave.
