### ISSUE TITLE
Specifying OCT_INSTALL_DIR and M_INSTALL_DIR via cmake

### ISSUE THREAD

**Issue by ankur-gupta** [stevengj/nlopt#95]
I am trying to install NLopt to a specific location. I cannot figure out how to specify these options via cmake -- OCT_INSTALL_DIR and M_INSTALL_DIR -- as specified in http://ab-initio.mit.edu/wiki/index.php/NLopt_Installation.

Here is what I tried:

```
cmake . -DCMAKE_CXX_FLAGS=--std=c++0x \
    -DOCT_INSTALL_DIR=/home/ankur/toolbox/nlopt/m \
    -DM_INSTALL_DIR=/home/ankur/toolbox/nlopt/oct .
```

And this is what I get:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    M_INSTALL_DIR
    OCT_INSTALL_DIR
```

I'm sure I just don't know how to do this. Any help would be very much appreciated. Also, this might be useful information to put in README.md or the wiki page of this repo.

**Comment by jschueller** [comment]
you can now use INSTALL_M_DIR, INSTALL_OCT_DIR
