### ISSUE TITLE
Running tests with CTest is broken

### ISSUE THREAD

**Issue by mwoehlke-kitware** [stevengj/nlopt#98]
If I check out NLopt, build it, and try to run the tests with `ctest`, it fails horribly because `testopt` was not built.

The way this works is a non-standard workflow and prevents running the tests e.g. when NLopt is built as a CMake external project.

Please, either just build `testopt` by default (i.e. remove `EXCLUDE_FROM_ALL`), or else add an option (e.g. `NLOPT_ENABLE_TESTS`) that controls whether `testopt` is built by default *and* whether any `add_test` are invoked.

**Comment by jschueller** [comment]
there's a specific ```tests``` target to build ```testopt```

**Comment by mwoehlke-kitware** [comment]
> there's a specific `tests` target to build `testopt`

Yes, and...

>> The way this works is a non-standard workflow and prevents running the tests e.g. when NLopt is built as a CMake external project.

I'm building NLopt as an external project. The current configuration requires going through extra gyrations (manually adding an additional external project step) in order to use the tests. Trying to build and submit to CDash would be similarly complicated. This breaks typical workflows that work on the majority of CMake projects, and is surprising and inconvenient to users.

Please, be friendly to your users; `cmake && make && ctest` should not die horribly. Nothing needed to run tests should *ever* be `EXCLUDE_FROM_ALL`. Either just build it, *always*, or (usual pattern) have an `option` to disable *all* testing, including all `add_test`s (and possibly even `enable_testing()`). 

See e.g. [LCM](https://github.com/lcm-proj/lcm) for an example of how testing should be handled. Note in particular the `LCM_ENABLE_TESTS` option and how it is used.

**Comment by jschueller** [comment]
I excluded tests to mimic another project of mine that has a huge test base (450 c++ tests) and where "make tests" is almost as long as the lib build. A cmake option doesnt work for me as sometimes I just want the python bindings installed on top of the lib, or specific tests, and not often all the targets.

**Comment by stevengj** [comment]
The `testopt` program is tiny; there is no reason not to build it by default.

**Comment by jschueller** [comment]
That's reasonable.

**Comment by stevengj** [comment]
(I have to admit this seems to be a broken behavior of `ctest`.  With `automake`, you would type `make test` and the Makefile dependencies would build any programs that haven't been built yet.   It is a shame that `ctest` can't build dependencies, but in the short term there is nothing we can do about this.)

**Comment by jschueller** [comment]
We could also add a target that depends on tests exes and runs CMAKE_CTEST_COMMAND

**Comment by stevengj** [comment]
@jschueller, that sounds good to me, but my concern is that if `cmake && make && ctest` is the standard way to do this for `cmake` users then we should support this.

Put another way, I think `make check` or similar would be vastly better than running `ctest` separately, since that way test dependencies can be auto-built.   However, it is something that should really be done upstream: `cmake` itself should be patched so that a `check` target which runs `ctest` (after building a dependency target like `check-depends`) should be included in *every* `Makefile`.

**Comment by mwoehlke-kitware** [comment]
> We could also add a target that depends on tests exes and runs CMAKE_CTEST_COMMAND

Please don't; this is still non-standard and will still create the same problems for CDash and/or when using NLopt as an external project.

`cmake && make && ctest` should work. Besides that users may be used to this from other projects, this is essentially what external projects and CDash rely on and expect. Inserting another target in there that must be built makes things harder for these use cases.

**Comment by mwoehlke-kitware** [comment]
Thanks again!
