### ISSUE TITLE
missing externals from libm

### ISSUE THREAD

**Issue by mwoehlke-kitware** [stevengj/nlopt#99]
When I build NLopt, I get a lot of errors like:

```
nlopt/newuoa/newuoa.c:385: undefined reference to `sincos'
nlopt/isres/isres.c:93: undefined reference to `ceil'
nlopt/isres/isres.c:242: undefined reference to `exp'
nlopt/isres/isres.c:266: undefined reference to `sqrt'
nlopt/slsqp/slsqp.c:1325: undefined reference to `sqrt'
nlopt/esch/esch.c:39: undefined reference to `tan'
nlopt/api/optimize.c:458: undefined reference to `pow'
nlopt/util/mt19937ar.c:230: undefined reference to `log'
nlopt/util/mt19937ar.c:230: undefined reference to `sqrt'
nlopt/util/stop.c:199: undefined reference to `__fpclassify'
```

...and many more. Please add the missing link to libm.

**Comment by stevengj** [comment]
@mwoehlke-kitware, what operating system and compiler are you using?

We should definitely be linking `-lm`.  @jschueller, I'm guessing that this got lost in the `cmake` transition?

**Comment by mwoehlke-kitware** [comment]
Fedora 21, gcc 4.9... but I'm also using `-Wl,--no-undefined` (as I do for just about everything I build) to have `ld` complain about things that aren't linked and should be.

**Comment by mwoehlke-kitware** [comment]
:tada: Thanks for the quick fix!
